openshift/hac-dev

package.json, test.sh
This PR enables the upload of coverage to codecov using the codecov's new bash uploader 
Signed off by msawood@redhat.com
=> chore: upload code coverage to codecov

config/dev.webpack.config.js, config/plugins.js, src/dynamic-plugin-sdk.ts
https://issues.redhat.com/browse/HAC-381
Adds in a `dynamic-plugin-sdk.ts` file into the root of `/src` (I can move it wherever you want though); this is effectively a blackbox to HAC-Dev. You can pry if you want & modify if you want, but exposed API is planned to be this structure come the NPM release in Jan. These are utilities to effectively open up your code to use k8s resources from DevSandbox.
Few major notes:
-  `dynamic-plugin-sdk.ts` is short lived... the file will be deleted in the long run and replaced with NPM; I have disabled eslint in this file
- I recommend you treat this as an npm package and not play with the internals, but they are free to do so if you need to fix a function's internals or want to improve the hook... I'd recommend not changing the signature of anything …
=> Adds temp dynamic-plugin-sdk k8s utils

src/components/ReviewComponents/ReviewComponentsForm.tsx, src/components/ReviewComponents/ReviewComponentsPage.tsx, src/components/ReviewComponents/__tests__/validation-utils.spec.ts, src/components/ReviewComponents/validation-utils.ts, src/shared/components/formik-fields/EditableLabelField.tsx, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/HAC-505
There was no validation for component name, which allowed adding any invalid value. This change adds a validation schema to component name to enforce the value to be of the format: `^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
https://user-images.githubusercontent.com/20013884/151558995-5a7e74db-2d6b-41dc-b140-1e696477a90d.mp4
Enter an invalid component name in the review components section.
=> Validate component name to match the correct format

OWNERS
No fix
Please remove me from the OWNERS file - I don't have enough understanding for reviewing random PRs in this repo. 
Once we have for example e2e tests subfolder, I'm fine being included in the OWNERS file in there, but being in root OWNERS makes no sense for me. Thx.
=> Remove rhopp from OWNERS

src/Routes.tsx, src/components/AddComponent/AddComponentPage.tsx, src/components/ApplicationListView/ApplicationList.tsx, src/components/ApplicationListView/ApplicationListHeader.ts, src/components/ApplicationListView/ApplicationListRow.tsx, src/components/ApplicationListView/__tests__/ApplicationList.spec.tsx, src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx, src/components/ComponentListView/ComponentListView.tsx, src/components/ComponentSamples/ComponentSamplesPage.tsx, src/components/CreateApplication/CreateApplicationPage.tsx, src/components/ReviewComponents/ReviewComponentsPage.tsx, src/shared/components/index.ts, src/shared/components/page/Page.scss, src/shared/components/page/Page.tsx, src/shared/components/page/__tests__/Page.spec.tsx, src/shared/components/page/index.ts, src/shared/components/table/Table.tsx, src/shared/components/table/TableData.tsx, src/shared/components/table/TableRow.tsx, src/shared/components/table/VirtualBody.tsx, src/shared/components/table/index.ts, src/shared/components/timestamp/Timestamp.tsx, src/shared/components/timestamp/__tests__/Timestamp.spec.tsx, src/shared/components/timestamp/datetime.ts, src/shared/style/_common.scss
https://issues.redhat.com/browse/HAC-542
- the Applications list page lists all the applications if available otherwise the empty state is being shown, the most recently deployed application is listed first
- user can create a new app by clicking on the `Create Application` button on the list page
- clicking on the application name will take the user to the Composition view page
- added tests
Goto URL : https://prod.foo.redhat.com:1337/beta/hac/app-studio/applications
=> applications list view

src/components/ComponentListView/ComponentListItem.tsx, src/components/ComponentListView/ComponentListViewPage.tsx, src/components/ComponentListView/__tests__/ComponentListViewPage.spec.tsx
https://issues.redhat.com/browse/HAC-543
Adds a name filter to componentListView
npm run verify
=> Add name filter to componentList View

src/components/ComponentListView/ComponentListItem.tsx, src/components/ComponentListView/ComponentListViewPage.tsx, src/components/ComponentListView/__tests__/ComponentListViewPage.spec.tsx, src/shared/components/action-menu/ActionMenu.tsx, src/shared/components/action-menu/ActionMenuContent.tsx, src/shared/components/action-menu/ActionMenuItem.tsx, src/shared/components/action-menu/ActionMenuToggle.tsx, src/shared/components/action-menu/__tests__/ActionMenu.spec.tsx, src/shared/components/action-menu/action-menu-utils.ts, src/shared/components/action-menu/types.ts, src/utils/delete-utils.ts
https://issues.redhat.com/browse/HAC-544
- Added Delete action in the kebab menu which on clicked will delete the component CR
- Added tests
Goto: https://prod.foo.redhat.com:1337/beta/hac/app-studio/components?application=<application-name>
=> Add delete action in the Component list page

src/utils/__tests__/route-utils.spec.ts, src/utils/route-utils.ts
https://issues.redhat.com/browse/HAC-833
UI crashed if there was no route available for a component. Added a null check in route utils to avoid it.
=> Fix route utils when no route is available for the component

nginx.conf
Since we don't have regular connection to hac-core extension let's build regular console.dot application image. This way we can present the application on console.dev environment and prepare all the necessary piping.
=> Allow accessing regular console.dot app static files

deploy.yml, package-lock.json
Unable to access hac-dev on console.dev
Deployment of hac-dev is currently possible only with `console.dot` approach, let's update the deploy script to include navigation and module reference.
=> Use console.dot deploy mechanism

src/dynamic-plugin-sdk.ts, src/shared/components/action-menu/ActionMenuItem.tsx, src/shared/components/catalog/CatalogController.tsx, src/shared/components/catalog/CatalogTile.tsx, src/shared/components/catalog/catalog-view/CatalogCategories.tsx, src/shared/components/catalog/catalog-view/CatalogFilters.tsx, src/shared/components/catalog/catalog-view/CatalogGrid.tsx, src/shared/components/catalog/catalog-view/CatalogView.tsx, src/shared/components/catalog/utils/catalog-utils.tsx, src/shared/components/catalog/utils/category-utils.ts, src/shared/components/catalog/utils/filter-utils.ts, src/shared/components/markdown-view/MarkdownView.tsx, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/status-box/StatusBox.tsx, src/shared/components/timestamp/datetime.ts, src/shared/utils/keyword-filter.ts, src/shared/utils/line-buffer.ts, src/shared/utils/router.ts
Static assets are too large.
Since local development doesn't have tree shaking and other optimization tools enabled we have to care how libraries are loaded. One problematic place is lodash, importing the entire library means that we'll be adding 0.6MB to our bundles. We can either use `lodash-es` or directly importing each function. Since we don't want to overlook any mistakes I adopted importing just the function.
```
assets by path js/*.js 8.76 MiB
assets by chunk 7.78 MiB (id hint: vendors) 9 assets
10 assets
assets by path css/*.css 44 KiB 8 assets
assets by path fonts/*.svg 5.08 KiB
asset fonts/restricted-sign.svg 2.38 KiB [emitted] [from: src/imgs/restricted-sign.svg]
asset fonts/skeleton-chart.svg 1.72 KiB [emitted] [from: src/imgs/skeleton-chart.svg] (auxiliary name: …
```
=> Import just the used lodash functions

config/remotePlugin.js
Inaccessible UI due to error `Uncaught ReferenceError: loadPluginEntry is not defined`
There's a new usage of default entry callback available and it's not compatible with the old one. Let's use the first the new one so we don't break the UI.
=> Use default entry callback settings

config/remotePlugin.js
Chrome's context is inaccessible
Since we are using slightly different shared module scope than chrome is using scalprum provider is not accessible and that causes loading of new provider if `useChrome` is used. This PR fixes such issue by including it in shared modules consumed from `hac-core` application.
=> Consume scalprum core to use chrome's context

src/components/AddComponent/SourceField.tsx, src/components/AddComponent/__tests__/SourceField.spec.tsx, src/components/AddComponent/__tests__/utils.spec.ts, src/components/AddComponent/utils.ts, src/dynamic-plugin-sdk.ts, src/types/component-detection-query.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/HAC-556
The CDQ was being constantly fetched with a 200ms delay asynchronously inside a loop,
and would not stop until the detection was completed.
This caused the fetching to continue even after the section was unmounted.
This PR replaces the fetch with a watch hook that only updates when the CDQ has changed.
https://user-images.githubusercontent.com/20013884/162475561-4b506d7f-69ed-4a69-a738-f476615c4d20.mp4
=> Use watch hook for component detection

config/remotePlugin.js
There will be in near future adjustment to extension types from `console.` to `core.` ones.
Let's duplicate all extensions with type `core.` for some time until we remove the PoC code from `hac-core`.
=> Start using core extensions in favor of console

build_deploy.sh, pr_check.sh
To match feature parity with backed apps, we use `COMPONENT` as our app-interface folder and use the full `IMAGE` name.
=> Fix: Use IMAGE instead of component name

build_deploy.sh, pr_check.sh
Quick fix for PR checks that are breaking `hac-core` deploys.
Fixes an issue that causes bonfire to deploy hac-core incorrectly in PR checks for e2e.
=> Fix: use hac-dev as COMPONENT

src/components/ComponentSamples/ComponentSamplesPage.scss, src/components/ComponentSamples/ComponentSamplesPage.tsx, src/components/ComponentSamples/SamplesEmptyState.tsx, src/components/ComponentSamples/__tests__/ComponentSamplesPage.spec.tsx
https://issues.redhat.com/browse/HAC-1239
Replace the use of `CatalogView` with a simple tile selector.
Navigate to sample selection page.
=> Replace samples catalog with simple tile selector

integration-tests/support/pageObjects/createApplication-po.ts, integration-tests/support/pages/ApplicationDetailPage.ts, src/components/ApplicationDetailsView/component-actions.tsx, src/components/LogViewer/BuildLogViewer.tsx, src/components/modal/DeleteResourceModal.tsx, src/components/modal/__tests__/DeleteResourceModal.spec.tsx, src/components/modal/createModalLauncher.tsx
https://issues.redhat.com/browse/HAC-1318
Adds confirmation modal for component deletion.
https://user-images.githubusercontent.com/20013884/172129206-f0b27584-a6fe-4649-9683-8701de158332.mp4
Delete a component from kebab menu.
=> Add confirmation modal for component deletion

src/components/AddComponent/GitOptions.tsx
- https://issues.redhat.com/browse/HAC-1434
- We need the multi component checkbox in git options to support multi component import.
https://user-images.githubusercontent.com/6041994/172453317-57e37d94-8ef1-414e-bc67-9b96dde74c83.mov
=> Bring back multi component checkbox in git options

integration-tests/support/commands/hooks.ts
unifies cookie disclaimers handling for local/console.dev/CI env - by completely skipping them
=> Skip cookie disclaimers for all cypress tests

src/shared/components/dropdown/BasicDropdown.tsx
https://issues.redhat.com/browse/HAC-1537
The basic dropdown component uses an additional state to manage the selected dropdown item, and ignores the prop value. This caused it to not show the correct value unless it was manually changed.
Navigate to the review components page, unit dropdown should be preselected with value form CDQ.
=> Remove state from basic dropdown component

src/components/ApplicationListView/ApplicationListRow.tsx, src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx
https://issues.redhat.com/browse/HAC-1419
Show a skeleton if the component count has not loaded.
https://user-images.githubusercontent.com/20013884/173863593-2b31129b-ba94-475f-a423-af682fbd5609.mp4
Navigate to applications list view.
=> Show component count only after load

config/remotePlugin.js, package-lock.json, package.json, src/hacbs/__tests__/hacbsFeatureFlag.spec.tsx, src/hacbs/hacbsFeatureFlag.ts
https://issues.redhat.com/browse/HACBS-796
Adding a new route `.../hac/hacbs` which can be first loaded to enable the hacbs feature flag until full model feature flag support is present.
This will help demo hacbs UI in the short term.
No change to UI.
go to `.../hac/hacbs` and the page should redirect to `.../hac/app-studio` as well as log to the console `HACBS Flag enabled`
=> add route /hacbs to enables the hacbs feature flag

src/hacbs/components/ApplicationDetails/DetailsPage.scss, src/hacbs/components/ApplicationDetails/DetailsPage.tsx, src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx, src/hacbs/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx, src/hacbs/components/ApplicationDetails/__tests__/HacbsApplicationDetails.spec.tsx, src/hacbs/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx, src/hacbs/components/ApplicationDetails/tabs/CommitsTab.tsx, src/hacbs/components/ApplicationDetails/tabs/ComponentsTab.tsx, src/hacbs/components/ApplicationDetails/tabs/EnvironmentsTab.tsx, src/hacbs/components/ApplicationDetails/tabs/PipelineRunsTab.tsx, src/pages/ApplicationsPage.tsx
https://issues.redhat.com/browse/HACBS-699
PR contains the application details view page layout
- Tabs with empty state
- Actions
- Components tab contains the component list as app studio
```
PASS  src/hacbs/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
DetailsPage
✓ should render the DetailsPage (23 ms)
✓ should render the DetailsPage (5 ms)
✓ should not render the tabs if invalid values are passed (3 ms)
✓ should render the tabs (15 ms)
✓ should render the tabs (30 ms)
✓ should not render the actions if it is not passed (4 ms)
✓ should not render actions invalid values are passed to actions (5 ms)
```
```
PASS  src/hacbs/components/ApplicationDetails/__tests__/HacbsApplicationDetails.spec.tsx
HacbApplicationDetails
✓ should render spinner if application data is not …
```
=> Add Hacbs Application details view layout

src/pages/ApplicationsPage.tsx
[Use Feature flags](https://github.com/openshift/hac-dev/pull/140) in Application details page instead of queryparams (`&hacbs=true`) to gate hacbs UI elements.
With this changes, once you visit `/hacbs` route, then you should see hacbs specific application details page (tabbed view).
=> Use hac build service feature flags to gate app details view

config/remotePlugin.js, src/hacbs/__tests__/hacbsFeatureFlag.spec.tsx, src/hacbs/hacbsFeatureFlag.ts
Additional feature flag support via extension was added to HAC-core recently.
This PR adds support across all of app studio to enable HACBS via a query string param:
Set `hacbs=true` on any page URL.
set `hacbs=true` in the URL and then navigate to an application details page. Observe the details page displays tabs instead of a typical app studio component based via.
cc @mfrances17 @karthikjeeyar
=> hacbs feature flag support via query string param

src/hacbs/components/topology/__data__/pipeline-test-data.ts, src/hacbs/components/topology/__tests__/dag.spec.ts, src/hacbs/components/topology/__tests__/topology-utils.spec.ts, src/hacbs/components/topology/dag.ts, src/hacbs/components/topology/topology-utils.ts, src/shared/components/pipeline-run-logs/types/pipeline.ts, src/shared/components/pipeline-run-logs/types/pipelineRun.ts
Converts the Tekton data into graph data model. This data model will be integrated with the pf pipeline framework.
Pipeline graph order is determined using:
-  Resource dependencies:
[results](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#emitting-results-from-a-pipeline) of one Task being passed into params or when expressions of another
- ordering dependencies:
[runAfter](https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#using-the-runafter-field) clauses on the corresponding Tasks
Contains the utility for converting the tekton model into topology graph model.
No UI changes.
```
PASS  src/hacbs/components/topology/__tests__/topology-utils.spec.ts
topology-utils: 
extractDepsFromContextVariables: 
✓ should return emtpy array for invalid values (2 ms)
✓ …
```
=> Add data model for pipelinerun visualization

src/shared/components/formik-fields/ResourceLimitField.tsx
https://issues.redhat.com/browse/HAC-1286
Bug in formik causes validation to happen on the previous value instead of the updated value when `setFieldTouched` is used.
I tried all workarounds from https://github.com/jaredpalmer/formik/issues/2083 but this is the only one that worked.
https://user-images.githubusercontent.com/20013884/177797951-40a04ef8-b43f-4da8-817c-9c4f937522ca.mp4
Try to add negative values in resource limit field.
=> Run validation with updated resource values

config/remotePlugin.js, jest.config.js, src/hacbs/components/ApplicationDetails/tabs/PipelineRunsTab.tsx, src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunEnterpriseContractTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunEventsTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunTaskRunsTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunYamlTab.tsx, src/hacbs/components/PipelineRunListView/PipelineRunListHeader.ts, src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx, src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx, src/hacbs/models/index.ts, src/hacbs/models/pipelineruns.ts, src/hacbs/pages/PipelineRunPage.tsx, src/hacbs/types/index.ts, src/hacbs/types/pipeline.ts, src/hacbs/types/pipelineResource.ts, src/hacbs/utils/pipeline-utils.ts, src/types/index.ts
https://issues.redhat.com/browse/HACBS-381
With the decision to create one large monorepo for app studio and its features/plugins, I've added a hacbs subdir under hac-dev to contain all hacbs front end UI code. This particular PR creates the initial structure and includes the pipeline run list page that was demo'd in M5, so we can establish initial code in hac-dev and continue to build onto it for MVP and beyond.
Pipelinerun list:
Pipelinerun details:
Pipelineruns will not appear by default. It was decided to hide hacbs in the UI until feature flags become available. To view pipelineruns, use /hac/hacbs in the URL to get the tabbed interface, then choose the pipelineruns tab.
=> Add HACBS initial pipeline run list and details

integration-tests/utils/Common.ts
The test was reloading the page to access the list of applications even when it already was on the correct page. 
Adding a check to not reload the page and if needed, go to the page by using the URL. The test is also using UI when deleting the app (click Applications in the left menu) so this functionality is still covered in tests.
=> Don't reload the page if the test is already there.

src/components/ApplicationDetailsView/ApplicationDetailsView.tsx, src/components/ApplicationListView/ApplicationListView.tsx, src/components/GettingStartedCard/GettingStartedCard.scss, src/components/GettingStartedCard/GettingStartedCard.tsx, src/pages/WorkspaceSettingsPage.scss, src/pages/WorkspaceSettingsPage.tsx
https://issues.redhat.com/browse/HAC-1946
Make getting started card images responsive.
https://user-images.githubusercontent.com/20013884/180005724-104163fd-4897-4a88-8957-2d43d37e47a6.mp4
=> Fix image sizing for getting started cards

src/components/modal/DeleteResourceModal.tsx, src/components/modal/__tests__/DeleteResourceModal.spec.tsx, src/components/modal/resource-modals.tsx
https://issues.redhat.com/browse/HAC-1963
Use display name instead of resource name for app delete modal.
https://user-images.githubusercontent.com/20013884/181466615-6ee7c445-0595-4daa-8912-4b03f1fe860c.mp4
Open application delete modal.
=> Use display name for application delete confirmation modal

src/components/ImportForm/SampleSection/SampleSection.tsx, src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
https://issues.redhat.com/browse/HAC-1983
Detected components were not being reset if catalog tile is deselected.
https://user-images.githubusercontent.com/20013884/182419900-3786d23f-c4a5-4819-954b-da507ec2e446.mp4
Click the same sample tile twice
=> Reset detected components if sample tile is deselected

src/hacbs/components/ApplicationDetails/ApplicationQuickstartContent.ts, src/hacbs/components/ApplicationDetails/DetailsPage.tsx, src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx, src/hacbs/components/ApplicationDetails/__tests__/HacbsApplicationDetails.spec.tsx
https://issues.redhat.com/browse/HACBS-827
Displays a quickstart in a right-side panel the first time a new application has been successfully created in HACBS. On subsequent application creations, the quickstart is no longer shown.
**Screen shot:**
**Movie:**
https://user-images.githubusercontent.com/39063664/182902832-dc253e02-e4b7-4fd4-ac9a-7d5f2341525d.mov
1. With HACBS active, create a new application. Upon successful completion, the quickstart will appear in a right-side panel. 2. When the quickstart is completed/dismissed, create another application. The quickstart will no longer appear when the application creation is completed.
=> Adds quickstart for HACBS applications

src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx
Adds the PipelineRun log viewer to the Logs tab of the PipelineRun details page.
Create an application and component.
Go to the application details `PipelineRuns` tab. 
Click on a pipeline run name to go to the PLR details page.
Go to the `Logs` tab.
=> render log viewer in PLR logs tab

src/components/ImportForm/SourceSection/SourceSection.tsx, src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
https://issues.redhat.com/browse/HAC-1992
Avoid creating binding and show error message when a repo from unknown provider is used.
Enter an unknown provider url.
=> Avoid creating binding when provider is unknown

src/hooks/__tests__/useSearchParam.spec.ts, src/hooks/useSearchParam.ts
Add a hook for working with a single URL search param in a way that mimics `useState`. Updates to the search param will be notified via react-router.
```
const [value, set, unset] = useSearchParam('name', '');
```
=> add hook to get and set a URL search param like useState

src/hacbs/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/hacbs/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
https://issues.redhat.com/browse/HACBS-991
For the initial early phase of the hacbs project, unit tests were encouraged but not required, as all code residing under /hacbs was temporarily exempt from code coverage. Most functionality still included unit tests as part of their merge as good practice, except for the pipelineruns list and details pages. Now that the exemption for /hacbs has been lifted, we need to add these unit tests so our test coverage remains high.
N/A - unit tests only
Verify that the tests pass as part of the build
N/A
=> HACBS: Adds unit tests for PLR list and details

src/components/ImportForm/utils/submit-utils.ts, src/hacbs/components/ImportForm/BuildSection.tsx, src/hacbs/components/ImportForm/__tests__/BuildSection.spec.tsx, src/hacbs/components/ImportForm/utils/__tests__/submit-utils-spec.ts, src/hacbs/components/ImportForm/utils/submit-utils.ts, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx, src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx, src/hacbs/consts/pipelinerun.ts, src/hacbs/hooks/useBuildPipelines.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
Enable the PAC on HACBS workflow by adding the `pipelinesascode` annotation in component creation flow.
https://user-images.githubusercontent.com/9964343/185442410-bee55725-b1f7-476f-b6be-f3b89b5d9b8c.mov
1. Fork a devfile repository eg: https://github.com/devfile-samples/devfile-sample-go-basic 
2. Install this Appstudio staging  [GitHub App](https://github.com/apps/appstudio-staging-ci) in your forked repository.
3. use the forked repository to create component in the UI.
```
Create Utils
✓ Should call k8s create util with pipelines-as-code annotations (1 ms)
✓ Should not update pipelines-as-code annotations for the existing components without pac annotations (2 ms)
✓ Should contain pipelines-as-code annotations for the existing components with pac annotations (1 ms) 
```
=> Enable Pipelines as code in HACBS workflow

src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx, src/hacbs/components/ApplicationDetails/tabs/EnvironmentsTab.tsx, src/hacbs/components/ApplicationDetails/tabs/IntegrationTestsTab.tsx, src/hacbs/components/IntegrationTestsListView/IntegrationTestListHeader.ts, src/hacbs/components/IntegrationTestsListView/IntegrationTestListRow.tsx, src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx, src/hacbs/components/IntegrationTestsListView/__data__/mock-integration-tests.ts, src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListRow.spec.tsx, src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx, src/hacbs/components/IntegrationTestsListView/useIntegrationTestActions.tsx, src/hacbs/components/PipelineRunListView/PipelineRunListHeader.ts
Fixes: https://issues.redhat.com/browse/HACBS-997
Lists all integration tests associated with the application. Currently only the `Delete` action is available.
Create an application with an integration test
Go to the application details Integration tests tab
=> Add HAC BS integration tests tab for applications

src/components/ImportForm/utils/__tests__/auth-utils.spec.ts, src/components/ImportForm/utils/auth-utils.ts
Fixes an issue related to https://github.com/openshift/hac-dev/pull/169
It was observed that entering a valid Git URL for a component may result in the error `This provider is not supported`:
The cause of this is that the SPI access check resource is fetched and considered `loaded` even though the controller may not have processed the check yet and therefore there is no `status` in the resource. At some later point in time, the controller will have processed the check and added a valid `status`. The fix here is to continue to wait until a `status` is present in the resource. We return `loaded = false` to the caller until the `status` appears. 
To reproduce this, go to the import wizard and enter a Git URL for a component. If it immediately goes to validated, continue to change the git url …
=> wait for access check to have a status

src/hacbs/components/ImportForm/ImportForm.tsx, src/hacbs/components/ImportForm/__tests__/ImportForm.spec.tsx, src/hacbs/components/ImportForm/useImportSteps.tsx, src/hacbs/components/ImportForm/utils/submit-utils.ts
Fix the "Go to application" link in the from the wizard not navigating to the application page.
The "Go to application" link would always navigate to the application list instead of the application details page.
With HACBS enabled.
Start the create application wizard.
Enter an application name and click next.
Click the "Go to application" link.
=> fix 'Go to application' from wizard

src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts, src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts, src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts, src/hacbs/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts
https://issues.redhat.com/browse/HACBS-1061
Handle Workflow visualization with environments that has `parentEnvironment` set to a non-existing environment name.
Before:
After: 
Create an Environment in an application with invalid parentEnvironment name
```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Environment
metadata:
name: poc
spec:
type: poc
deploymentController: appstudio
deploymentStrategy: Manual
displayName: Test Environment
parentEnvironment: non-existing-environment 
tags:
- test
clusterCredentials:
apiServerURL: http://example.com/prod
configuration:
env:
- name: env
value: test
```
=> fix workflow visualization with non existing parent environment

src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx, src/hooks/__tests__/useSearchParam.spec.ts, src/hooks/useSearchParam.ts, src/utils/test-utils.tsx
If there are multiple uses of `useSearchParam` where the search params are updated multiple times in the same thread of execution, after the first update, subsequent updates are using a stale value of the previous search params.
The fix is to read directly from `window.location.search` when performing an update .
- Enable HACBS.
- Go to `Settings` page
- Ensure there is at least one environment; create if necessary
- Enter a name filter that matches no environments
- Set a type filter
- When there are no matches, the empty state shows a "Clear all filters" button
- Click "clear all filters"
Observe that it requires 2 clicks to clear all the filters because the first click only clears the type filter. 
With the fix, both the type filter and name filter would be cleared.
cc …
=> fix useSearchParam using stale value with multiple update

config/remotePlugin.js, src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx, src/hacbs/components/ImportForm/useImportSteps.tsx, src/hacbs/components/IntegrationTestForm/IntegrationTestForm.tsx, src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx, src/hacbs/components/IntegrationTestForm/IntegrationTestView.tsx, src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx, src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx, src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx, src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx, src/hacbs/pages/IntegrationTestPage.tsx
Fixes [HACBS-820](https://issues.redhat.com/browse/HACBS-820)
Allows users to add an integration test to an existing application, either from the empty state or from the actions menu for an application.
Navigate to an Application.
From the `Actions` menu, select `Add integration test`
Navigate to an application that has no integration tests.
Click the `Add integration test` button.
=> Add ability to add an integration test to an application

integration-tests/support/pageObjects/createApplication-po.ts, integration-tests/support/pageObjects/hacbs-po.ts, integration-tests/support/pages/ComponentsPage.ts, integration-tests/support/pages/hacbs/AddIntegrationTestPage.ts, integration-tests/support/pages/hacbs/ComponentsTabPage.ts, integration-tests/support/pages/hacbs/CreateBuildPage.ts, integration-tests/support/pages/hacbs/OverviewTabPage.ts, integration-tests/tests/hacbs/add-component-to-application-via-hacbs-tab.spec.ts, integration-tests/utils/Common.ts, integration-tests/utils/HACBSApplications.ts, src/components/ComponentsListView/ComponentListView.tsx, src/hacbs/components/ApplicationDetails/DetailsPage.tsx, src/hacbs/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx, src/hacbs/components/Commits/AppRecentCommits.tsx, src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx
_Main aim of the PR:_ To add UI tests for the following scenario,
* Using the **"Application Details View Page"**:
* Enabling HACBS UI.
* Adding a component while creating an application.
* Adding a component by using the "Overview" tab.
* Adding a component by using the "Components" tab.
* Adding a component by the "Actions" drop-down.
[Test Recording](https://drive.google.com/file/d/1sBZUW80OqFH2sF37BZTT4Zj8U39LuTwL/view?usp=sharing)
=> HACBS UI tests: Application Details View

src/components/ImportForm/utils/__tests__/cdq-utils.spec.ts, src/components/ImportForm/utils/cdq-utils.ts
- https://issues.redhat.com/browse/HAC-2206
- The CDQ loaded status was dependent on the watch resource hook returning the loaded value but it is not correct if we want to make sure the component detection is actually completed.
- This resulted in the error state of `No components detected` being shown when the detection was not complete yet.
- This PR updates the logic for loaded value of `useComponentDetection` to actually use completed status from CDQ. 
https://user-images.githubusercontent.com/6041994/191248964-455d1631-7361-4ffc-a674-136b11a69ccb.mov
=> Fix wrong CDQ loading status

config/remotePlugin.js, src/hacbs/__tests__/hacbsFeatureFlag.spec.tsx, src/hacbs/hacbsFeatureFlag.ts
When the query string method of `?hacbs=true` was introduced to enable the hacbs feature flag, the `/hac/hacbs` route method stopped working.
There's no benefit to keeping both methods around so I'm choosing to remove the route method. It is a method that isn't as usable as the query string method.
no UI change
visit `/hac/hacbs` and observe that the route is no longer available.
=> remove /hac/hacbs route for enabling hacbs feature flag

src/components/ApplicationDetailsView/ApplicationDetailsView.tsx, src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx, src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
Some bread crumbs links contained an extra `:` in the URL.
Although this was only noticeable on the pipeline run details page because the last segment of a breadcrumb does not show a URL right now.
Go to pipeline run details page and click the `pipeline runs` breadcrumb to go to the application details page on the pipeline runs tab.
=> fix breadcrumb links

src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx, src/hacbs/components/TaskRunListView/TaskRunListRow.tsx, src/hacbs/components/TaskRunListView/__tests__/TaskRunListRow.spec.tsx, src/shared/components/pipeline-run-logs/StatusIcon.tsx
https://issues.redhat.com/browse/HACBS-1176
https://issues.redhat.com/browse/HACBS-1177
Adds Status icon to
1. PLR details header
2. PLR list
3. TaskRun List
=> add pipelinerun & taskrun status

src/hacbs/components/IntegrationTestsListView/IntegrationTestListRow.tsx
Fixes [HACBS-1167](https://issues.redhat.com/browse/HACBS-1167)
Remove external link icon where the displayed text is the full url.
=> Remove unnecessary external icon link

src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts, src/hacbs/components/PipelineRunDetailsView/RelatedPipelineRuns.tsx, src/hacbs/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/hacbs/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx, src/hacbs/consts/pipelinerun.ts, src/hacbs/utils/pipeline-utils.ts
Fixes [HACBS-1022](https://issues.redhat.com/browse/HACBS-1022) and [HACBS-1025](https://issues.redhat.com/browse/HACBS-1025).
Adds more detail to details page:
- Labels
- Log snippet
- Created at
- Pipeline
- ~~Owner~~
- ~~Triggered by~~
- Application
- Source
- ~~Workspace~~
As part of this PR, it also includes breadcrumb change so user can return to the pipelinerun list, and removal of the Enterprise Contract tab (1025). Also some minor changes to existing details code e.g. handling plural units in duration value.
PLR Details top:
PLR Details bottom:
PLR Details w/ annotations and labels expanded:
Select an existing pipelinerun to view the details page.
=> More complete changes to pipelinerun details page

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
https://issues.redhat.com/browse/HAC-2299
Reset the `detectionFailed` formik field after runtime is manually selected.
https://user-images.githubusercontent.com/20013884/196224248-ffc6c858-553a-473b-88f4-05d62f7df27d.mp4
Use a repo whose runtime cannot be detected, and then manually select a runtime for it.
=> Reset formik error check after runtime is selected

src/hacbs/components/EnterpriseContractView/const.ts
Fixes [HACBS-1290](https://issues.redhat.com/browse/HACBS-1290)
The URL for the json data for release policies has changed
=> HACBS: Fix url for enterprise contracts release policies.

src/hacbs/components/ImportForm/create-utils.ts, src/hacbs/components/ImportForm/types.ts, src/hacbs/components/ImportForm/utils/__tests__/create-utils.spec.ts, src/hacbs/components/IntegrationTestsListView/IntegrationTestListRow.tsx, src/hacbs/components/IntegrationTestsListView/__data__/mock-integration-tests.ts, src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListRow.spec.tsx
https://issues.redhat.com/browse/HACBS-1362
Add `test.appstudio.openshift.io/optional: true/false` to mark an `integrationTestScenario` optional instead of `spec.optional` (no longer valid).
1. Add an Integration test and mark it as optional.
2. The integration test CR should contain the optional labels.
```
Create Utils
✓ Should contain the optional test value in the labels (1 ms)
✓ Should not contain the optional label if the test is mandatory
```
```
IntegrationTestListRow
✓ should read the optional field from label (8 ms)
✓ should show mandatory value if the optional labels are not set (8 ms)
```
=> add optional label to mark a integration test as optional

src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts, src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
`No tests set` displayed when there are tests
App with no components and no tests:
Go to the overview tab and observe that
=> fix `No tests set` group label when tests are present

src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
[HACBS-1008](https://issues.redhat.com/browse/HACBS-1008)
When trying to create a component that doesn't need to use any port, if I leave the "Target port" text box empty, nothing happens when I click on the "Create components & continue".
**Before fix:** 
**After fix:** 
In component review section, remove the tagertPort value under `Deploy Configuration` section and click on `create component & continue` button
```
Create Utils
✓ Should create component with target port
✓ Should create component without target port, if it is not passed (1 ms)
```
=> Fix component creation without targetPort

config/remotePlugin.js, package-lock.json, package.json
Unable to access unleash client values provided from chrome.
Application can't access values from unleash client to use feature flags. Hac-core will be sharing (**merge after!** https://github.com/openshift/hac-core/pull/116) unleash client values so we have to use the shared deps and use the values as well.
=> Enable unleash client from chroming service

integration-tests/docker/Dockerfile, pr_check.sh
Run tests in a docker as a host user. Currently, if a job is interrupted during running tests, Jenkins fails to remove files generated by this test. Running as a host user should help to solve that.
=> Run docker as host user.

integration-tests/plugins/index.ts
report portal plugin was left enabled for local e2e test runs, disable it
=> Force disable report portal plugin when running tests locally

config/remotePlugin.js
Redirect from `/app-studio` to `/stonesoup` isn't working when the user has yet to signup.
https://github.com/openshift/hac-dev/pull/277 changed the url to `/stonesoup` and at the same time added a redirect from `/app-studio`. However the redirect route still had the `SIGNUP` flag as a requirement. Simply removed the flag so that the redirect would work as expected.
Create a new RHD account that has yet to sign up.
Go to `/hac/app-studio`.
Observe the page fails to load.
With this change, a redirect to `/stonesoup` would happen and then the signup page will load.
=> remove flags from redirect

integration-tests/tests/create-application-from-private-git-form.spec.ts, integration-tests/tests/create-application-from-private-git-source.spec.ts, integration-tests/tests/create-application-from-private-quay-image.spec.ts, integration-tests/tests/create-application-from-public-git-source.spec.ts, integration-tests/tests/create-application-from-public-quay-image.spec.ts, integration-tests/tests/create-application-from-sample.spec.ts, integration-tests/tests/hacbs/add-component-to-application-via-hacbs-tab.spec.ts, src/hacbs/__tests__/hacbsFeatureFlag.spec.tsx, src/hacbs/hacbsFeatureFlag.ts
https://issues.redhat.com/browse/HAC-2492
- set HACBS FLAG as `true` by default
- HACBS can be disabled by adding to url `hacbs=false`
- HACBS can be disabled by setting localstorage `hacbs` to `true`
Changes HACBS feature flag test
=> enable hacbs by default

config/remotePlugin.js
Allows to use quickstarts dependency.
[RHCLOUD-23088](https://issues.redhat.com//browse/RHCLOUD-23088)
When using quickstarts from patternfly the page doesn't load and there's an error that eager consumption of react is not ready. This PR removes the quickstarts from shared dependency list to allow usage of `@patternfly/quickstarts` package.
=> Do not include quickstarts in shared deps

src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
https://issues.redhat.com/browse/HAC-2643
Log snippet and Message fields are shown only when the pipeline is failed. Removed the hard coded summary task log and replaced it with the actual failure message.
**Before:**  (shows the logs from show-summary task instead of failed task)
**After:**
Shows the failure message: 
Error fields are not shown when the pipeline is succeeded.
```
PipelineRunDetailsTab
✓ should not render the error fields for the succeeded pipelinerun (25 ms)
✓ should render the error fields for the failed pipelinerun (28 ms)
```
=> Fix the error fields to show actual pipeline failure messages

src/__data__/pipelinerun-data.ts, src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/PipelineRunVisualization.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx, src/components/PipelineRunListView/pipelinerun-actions.tsx, src/components/topology/__data__/pipeline-test-data.ts, src/shared/components/pipeline-run-logs/types/coreTekton.ts, src/shared/components/pipeline-run-logs/types/pipeline.ts, src/types/coreTekton.ts, src/types/pipeline-run.ts, src/types/pipeline.ts, src/utils/__tests__/pipeline-utils.spec.ts, src/utils/pipeline-actions.ts, src/utils/pipeline-utils.ts
https://issues.redhat.com/browse/HAC-2574
Add Rerun action to the pipelinerun list and details pages.
https://user-images.githubusercontent.com/9964343/208454478-21ab7916-cd50-413a-ad9c-91d6ebc1cef4.mov
Go to pipelineruns list page/details to find the rerun action in the kebab/action dropdown.
```
src/utils/__tests__/pipeline-utils.spec.ts
getDuration
✓ handles invalid values (2 ms)
✓ returns correct durations in short format (1 ms)
✓ returns correct durations in long format (1 ms)
calculateDuration
✓ should return definite duration (4 ms)
getRandomCharacters
✓ should return 6 digit random alphanumeric characters as default (1 ms)
✓ should return 2 digit random alphanumeric characters (1 ms)
getPipelineRunData
✓ should return null (43 ms)
✓ should have a different name for the new …
```
=> Add pipelinerun rerun action

config/remotePlugin.js, src/utils/flag-utils.ts
[
](https://issues.redhat.com/browse/HAC-2688)
Adds a feature flag for mvp using the flags extension point.
Feature flagged the settings page route as well as the navigation link. Unfortunately there seems to be a bug with the navigation links not obeying feature flags. Therefore these links were simply commented out.
The mvp feature flag can be controlled by the developer using the query string param `?mvp=true|false` as well as through the local storage by setting `mvp=true|false`. By default the flag is enabled.
The flag can be tested by going directly to the url `/hac/stonesoup/workspace-settings` with the mvp feature flag set to `true` or `false` using the query param or local storage.
=> feature flag and remove settings page for mvp

src/components/ImportForm/ApplicationSection/ApplicationSection.tsx, src/components/ImportForm/ImportForm.tsx
- https://issues.redhat.com/browse/HAC-2337
- Updated application name field to only show a placeholder text instead of input value.
=> Update application name field to only show placeholder text

config/remotePlugin.js, src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx, src/components/ApplicationDetails/tabs/overview/sections/__tests__/AppWorkflowSection.spec.tsx, src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts, src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx, src/utils/flag-utils.ts
https://issues.redhat.com/browse/HAC-2649
Hides the release and managed environment nodes in the application lifecycle visualization when the MVP flag is set to true.
The mvp feature flag can be controlled by the developer using the query string param `?mvp=true|false` as well as through the local storage by setting `mvp=true|false`.
Note: This PR is built on top of https://github.com/openshift/hac-dev/pull/296, here is the commit to be reviewed is 2ea2edb9d0fa687d6c25fdcb99c2ff10010bfd4b
**MVP flag is set to true:**
**MVP flag is set to false:**
Visit an Application details page and add `&mvp=true` to the URL.
```
useAppWorkflowData hook
✓ should return workflow nodes without release and managed environments when mvp flag is true (1 ms)
```
cc: @christianvogt @rohitkrai03 @megan-hall
=> hide release and managed environment nodes in lifecycle visualization for mvp

src/__data__/pipelinerun-data.ts, src/shared/components/pipeline-run-logs/StatusIcon.tsx, src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts, src/shared/components/pipeline-run-logs/utils.ts
https://issues.redhat.com/browse/HAC-2644
Adds `Cancelling` status to the pipeline runs that are already cancelled and still finishing up the current tasks (this could be finally tasks as well). Doing this will prevent the user from cancelling the pipelinerun again and again and provides the actual state of the pipelinerun.
**Before:**
https://user-images.githubusercontent.com/9964343/208898535-614c1bca-a0f2-405e-af6f-6ea146961ce4.mp4
**After:** 
https://user-images.githubusercontent.com/9964343/208898548-15296b4a-1f57-403a-a945-129454b383c9.mp4
Stop/Cancel a running Pipeline, it should mark the pipelinerun status as cancelling and stop/cancel actions in the dropdown should be disabled.
```
pipelineRunStatus
✓ should return null if an invalid pipelineruns (2 ms)
✓ should return Pending …
```
=> Add cancelling status for pipelineruns

src/components/ApplicationDetails/ApplicationDetails.tsx, src/components/ApplicationDetails/DetailsPage.tsx, src/components/ApplicationDetailsView/ApplicationSwitcher.tsx
https://issues.redhat.com/browse/HAC-2622
=> add Context Switcher to Application details view

src/components/ImportForm/SourceSection/SourceSection.tsx
https://issues.redhat.com/browse/HAC-2377
Adds missing icons near the Learn more quickstart link  in Add component step.
=> add learn more missing icon in component step

src/components/Commits/CommitDetailsView.tsx, src/components/Commits/CommitSidePanelHeader.tsx, src/components/Commits/CommitsListRow.tsx, src/components/Commits/__data__/pipeline-with-commits.ts, src/components/Commits/__tests__/CommitsListRow.spec.tsx, src/components/Commits/__tests__/CommitsListView.spec.tsx, src/components/Commits/__tests__/commit-status.spec.ts, src/components/Commits/commit-status.ts
https://issues.redhat.com/browse/HAC-2620
Show commit status in commit list rows in the commits list page.
Go to commits list page.
=> Show commit status in commit list row

src/components/Components/BuildStatusColumn.tsx, src/components/Components/__tests__/BuildStatusColumn.spec.tsx, src/components/ComponentsListView/BuildStatusColumn.tsx
https://issues.redhat.com/browse/HAC-2845
In components list view, `Merge build PR`  and followed by `view logs` status is shown before the actual component status.
**Solution:**
Wait for pipeline runs call to resolve before showing any status.
https://user-images.githubusercontent.com/9964343/211794262-daf6cbcd-cd43-46e7-a698-848d977f9182.mov
```
BuildStatusColumn
✓ should not render merge status if the pipelineruns is still loading (5 ms)
✓ should not render View Build logs action item for components without build pipelinerun (4 ms)
```
=> fix merge build pr status in component list view

src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
https://issues.redhat.com/browse/HAC-2864
If When expression is not met, then the task will be skipped and collected in `pipelinerun.status.skippedTasks` but we were checking based on the task status (non-existent in this case) and marked those tasks as Idle.
**Solution:**
Finding skipped tasks in `pipelinerun.status.skippedTasks` and marking it as skipped to get the right icon.
**Before:** 
**After:**
```
appendStatus
✓ should append Skipped status for the tasks without status/reason but marked as skippedTasks in pipelinerun status
```
1. Cancel the running pipeline, which should mark all the remaining tasks as Skipped tasks.
=> Fix skipped task icon in pipelinerun visualization

src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts, src/shared/components/pipeline-run-logs/StatusIcon.scss, src/shared/components/pipeline-run-logs/StatusIcon.tsx, src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts, src/shared/components/pipeline-run-logs/utils.ts
https://issues.redhat.com/browse/HAC-2863
Pipeline visualization uses icons from pf-pipelines package and pipeline run logs uses a custom statusIcon component causing inconsistencies in the pipeline icons between graph and logs component.
**Solution:**
Using PF status icon as base and extending it to support some custom intermediate states (cancelling state - used to better notify the plr state to the user and avoid any actions on plrs that are being cancelled).
Note: we need this to be added in the PF package to avoid custom handling. will log a bug on PF for this new state.
https://user-images.githubusercontent.com/9964343/212138664-70a2dc13-a2e3-42e1-82a5-44021026bdd0.mov
---
**Fixed the status label background colors**
1. go to pipelinerun details page and switch between details and …
=> Use PF pipelines statusIcon component for icon consistency in plr logs and graph

src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
- https://issues.redhat.com/browse/HAC-2830
- Add `'skip-initial-check': 'true'` annotation when creating component without PAC.
No change in the UI.
=> Add skip initial check annotation while creating components

src/utils/gitops-utils.scss, src/utils/gitops-utils.tsx
https://issues.redhat.com/browse/HAC-2953
Spin animation was missing for build running status in component list view.
https://user-images.githubusercontent.com/9964343/213522839-54b50448-e0fa-4c69-8bd5-e68087e2a005.mov
=> Add spin animation to running build status icon

src/components/ImportForm/utils/__tests__/transform-utils.spec.ts, src/components/ImportForm/utils/transform-utils.ts
https://issues.redhat.com/browse/HAC-2882
In certain circumstances, CDQ responds with no default values for the CPU and memory limits. As such the UI had implemented values which were considered too high.
Reduced the defaults to 50Mi and 10millicores.
=> reduce default resources

src/components/Commits/__tests__/commit-status.spec.ts, src/components/Commits/commit-status.ts, src/components/PipelineRunListView/PipelineRunListRow.tsx, src/shared/components/pipeline-run-logs/__tests__/utils.spec.ts, src/shared/components/pipeline-run-logs/utils.ts
https://issues.redhat.com/browse/HAC-2917
The status and duration of a new pipeline run that has yet to start is incorrect. The duration should probably show `-` and the status should as well or some other waiting to start state.
https://user-images.githubusercontent.com/9964343/213528869-99efaee5-e575-4438-9ac9-d2b2e5338532.mov
1. rerun the pipelinerun in the pipelinerun list view.
=> fix initial pipelinerun status text and duration field

integration-tests/support/pageObjects/createApplication-po.ts, src/components/ComponentsListView/ComponentListItem.tsx, src/components/ComponentsListView/__tests__/ComponentListItem.spec.tsx, src/hooks/__data__/mock-data.ts, src/utils/__tests__/route-utils.spec.ts
- https://issues.redhat.com/browse/HAC-2787
- https://issues.redhat.com/browse/HAC-2929
- https://issues.redhat.com/browse/HAC-2968
- Update the component list view to show routes for the component on top of the card.
- Updated component details labels.
=> Show routes as component URL on component cards

src/components/LogViewer/BuildLogViewer.tsx, src/components/LogViewer/__tests__/BuildLogViewer.spec.tsx, src/hooks/useComponentPipelineRun.tsx
https://issues.redhat.com/browse/HAC-2983
view build logs opens logs with test pipelineruns but the Build logs modal should always show the build pipelinerun logs.
**Before:**
**After:**
```
BuildLogViewer
✓ should show empty box if it is not a build pipelinerun (3 ms)
```
When your component has both build and test pipelineruns, the build log viewer should always show the logs for your build pipelinerun.
=> view build logs should only show the build pipelinerun logs

src/components/Commits/__data__/pipeline-with-commits.ts, src/utils/__tests__/commits-utils.spec.ts, src/utils/commits-utils.ts
https://issues.redhat.com/browse/HAC-2993
PR number is displayed as `#undefined` in the UI because the PR number is being read from PLR annotations instead of labels
before:
after:
- [ x Chrome
=> read PR number from pipeline run label

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
https://issues.redhat.com/browse/HAC-2908
During import, if the runtime is changed, the advanced options disappear entirely while the CDQ is running. Furthermore the expanded advanced settings which were expanded prior to selecting a new runtime return collapsed after the CDQ completes.
Now showing the deploy configuration options all the time with default values and fixed the content jumping caused due to conditional rendering of spinner.
**Before:**
**After:**
```
ReviewComponentCard
✓ should not hide expandable config when components are not detected (76 ms)
```
Change the runtime in the component review step.
=> Fix disappearing advanced options when switching runtime

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
https://issues.redhat.com/browse/HAC-2918
Adds component reference to the pipeline run details page.
=> add component reference to pipeline run details

src/components/ApplicationDetails/tabs/overview/sections/__data__/WorkflowSnapshotsEnvironmentBindingsData.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts, src/consts/pipelinerun.ts, src/hacbs/components/Environment/__data__/mockAppEnvWithHealthStatus.ts, src/hacbs/components/Environment/__tests__/EnvironmentCard.spec.tsx, src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx, src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts, src/hooks/useSnapshots.ts, src/types/coreBuildService.ts, src/types/pipeline-run.ts, src/utils/__tests__/environment-utils.spec.ts, src/utils/environment-utils.ts
https://issues.redhat.com/browse/HAC-2935
https://issues.redhat.com/browse/HAC-2978
Environment Card, lifecycle and commit visualization always showing Application Missing/Pending status.
**RCA:** 
Snapshot fetching logic was based on the integration test pipelineruns, since we will not use any integration tests for mvp, the snapshot + environment map was always resulting in "Application Missing" state as there are not test pipelineruns.
**Solution**:
Removed the logic for fetching the snapshot from the test pipelineruns, and now we have the commit labels available in the snapshot, so directly use commit label to query the latest snapshot (for commit Visualization) and for lifecycle, environment cards we are now relying on SEB's `componentDeploymentConditions` to determine the overall …
=> Fix environment status in env list view and graph nodes

config/remotePlugin.js, src/components/Activity/ActivityTab.tsx, src/components/Activity/__tests__/ActivityTab.spec.tsx, src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts, src/components/Commits/CommitsListView.tsx, src/components/Commits/__tests__/CommitsListView.spec.tsx, src/components/ComponentSettingsForm/ComponentSettingsForm.tsx, src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/WorkspaceSettings/WorkspaceSettings.tsx, src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx, src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
Fixes [HAC-2994](https://issues.redhat.com/browse/HAC-2994)
Fixes [HAC-2995](https://issues.redhat.com/browse/HAC-2995)
Fixes [HAC-3013](https://issues.redhat.com/browse/HAC-3013)
Fixes [HAC-3026](https://issues.redhat.com/browse/HAC-3026)
Fixes navigation to items moved into the Activity page tabs.
Updates the activity page to use the URL for active tab path rather than state.
Update workspace settings page to use URL path rather than search params for active tab
=> Fix navigation for activity page tab items

package.json
Speed up our PR check by skipping unit tests during the build of an image in the PR check job.
[issue](https://issues.redhat.com/browse/HAC-3038)
=> Speed up PR check job

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
https://issues.redhat.com/browse/HAC-2951
There's no way to navigate back to the commit details page after clicking on a pipeline run from the commit details page.
visit pac pipeline run details page, it should have link to commit details page.
```
PipelineRunDetailsTab
✓ should not render the commit link for simple pipelinerun (19 ms)
✓ should render the commit link for pac pipelinerun (23 ms)
```
cc: @christianvogt @MariaLeonova
=> add commit link in pipeline run details page

src/components/ApplicationDetails/DetailsPage.tsx, src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx, src/components/ImportForm/ApplicationSection/ApplicationSection.tsx, src/components/ImportForm/ReviewSection/ReviewSection.tsx, src/components/ImportForm/SampleSection/SampleSection.tsx, src/components/ImportForm/SourceSection/SourceSection.tsx, src/pages/ApplicationsPage.tsx, src/pages/ComponentSettingsPage.tsx
https://issues.redhat.com/browse/HAC-3057
Removes `Stonesoup` from browser titles and replaces the string with `CI/CD`
=> replace Stonesoup with CI/CD for now in browser titles

src/shared/components/pipeline-run-logs/StatusIcon.scss, src/shared/components/pipeline-run-logs/StatusIcon.tsx
https://issues.redhat.com/browse/HAC-3040
Pipelinerun running icons uses different speeds in different spots. This PR makes the running icon speed consistent in all the places.
https://user-images.githubusercontent.com/9964343/215699780-7879ae31-faa5-46f5-b471-5de279ff8b74.mov
=> running icon speed should be consistent

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/RunResultsList.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/RunResultsList.spec.tsx, src/utils/__tests__/render-utils.spec.tsx, src/utils/render-utils.tsx
TBD
Displays a table of the key value pair of results for the pipeline run on the details page.
If a URL is present in the data, it is converted to a link.
For the most part, the code was taken from the developer console.
When results are present, a new table is shown at the bottom of the page:
=> add plr results to details page

src/components/ImportForm/utils/__tests__/transform-utils.spec.ts, src/components/ImportForm/utils/submit-utils.ts, src/components/ImportForm/utils/transform-utils.ts
Fixes [HAC-3024](https://issues.redhat.com/browse/HAC-3024)
When creating sample components, use the suggested name returned by CDQ rather than prepending the application name and adding the `-sample` suffix.
=> Use sample component names as retrieved from CDQ

src/shared/components/action-menu/ActionMenuToggle.tsx
Fixes [HAC-3072](https://issues.redhat.com/browse/HAC-3072)
Action menu click was not propagating the event so other action menus did not close. Change to propagate the event, but delay the menu open so that it doesn't automatically close when catching the click event.
=> Fix to hide action menus when bringing up another

src/__data__/pod-data.ts, src/shared/components/pipeline-run-logs/PipelineRunLogs.scss, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx, src/shared/components/pipeline-run-logs/logs/Logs.tsx, src/shared/components/pipeline-run-logs/logs/LogsWrapperComponent.tsx, src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx, src/shared/components/pipeline-run-logs/logs/log-utils.spec.ts, src/shared/components/pipeline-run-logs/logs/logs-utils.ts
https://issues.redhat.com/browse/HAC-2808
https://issues.redhat.com/browse/HAC-3025
https://issues.redhat.com/browse/HAC-3071
UI doesn't tell user when the selected log isn't available any more. Due to the pod limit, the pruner will start to remove the old pods in order to create new pods, so the user will not be able to view the logs for the pods that are pruned already.
This PR fixes few issues around the build logs:
1. Display the message in the UI to notify that the logs are no longer available for the <selected_task>.
2. Display the pending state message if the task is not started yet.
3. Clicking on the build log should show the last completed task logs.
Note: Pods limit are now increased to 150 (130 for taskruns , 20 for deployments), so the pruner will kick in when the pods count …
=> fix build logs loading, alignment and pending state messages

integration-tests/support/pages/CreateApplicationPage.ts, src/components/ImportForm/ApplicationSection/ApplicationSection.tsx, src/components/ImportForm/ApplicationSection/__tests__/ApplicationSection.spec.tsx, src/components/ImportForm/utils/__tests__/useValidApplicationName.spec.ts, src/components/ImportForm/utils/__tests__/validation-utils.spec.ts, src/components/ImportForm/utils/useValidApplicationName.ts, src/components/ImportForm/utils/validation-utils.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/HAC-2353
https://issues.redhat.com/browse/HAC-3048
- Use CR name for field instead of displayName
- Change field label to "Name"
- Change placeholder to "my-first-app" and increment suffix if name is already used
- Show Inline errors for incorrect name format
- Use RFC compliant regex for resource name fields
https://user-images.githubusercontent.com/20013884/216340465-687b8791-050d-4a68-889a-e281a33c618c.mp4
Create applications from import form.
=> Follow CR name requirements for application input field

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
https://issues.redhat.com/browse/HAC-3102
Components settings form has broken responsive layout for component cpu and memory settings.
Before:
After:
https://user-images.githubusercontent.com/9964343/216927595-7a503e23-ea3b-4dd7-ba39-3fe6c14eb1de.mov
=> make component settings form responsive

integration-tests/support/pageObjects/createApplication-po.ts, integration-tests/support/pages/ApplicationDetailPage.ts, integration-tests/tests/create-application-from-public-git-source.spec.ts
https://issues.redhat.com/browse/HAC-3063
Add meaningful test for the build log modal.
It used to check just that the modal was opened. Now it also checks that the task has run and shows the expected output.
=> Enhance test for build log

src/components/ApplicationDetails/tabs/overview/visualization/nodes/CommitWorkflowNode.tsx, src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.scss, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.scss, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.tsx
https://issues.redhat.com/browse/HAC-3126
On hovering over the pipeline run/commit nodes, the cursor pointer is applied but there isn't any interaction on the node yet.
We have a story to address the pipeline run and commit node interactions in the backlog, so removing the cursor pointer style until we implement the interactions.
[slack thread](https://redhat-internal.slack.com/archives/C038DJAP7HR/p1675862260167559?thread_ts=1675806083.101539&cid=C038DJAP7HR) 
https://user-images.githubusercontent.com/9964343/217618070-b9495c8c-c5cb-4667-b672-410c294ff3e6.mp4
https://user-images.githubusercontent.com/9964343/217618052-eb222faf-39b5-4882-b9d8-fc998dd3e77d.mp4
=> fix cursor style while hovering on pipelinerun and commit node

config/remotePlugin.js, src/components/ApplicationDetails/ApplicationDetails.tsx, src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx, src/components/Commits/CommitDetailsView.tsx, src/components/Commits/__tests__/CommitDetailsView.spec.tsx, src/components/EmptyState/EmptyState.scss, src/components/EmptyState/ErrorEmptyState.tsx, src/components/EmptyState/__tests__/ErrorEmptyState.spec.tsx, src/components/IntegrationTest/IntegrationTestDetailsView.tsx, src/components/IntegrationTest/__tests__/IntegrationTestDetailsView.spec.tsx, src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/pages/EditIntegrationTestPage.tsx, src/pages/NotFoundPage.tsx, src/pages/__tests__/EditIntegrationTestPage.spec.tsx
Fixes [HAC-3050](https://issues.redhat.com/browse/HAC-3050)
Handle errors at top level pages and display an error state if an error is returned while loading the data.
Created an ErrorState component that handles showing errors consistently, and generically handles 404 errors.
/cc @MariaLeonova
=> Fix to show error state rather than spinner

src/components/Commits/CommitsListView.tsx, src/components/Components/ComponentListView.tsx, src/components/Environment/EnvironmentListView.tsx, src/components/ImportForm/SampleSection/SampleSection.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/TaskRunListView/TaskRunListView.tsx
https://issues.redhat.com/browse/HAC-3097
Adds the clear button to all search input instances.
before:
after:
=> add clear button to search inputs

src/components/ImportForm/ImportForm.scss, src/components/ImportForm/ImportForm.tsx, src/components/ImportForm/SampleSection/SampleSection.tsx
https://issues.redhat.com/browse/HAC-3098
Update styles to make the wizard content extend to the bottom so that the grey background of the samples isn't cut short.
before:
after:
- create a new component from samples
=> extend samples background to bottom of wizard

src/components/ImportForm/SampleSection/SampleSection.tsx
https://issues.redhat.com/browse/HAC-3125
Show the full description content of the sample in the card instead of a single line which cuts the description short.
before:
after:
- add a component
- choose to start from a sample
=> show full description of samples

src/components/ApplicationDetails/ApplicationDetails.tsx, src/components/ApplicationListView/ApplicationListRow.tsx, src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx, src/components/modal/resource-modals.tsx
https://issues.redhat.com/browse/HAC-3135
Fallback to application `metadata.name` when `spec.displayName` does not exist or is an empty string.
Create a new application.
Edit the application yaml and delete the `spec.displayName` or set to an empty string.
=> fallback to app metadata.name when displayName is empty

src/components/Components/ComponentListItem.tsx, src/components/Components/__tests__/ComponentListItem.spec.tsx
https://issues.redhat.com/browse/HAC-2866
Add clipboard copy feature to build container image field in component list. 
Note:
Container image link that we show today redirects to a 403 page and it isn't useful.[ Slack thread](https://redhat-internal.slack.com/archives/C038DJAP7HR/p1675805885081549?thread_ts=1673452387.689769&cid=C038DJAP7HR)
```
ComponentListItem
✓ should not render Built container image if the containerImage is missing in component status (13 ms)
✓ should render Built container image if the component status contains the containerImage field (17 ms)
```
=> Add clipboard copy to built container image field

src/components/ApplicationDetails/component-actions.tsx, src/components/Components/ComponentPACStateLabel.tsx, src/components/CustomizedPipeline/CustomizeAllPipelines.tsx, src/components/CustomizedPipeline/CustomizeComponentPipeline.tsx, src/components/CustomizedPipeline/CustomizePipelines.tsx, src/components/CustomizedPipeline/CustomizePipelinesModal.tsx, src/components/CustomizedPipeline/__tests__/CustomizeComponentPipeline.spec.tsx
https://issues.redhat.com/browse/HAC-3140
When the customize pipeline modal is opened for a single component using the kebab menu item of a row in the component list view, the state of the component is not updated as the state changes.
The reason this happens is because the component instance passed to the modal is stale.
Reworked the logic to pass 
No change in visuals
- Create a component with default build
- from the components tab, select `customize build pipeline` from the component row kebab
- Click on `send pull request`
- observe the state never updates before this change
- after this change the state should update as the user goes through the flow
=> fix customize pipeline modal for single component

src/hooks/useApplicationHealthStatus.ts, src/utils/__tests__/environment-utils.spec.ts, src/utils/environment-utils.ts
- https://issues.redhat.com/browse/HAC-3144
- Update `useApplicationHealth` hook to only use status from `SnapshotEnvironmentBinding`.
=> Update application health status to only use SEB

integration-tests/support/pageObjects/global-po.ts, integration-tests/utils/Login.ts, src/components/Overview/AboutSection.tsx, src/components/Overview/InfoBanner.tsx, src/components/Overview/IntroBanner.scss, src/components/Overview/IntroBanner.tsx, src/components/Overview/__tests__/IntroBanner.spec.tsx
https://issues.redhat.com/browse/HAC-3128
https://issues.redhat.com/browse/HAC-3130
Makes overview page responsive.
Changes the `+ Create an application` action to go to the import wizard instead of the application list view.
Add action `View my applications` to go to the application list view. This action will only appear if the user has at least one application.
Visit the overview page with 0 or more applications.
=> update overview page layout and actions

integration-tests/tests/create-application-from-public-git-source.spec.ts
seems to fail on occasion just before the logs load
=> increase timeout for build log test

src/components/Environment/EditStrategyModal.tsx, src/components/ImportForm/SourceSection/AuthTokenModal.tsx, src/components/ImportForm/SourceSection/__tests__/AuthTokenModal.spec.tsx, src/components/modal/DeleteResourceModal.tsx
https://issues.redhat.com/browse/HAC-3029
This issue only presents itself in production because the error is due to CORS.
If the network request to SPI fails, the UI was setting the error object into the state. We then try to render the error object which causes react to blow up. The solution is to extract the error message and set a string to the error state.
No change.
- go to create a component
- enter any git url that's unreachable
- manually enter a token
- press connect
You will need to force an error to occur in the network request to SPI in order to reproduce this.
=> fix crash when import a private Git Repository

src/components/Environment/EnvironmentListView.tsx, src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
https://issues.redhat.com/browse/HAC-3141
Environment list view should list the environments in order based on the selected parentEnvironment.
**Before:**
**After:**
Create a list of environment in the order using spec.parentEnvironment fields or via UI by adding ?mvp=false flag in environment page.
```
EnvironmentListView
✓ should render environment(s) in order based on parentEnvironments (40 ms)
```
=> Add environment order in list view

src/components/ApplicationListView/ApplicationListRow.tsx, src/hooks/__data__/mock-data.ts, src/hooks/__tests__/useAllApplicationEnvironmentsWithHealthstatus.spec.ts, src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts, src/types/coreBuildService.ts
https://issues.redhat.com/browse/HAC-3202
Environment page is breaking when the component creation fails with Gitops error then the SnapshotEnvironmentBinding's status is missing `ComponentDeploymentConditions` field. 
Note:
This is not happening in staging, development clusters. This issue was noticed when deploying frontend + backend components in quicklab clusters.
This issue was noticed when deploying frontend + backend components in quicklab clusters.
https://github.com/ch007m/my-stonesoup/blob/main/howto-play.md#install-the-frontend
```
useAllApplicationEnvironmentsWithHealthStatus
✓ should return empty array if some resources are not loaded (12 ms)
✓ should return default status for managed environment (3 ms)
✓ should return Missing status (2 ms)
✓ should return Progressing status …
```
=> Fix environment UI crashing issue

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
https://issues.redhat.com/browse/HAC-3203
Create button is not enabled again after switching the runtime from Other to Basic Quarkus when context directory is set in the first step.
https://user-images.githubusercontent.com/9964343/220329109-9eb71a6f-e0e8-4b1e-82d5-f718fe133e7a.mov
1. use https://github.com/RedHat-EMEA-SSA-Team/end-to-end-developer-workshop repo while creating components and set the context directory to `/labs`.
2. Switch the detected runtime of a component from `Other` to  `Basic Quarkus` component.
```
RuntimeSelector
✓ should set the context directory when the provided repo is matching with sample runtime repo (59 ms)
✓ should not set the context directory when the runtime is changed (48 ms)
```
cc: @rohitkrai03
=> context directory should not be passed when runtime is changed

src/components/modal/DeleteResourceModal.tsx, src/components/modal/__tests__/DeleteResourceModal.spec.tsx, src/shared/components/formik-fields/field-types.ts
https://issues.redhat.com/browse/HAC-2744
Automatically focus on name input field in delete modal
https://user-images.githubusercontent.com/20013884/219417639-b121b28c-5329-4096-aedd-3a32bbfff96d.mp4
Delete a component or application.
=> Autofocus on name input field in delete modal

config/remotePlugin.js
https://issues.redhat.com/browse/HAC-3201
Approved users should be able to visit to workspace page, add signup feature flag to protect the route.
cc: @rohitkrai03
=> Guard workspace route with signup feature flag

src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx, src/components/IntegrationTest/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx
https://issues.redhat.com/browse/HAC-2811
After creating an integration test through the UI, if I view its detail page and click on the provided image bundle link, it tries to access that while staying within console and shows me a 404.
Before:
After:
https://user-images.githubusercontent.com/9964343/219626083-e16acd59-833d-42ae-8d7a-9ba2d4af09db.mov
Add an integration test and visit the integration test details page. (use ?mvp=false flag to enable integration tests tab)
=> fix quay image link in integration details page

src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx, src/components/ApplicationListView/__tests__/ApplicationListView.spec.tsx, src/utils/breadcrumb-utils.tsx
https://issues.redhat.com/browse/HAC-3248
Application list view breadcrumb should not contain applications link
```
Application List
✓ should not contain applications breadcrumb link in the list view (25 ms
```   
```
ApplicationDetails
✓ should contain applications breadcrumb link in the list view (841 ms)
```
=> remove applications link from application list view

src/components/ImportForm/SourceSection/SourceSection.tsx
https://issues.redhat.com/browse/HAC-2992
When switching to samples flow we are resetting the `source.git.url` to empty, but the fieldTouched property is not reset causing the validation message to show up when switching back to import from code flow. 
Before:
After:
1. In Add component page, click on the Git url and move to `Start with a Sample` flow
2. Switch back to `Import from your code` flow from samples page.
=> remove validation errors when switching back from samples to import  flow

src/components/Components/BuildStatusColumn.tsx, src/components/Components/ComponentListItem.tsx, src/components/Components/ComponentListView.tsx, src/components/Components/ComponentPACStateLabel.tsx, src/components/Components/__tests__/BuildStatusColumn.spec.tsx, src/components/CustomizedPipeline/CustomizePipelines.tsx, src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx, src/hooks/__tests__/usePACState.spec.ts, src/hooks/usePACState.ts, src/utils/component-utils.ts
https://issues.redhat.com/browse/HAC-3175
A third state `error` has been added. This state is now used whenever we set to `request` but the github app isn't installed. Previously it would remain in the `request` state and therefore the UI would assume that if the transition to `done` doesn't happen within a few seconds, that the github app may not be installed and so we would inform the user to go do so. Once installed the value would transition to `done` and pac would have been configured.
When in the `error` state, inform the user that the github app must be installed. Also provide the user with a means to resend the pull request.
Failed to send pull request:
Component list when the pull request failed to send
- Create a component where the repo doesn't have the github app installed.
- …
=> support pac-provision error state

src/components/Components/BuildStatusColumn.tsx, src/components/Components/__tests__/ComponentListItem.spec.tsx, src/components/Components/__tests__/ComponentListView.spec.tsx, src/hooks/usePipelineRunsForApplication.ts, src/shared/components/pipeline-run-logs/utils.ts
Fixes [HAC-2344](https://issues.redhat.com/browse/HAC-2344)
When the Pipelinerun has not been started yet, display the component status as `Build Starting`
/cc @karthikjeeyar @christianvogt
=> Show `Build starting` for component status when pipeline run does not exist

src/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.scss, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.tsx, src/components/PipelineRunDetailsView/visualization/types.ts, src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts, src/components/topology/__data__/pipeline-test-data.ts
Fixes [HAC-3200](https://issues.redhat.com/browse/HAC-3200)
Determines the test status for pipeline run tasks and if the task run is successful, show any test status to indicate the test status issues.
=> Show task run test output status on task run nodes

src/components/ImportForm/SourceSection/SourceSection.tsx, src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx, src/components/ImportForm/utils/types.ts, src/components/ImportForm/utils/validation-utils.ts
https://issues.redhat.com/browse/HAC-2752
Use the `isValidated` formik state to check and not run SPI access check if repo is already validated.
https://user-images.githubusercontent.com/20013884/220950890-b698cfbd-44de-4b3c-b679-19265bd46857.mp4
Navigate back to git input page after adding valid git repo.
=> Avoid rerunning access check for already authorized repositories

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx, src/shared/components/dropdown/BasicDropdown.tsx, src/shared/components/formik-fields/DropdownField.tsx, src/shared/components/formik-fields/field-types.ts
https://issues.redhat.com/browse/HAC-2909
Replace the runtime detection spinner with disabled dropdown with `Detecting runtime...` message.
**Detecting phase screenshot:**
**Detection full video:**
/cc @christianvogt
=> add `Detecting runtime` message instead of spinner

src/shared/components/formik-fields/EditableLabelField.tsx, src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx, src/shared/components/formik-fields/field-types.ts
Fixes [HAC-2120](https://issues.redhat.com/browse/HAC-2120)
Don't submit form on an enter key press in the editable label field. The edit should be saved but the form should not be submitted.
/cc @karthikjeeyar @christianvogt
=> Do not complete form on editable label enter key

src/shared/components/formik-fields/EditableLabelField.tsx, src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx
https://issues.redhat.com/browse/HAC-3376
Invalid component name error message should be shown if there is any validation error during detection.
**Before:**
**After**:
Try to import the repository: https://github.com/hacbs-release/fbc-test
cc: @rottencandy
=> show validation error message when invalid component name is detected

pr_check.sh
The bonfire namespace is not released after the tests.
The bonfire release command without the `-f` flag was waiting for the confirmation and so the namespace was not released after the test run but after the timeout.
Should be done as part of [HAC-3491](https://issues.redhat.com/browse/HAC-3491)
=> Force release the namespace.

src/utils/pipeline-utils.ts
Fix for showing correct pipeline status. Do not propagate task run status up to pipeline run status (introduced in https://github.com/openshift/hac-dev/pull/468).
https://github.com/openshift/hac-dev/pull/468 mistakenly propagated the task run status up to the overall pipeline run status. Remove this propagation.
Before:
After:
View a successful pipeline run that has HACBS_TEST_OUTPUT failures in task runs.
/cc @karthikjeeyar @rohitkrai03
=> Do not propagate task status up to pipeline run

integration-tests/support/pageObjects/createApplication-po.ts, integration-tests/support/pages/ApplicationDetailPage.ts, integration-tests/tests/basic-happy-path.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppComponentsNodes.ts
Fixes [HAC-2915](https://issues.redhat.com/browse/HAC-2915)
Removes status indicator for component nodes in the overview lifecycle visualization
/cc @karthikjeeyar @christianvogt
=> Remove status from component node of lifecycle vis

src/components/NamespacedPage/NamespacedPage.scss, src/components/NamespacedPage/NamespacedPage.tsx, src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/PipelineRunSidePanel.tsx, src/components/PipelineRunDetailsView/PipelineRunVisualization.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunSidePanel.spec.tsx, src/components/PipelineRunDetailsView/sidepanels/TaskRunDetails.tsx, src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.scss, src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.tsx, src/components/PipelineRunDetailsView/tabs/RunResultsList.scss, src/components/PipelineRunDetailsView/tabs/RunResultsList.tsx, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.scss, src/components/PipelineRunDetailsView/visualization/nodes/PipelineRunNode.tsx, src/components/PipelineRunDetailsView/visualization/types.ts, src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts, src/components/SidePanel/SidePanel.tsx, src/components/SidePanel/SidePanelContext.ts, src/components/SidePanel/SidePanelHost.tsx, src/components/SidePanel/__tests__/SidePanel.spec.tsx, src/components/SidePanel/__tests__/SidePanelHost.spec.tsx, src/components/TaskRuns/TaskRunLogs.tsx, src/components/TaskRuns/__tests__/TaskRunLogs.spec.tsx, src/components/topology/factories/VisualizationFactory.tsx, src/types/task-run.ts
https://issues.redhat.com/browse/HAC-3357
Adds click interaction for task run nodes of the pipeline run visualization.
Opens a sidepanel with extra information.
The side panel is configured as `inline` which will push the content. The reason for doing this is because it allows us to navigate the visualization and gain access to the right most nodes without having to first close the panel.
When a node is clicked, we scroll it into view to ensure the task node is visible when the panel opens.
Some tasks aren't very interesting, such as skipped tasks. Skipped tasks have no start time or duration or logs.
Known issues:
~~There is a layout issue with consoledot that prevents me from defining two distinct scroll areas: one for the panel and one for the adjacent content. Because of this the …
=> add sidepanel for task run nodes of pipeline run visualization

src/components/ApplicationDetails/DetailsPage.scss, src/components/ApplicationDetails/DetailsPage.tsx
https://github.com/openshift/hac-dev/pull/465 changed the page layout to work around a consoledot issue but this resulted in the details page for the activity pipelinerun tab not extending the full length
before:
after:
Navigate to application -> activity tab -> pipeline runs tab
=> fix details page layout with flex

src/components/LogViewer/BuildLogViewer.tsx, src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/PipelineRunVisualization.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunTaskRunsTab.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunTaskRunsTab.spec.tsx, src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts, src/components/TaskRunListView/TaskRunListView.tsx, src/components/TaskRunListView/__tests__/TaskRunListView.spec.tsx, src/hooks/useTaskRuns.ts, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx, src/shared/components/pipeline-run-logs/logs/pipelineRunLogSnippet.ts
https://issues.redhat.com/browse/HAC-3352
when embedded-status configuration is set to minimal, which will remove the `status.taskruns` from the `pipelineruns.status`. This PR fetches the taskruns separately instead of reading from `pipelinerun.status.taskruns`
No UI changes
Pipelinerun/Taskrun/logs should work as before.
https://user-images.githubusercontent.com/9964343/224714069-4579d68b-ffdd-44e8-a1e9-2dda642866d1.mov
=> Support tekton minimal status configuration

src/components/Commits/CommitsListView.tsx, src/components/Components/ComponentListView.tsx, src/components/Environment/EnvironmentListView.tsx, src/components/ImportForm/SampleSection/SampleSection.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/TaskRunListView/TaskRunListView.tsx
Fixes an issue where the search input on the toolbars shows two clear buttons (`x`).
PF latest adds a clear button on a SearchInput when `onClear` is set. Remove the `onClear` setting and rely on the toolbar clear button for clearing the text.
/cc @karthikjeeyar
=> Fix for SearchInput used in toolbar

src/components/PipelineRunDetailsView/PipelineRunSidePanel.tsx, src/components/PipelineRunDetailsView/PipelineRunVisualization.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunSidePanel.spec.tsx, src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
https://github.com/openshift/hac-dev/pull/465#issuecomment-1469904086
`scrollIntoView` acts funny for Firefox. It doesn't seem to take into consideration the width of the SVG node.
Implemented a custom solution just for Firefox :(
Select task nodes in the pipeline run visualization that is not fully visible when the side panel is open.
=> workaround svg scrollIntoView for Firefox

src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.scss, src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.tsx, src/components/PipelineRunDetailsView/sidepanels/__tests__/TaskRunDetails.spec.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/hooks/useComponents.ts, src/utils/component-utils.ts
https://issues.redhat.com/browse/HAC-3180
https://issues.redhat.com/browse/HAC-3320
Added a `Start new build` action to the pipeline run details page.
This action is only visible for default build components. Even if the pipeline run was previously run from a default pipeline component which was then later updated, the action would not be available. Similarly if the pipeline run was from PAC but later the component was returned to a default pipeline, the action will be available.
After starting the action, the user is brought to the pipeline run list page with a filter set to the related component name.
landing page after execution:
Visit a pipeline run details page.
Ensure the related component is a sample or default build.
Click the actions dropdown menu and select `Start new build`
=> Start new build action from pipeline run details page

src/components/ApplicationDetails/ApplicationHeader.tsx, src/utils/__tests__/route-utils.spec.ts, src/utils/route-utils.ts
- https://issues.redhat.com/browse/HAC-3420
- The application header was only considering first component to show the route.
- Updated that logic to find first component that has a route.
https://user-images.githubusercontent.com/6041994/225864866-dd6ff8d6-efaa-41fc-9639-bf2062b15406.mov
=> Fix route URL not showing up if first component doesn't have route

src/components/ImportForm/ReviewSection/ReviewSection.tsx, src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
https://issues.redhat.com/browse/HAC-3120
Handle errors returned by CDQ in the event of service or network errors.
Ensures that the wizard can advance to the review section if cdq errors out.
no visible change other than user is advanced to next page in the event of an error.
Will need to reproduce network errors during import to cause CDQ to fail.
=> handle cdq errors in import wizard

src/components/IntegrationTest/__tests__/IntegrationTestDetailsView.spec.tsx, src/hooks/useIntegrationTestScenarios.ts
https://issues.redhat.com/browse/HAC-3538
When there are multiple integration test scenarios, clicking on the second test takes the user to the correct route but shows the data from first integration test in the application.
Before:
https://user-images.githubusercontent.com/9964343/226851889-10cdabc9-5a76-4789-b078-aa0e342caf3c.mp4
After:
https://user-images.githubusercontent.com/9964343/226850485-228eab75-961e-44f7-807e-c5827e3f712f.mp4
1. Add multiple integration tests
2. Clicking on an integration test should load the details page with that integration test data.
=> Show Integration details page based on integration test name

src/hooks/__tests__/useTaskRuns.spec.ts, src/hooks/useTaskRuns.ts, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx
https://issues.redhat.com/browse/HAC-3557
When viewing logs of a Pipelinerun, the ordering of the tasks constantly changes on clicking a task.
**Before:**
https://user-images.githubusercontent.com/9964343/227000748-dcbc81ae-3b45-4082-8d32-15c6be064c3d.mp4
**After:**
https://user-images.githubusercontent.com/9964343/227000790-35da1ec6-a763-4bdb-a146-26a9a6c3417b.mp4
```
PipelineRunLogs.spec.tsx
✓ should render the task names in the same order when a task is clicked (75 ms)
```
/cc @jeff-phillips-18
=> Tasks order should be consistent when user selects a task in plr logs

src/components/ApplicationDetails/DetailsPage.tsx, src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx, src/shared/components/action-menu/ActionMenuItem.tsx, src/shared/components/action-menu/__tests__/ActionMenuItem.spec.tsx
https://issues.redhat.com/browse/HAC-3612
When a user doesn't have a enough permission to perform an action, then the button is disabled but the user is still able to click on the button and it redirects to the underlying link.
This PR also fixes the colour scheme for kebab menu actions.
Link redirection:
**Before:**
**After:**
Kebab menu action color Schemes:
|  **Before** | **After**
|---|---|
|  <img width="298" alt="Screenshot 2023-03-29 at 10 08 22 AM" src="https://user-images.githubusercontent.com/9964343/228442341-23e139c0-14bf-41bb-af71-0e24d1839a2a.png">| <img width="335" alt="Screenshot 2023-03-29 at 11 44 38 AM" src="https://user-images.githubusercontent.com/9964343/228442789-8abf0854-cea5-485c-8fa4-cfbf44aab2fc.png"> |
/cc @rottencandy
=> Prevent link redirection in disabled action button 

helpers/resources/release/managed-workspace/ec-policy.yaml, src/components/EnterpriseContractView/__data__/mockECPolicy.ts, src/components/EnterpriseContractView/__data__/mockEnterpriseContractPolicies.ts, src/components/EnterpriseContractView/const.ts
https://issues.redhat.com/browse/HACBS-2004
The hacbs-contract GitHub organization has been renamed to `enterprise-contract`. This change updates references to the new name as to not rely on the redirect put in place automatically by GitHub.
=> Update references to the new EC GitHub org name

Caddyfile
https://issues.redhat.com/browse/HAC-3609
HCC is moving away from beta environment to preview environment in order to do that we need to have preview prefix strip when user requests hac-dev files.
=> Add preview to caddy uristip and chrome redirect

src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx, src/components/PipelineRunListView/pipelinerun-actions.tsx
https://issues.redhat.com/browse/HAC-3617
With the addition of access checks to disable actions, in some cases we now show the access check tooltip even though the action is disabled because the pipeline run is not running.
The permissions related tooltip should only be shown when the action is disabled due to permissions.
Create a pipeline run.
Go to the details page or list page and open the kebab menu.
If the pipeline run has completed, the actions should be disabled without showing a tooltip about permissions.
=> don't show access tooltip when disabled for other reasons

src/components/HelpTopicLink/HelpTopicLink.tsx, src/components/HelpTopicLink/__tests__/HelpTopicLink.spec.tsx
https://issues.redhat.com/browse/HAC-3646
There are 4 what's next learn more help topics, but only a single one at a time would be displayed in drop down menu.
Fixed this and now all 4 are displayed at once.
=> enable all what's next help topics at once

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
https://issues.redhat.com/browse/HAC-3614
Use a default image when runtime is not detected.
Add a repository with an undetectable runtime.
=> Use default image when runtime is not detected

src/components/Commits/CommitDetailsView.tsx, src/components/Commits/CommitsListHeader.tsx, src/components/Commits/CommitsListRow.tsx, src/shared/components/commit-label/CommitLabel.tsx, src/shared/components/commit-label/__tests__/CommitLabel.spec.tsx
Fixes [HAC-3579](https://issues.redhat.com/browse/HAC-3579)
Adds a component `CommitLabel` to be used for displaying commit IDs.
/cc @karthikjeeyar @christianvogt
=> Add CommitLabel for displaying Commit IDs

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx, src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx, src/components/ImportForm/utils/__tests__/transform-utils.spec.ts, src/components/ImportForm/utils/transform-utils.ts, src/components/ImportForm/utils/types.ts, src/shared/components/formik-fields/EditableLabelField.tsx, src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx
https://issues.redhat.com/browse/HAC-3585
If the user has provided a component name, then it should not be updated when a runtime is changed.
https://user-images.githubusercontent.com/9964343/229850506-19e7ed42-d994-401c-adf3-326aee724e5e.mov
1. In the review step, change the component name
2. choose a different runtime
=> User provided component name should not be overridden by cdq defaults

src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx, src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
No Jira filed currently.
There were some changes to the Enterprise Contract task definition and now the step containing the Enterprise Contract output in YAML format is called "report" instead of "validate".
See the task definition change here:
https://github.com/enterprise-contract/ec-cli/pull/589
This is related to the recently merged #530 .
- Bugfix
I believe the newly merged code from #530 won't be working as expected in RHTAP stage and prod due to the recent step name change.
I'm not sure how to test this, or whether there are other changes required. Feel free to advise if there's something else needed. Attention @christianvogt @sahil143 .
=> Update task name for scraping EC report output

src/components/ImportForm/SampleSection/SampleSection.tsx
https://issues.redhat.com/browse/HAC-3099
If an onclick handler is provided to CatalogTile, it uses an `a` tag by default. Removing the handler makes it use `div`.
https://user-images.githubusercontent.com/20013884/230939891-a216dfc2-5546-4b46-a37e-68f152f3d9cb.mp4
=> Move sample card onlick handler to galleryitem

src/components/LogViewer/BuildLogViewer.scss, src/components/LogViewer/BuildLogViewer.tsx, src/shared/components/pipeline-run-logs/PipelineRunLogs.scss, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx
Fixes [HAC-2966](https://issues.redhat.com/browse/HAC-2966)
Sets the task run list to be scrollable rather than the entire build logs modal. Scroll the active item into view if it is not.
/cc @rohitkrai03 @karthikjeeyar
=> Set scrollbar on tasks list in build logs modal

src/shared/components/pipeline-run-logs/__tests__/Logs.spec.tsx, src/shared/components/pipeline-run-logs/__tests__/MultiStreamLogs.spec.tsx, src/shared/components/pipeline-run-logs/logs/Logs.tsx, src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx
https://issues.redhat.com/browse/RHTAPBUGS-107
Autoscrolling is not working for larger logs data stream (eg: build-container task).
**Root Cause Analysis**
The performance bottleneck is caused when a large dataset is streamed, the `scrollIntoView` method is being called multiple times continuously which blocks the javascript thread and the browser becomes unresponsive.
**Solution:**
Throttling `scrollIntoView` method and made the function call asynchronous by wrapping in setTimeout function.
**Before:**
https://user-images.githubusercontent.com/9964343/231555950-cc55a47f-3bff-484a-9731-3e6104363c22.mov
**After:**
https://user-images.githubusercontent.com/9964343/231555969-92527e72-00a0-4415-8844-906c545916d5.mov
1. Add a quarkus or spring boot application from samples.
2. view build logs …
=> fix build logs autoscroll performance issue

src/components/NamespacedPage/NamespacedPage.tsx, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx
https://issues.redhat.com/browse/RHTAPBUGS-126
Page crash happens when pipelinerun.status is not available.
This results in another error when the modal tries to update itself but the modal provider is removed from the tree.
- Add null check for status.taskRuns of pipelinerun when displaying logs modal.
- Move error boundary up the tree to cover modal provider.
https://user-images.githubusercontent.com/20013884/233167332-85f41be2-0bf6-4250-8948-faf40b1e28c4.mp4
=> Check taskrun status when displaying logs

src/components/Environment/create/CreateEnvironment.tsx, src/components/Environment/create/CreateEnvironmentForm.tsx, src/components/Environment/create/IngressDomainField.tsx, src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx, src/components/Environment/environment-utils.ts, src/components/ImportForm/utils/validation-utils.ts
Fixes [HAC-3786](https://issues.redhat.com/browse/HAC-3786)
Adds an `Ingress domain` input when creating a non-OpenShift cluster environment.
/cc @rohitkrai03 @karthikjeeyar
=> Add ingressDomain for env create of non-OpenShift

src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
https://issues.redhat.com/browse/HAC-3760
change the width of message column
**Before**
**After**
=> change width for message and component column for enterprise contract table

src/components/Activity/ActivityTab.tsx, src/components/Activity/__tests__/ActivityTab.spec.tsx, src/components/ApplicationDetails/ApplicationDetails.tsx, src/components/ApplicationDetails/DetailsPage.tsx, src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx, src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx, src/hooks/useLocalStorage.ts
https://issues.redhat.com/browse/RHTAPBUGS-161
I often want to visit the pipeline runs within the activity tab. However every time I visit the activity tab, it displays the commits sub tab by default. It would be useful if clicking the activity tab brought the user back to the previously viewed sub tab.
https://user-images.githubusercontent.com/9964343/233547956-9f0d7509-54be-4027-8ccf-638628ea443b.mov
1. Select Activity tab, and select pipelineruns tab 
2. Go to any other tab and return back to activity tab, the pipelineruns tab should be pre selected
=> return users to last used sub tab on activity tab selection

src/components/PipelineRunDetailsView/tabs/ScanDescriptionListGroup.tsx
Fixes [RHTAPBUGS-210](https://issues.redhat.com/browse/RHTAPBUGS-210)
Hide the `View logs` link when there are no vulnerabilities
=> Hide logs link when there are no vulnerabilities

src/components/Components/ComponentListItem.tsx, src/components/ImportForm/utils/__tests__/transform-utils.spec.ts, src/components/ImportForm/utils/submit-utils.ts, src/components/ImportForm/utils/transform-utils.ts
Addresses [RHTAPBUGS-12](https://issues.redhat.com/browse/RHTAPBUGS-12)
Fixes the UI side for setting and showing instances that are scaled to zero. However, the backend is clearing the replicas field when it is set to zero so the UI will still not show the scaling to zero.
/cc @karthikjeeyar @rohitkrai03
=> Allow component instances to be scaled to 0

src/components/Environment/EnvironmentCard.tsx, src/components/Environment/EnvironmentList.scss, src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx, src/components/Environment/environment-utils.ts, src/components/ImportForm/utils/__tests__/validation-utils.spec.ts, src/components/ImportForm/utils/validation-utils.ts, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx, src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts
Fixes [RHTAPBUGS-215](https://issues.redhat.com/browse/RHTAPBUGS-215)
Limits user entry of resource names to 64 characters. Also fixes a text overflow issue for environment cards when the environment name is very long (env names are not restricted in length).
=> Restrict resource name entries to 63 characters

src/components/ImportForm/utils/__tests__/validation-utils.spec.ts, src/components/ImportForm/utils/validation-utils.ts
Fixes [RHTAPBUGS-234](https://issues.redhat.com/browse/RHTAPBUGS-234)
Allows extensions to dockerfile file name when importing a component.
=> Fix docker file path to allow extensions

src/components/PipelineRunDetailsView/tabs/ScanDetailStatus.tsx, src/components/PipelineRunListView/PipelineRunListRow.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/PipelineRunListView/ScanStatus.tsx, src/components/PipelineRunListView/__tests__/ScanStatus.spec.tsx
Fixes [RHTAPBUGS-232](https://issues.redhat.com/browse/RHTAPBUGS-232)
Fixes vulnerabilities column in task run list for the pipeline run details view. Remove text from list row cell. Update view when all task runs have been retrieved to size cells correctly.
=> Fix scan results view in pipeline run task list

src/components/PipelineRunDetailsView/__data__/mockVisualizationData.ts, src/components/PipelineRunDetailsView/tabs/__tests__/ScanDescriptionListGroup.spec.tsx, src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts, src/hooks/__tests__/useScanResults.spec.ts, src/hooks/useScanResults.ts, src/utils/pipeline-utils.ts
Fixes [RHTAPBUGS-230](https://issues.redhat.com/browse/RHTAPBUGS-230)
Include any of the various names for CVE scan results when determining task run results status.
/cc @christianvogt @karthikjeeyar
=> Fix to show CVE_SCAN_RESULT status in nodes

src/components/TaskRunDetailsView/tabs/TaskRunDetailsTab.tsx, src/components/TaskRunDetailsView/tabs/__tests__/TaskRunDetailsTab.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-253
UI crashes when you visit taskrun details page which contains embedded taskspec.
Before:
After:
Add a custom task (with taskspec) in your build pipeline
eg:
```
- name: echo-message
taskSpec:
steps:
- name: echo
image: ubuntu
script: |
#!/usr/bin/env bash
echo "Hello world!"
```
cc: @rohitkrai03
=> fix UI crashing when taskrun contains taskspec

src/components/ImportForm/utils/__tests__/validation-utils.spec.ts, src/components/ImportForm/utils/validation-utils.ts
- https://issues.redhat.com/browse/RHTAPBUGS-252
- Support dockerfile paths with more than one extensions.
=> Support dockerfile path with more than one extension

config/remotePlugin.js
Fixes [RHTAPBUGS-240](https://issues.redhat.com/browse/RHTAPBUGS-240)
Handles the route to environments when no workspace is set. The environments page uses the last used workspace.
=> Add route for environments when no workspace

src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.scss
https://issues.redhat.com/browse/RHTAPBUGS-251
Secrets form lacked spacing between key/value groups and line separating the two.
Added margin to create a gap.
The styling mimics from OpenShift console.
before:
after:
=> add margin between secret key/value form groups

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-235
Ensure download SBOM section is available by looking for the `IMAGE_URL` pipeline run result.
Also adjusted flex layout because the copy sbom input wasn't spanning the full width
Create a component with the default build pipeline.
Create another component with the custom build pipeline.
Go to the PLR details page for the builds related to each component.
=> add sbom download to PLR details

src/components/Activity/ActivityTab.tsx, src/components/Activity/__tests__/ActivityTab.spec.tsx, src/components/ApplicationDetails/ApplicationDetails.tsx, src/components/ApplicationDetails/DetailsPage.tsx, src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-262
- Add support for using partial path keys in details page tabs
- Use partial key for activity tab subitems, and replace with full path if sub path is not available
https://github.com/openshift/hac-dev/assets/20013884/a68a4649-3a76-486a-830e-bf32d9177754
=> Use partial path for activity tab

src/components/ImportForm/GitImportActions.tsx, src/components/ImportForm/__tests__/GitImportActions.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-283
In Add component flow the final submit button should read `Add component`
**Before:**
**After:**
1. Add new component in an application, the final submit button should read `Add component`
cc: @misjohns
=> fix Add component button text

src/components/Overview/AboutSection.tsx, src/components/Overview/IntroBanner.tsx, src/components/Overview/__tests__/AboutSection.spec.tsx, src/components/Overview/__tests__/IntroBanner.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-290
Change all instances of `https://dn.dev/DevNationSlack` to `https://dn.dev/slack`.
Reason for the followup change is because the latter has no expiration date.
Join the wait list to see the top banner.
Visit the overview page at any time to see the updated `Contact us` card.
=> update slack links to https://dn.dev/slack

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-287
Show dockerfile field only when dockerfile runtime is selected
https://github.com/openshift/hac-dev/assets/20013884/b0b74399-30dd-4788-9db7-b1d4143437e9
=> Hide dockerfile field for non-dockerfile runtimes

src/components/modal/DeleteResourceModal.tsx, src/components/modal/__tests__/DeleteResourceModal.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-286
https://issues.redhat.com/browse/RHTAPBUGS-63
- Keep delete modal open and show error if deletion fails
- Avoid showing autocomplete suggestions in resource name field
https://github.com/openshift/hac-dev/assets/20013884/b5444eac-c9ce-4697-ac1b-d5ee785ca000
=> Keep delete modal open if deletion fails

src/components/ImportForm/SampleSection/SampleCard.tsx
Fixes [RHTAPBUGS-275](https://issues.redhat.com/browse/RHTAPBUGS-275)
Sets the correct font size on the sample card icon.
=> Fix for sample icon alt text size

integration-tests/support/pages/ComponentsPage.ts, src/components/ImportForm/ReviewSection/ReviewComponentCard.scss, src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx, src/shared/components/formik-fields/ResourceLimitField.tsx, src/shared/components/name-value-editor/BasicNameValueEditor.scss, src/shared/components/name-value-editor/BasicNameValueEditor.tsx
Fixes [RHTAPBUGS-247](https://issues.redhat.com/browse/RHTAPBUGS-247)
Fixes [RHTAPBUGS-248](https://issues.redhat.com/browse/RHTAPBUGS-248)
Updates layout of the environment name/value pairs at low resolutions to provide more space for entries of name and value.
Updates the layout for the cpu/memory/instances settings at low resolutions to prevent overlap and maintain spacing.
=> Improve responsive layout of import wizard

integration-tests/README.md, integration-tests/entrypoint.sh
https://issues.redhat.com/browse/HAC-4050
make the e2e test container expose the test artifacts at a path that can be easily mounted
=> e2e: make artifacts available from the container

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
https://issues.redhat.com/browse/RHTAPBUGS-243
Make the name and runtime section use vertical flex layout on smaller screens.
https://github.com/openshift/hac-dev/assets/20013884/cfd238c9-3223-42b2-961d-29b5075ffad5
/cc @christianvogt
=> Improve responsiveness of name & runtime fields

src/components/Environment/EnvironmentCard.tsx, src/components/Environment/__tests__/EnvironmentCard.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-274
When an environment is configured for BYOC, the URL provided to the user is incorrect in the deployment card. 
Note: We dont have a way to show the managed environment deployment route at the moment, so we need to hide this url instead of misleading the users.
**Before:**
**After:**
=> Hide application URL in managed environment card

src/components/ImportForm/SourceSection/SourceSection.tsx, src/components/ImportForm/utils/auth-utils.ts
Fixes [RHTAPBUGS-317](https://issues.redhat.com/browse/RHTAPBUGS-317)
When the user changes the git repo name, we need to set the validating flag after the sourceURL is updated in order for it to be validated correctly. Also, remove the created `SPIAccessCheckModel` resource when we no longer need it.
=> Fix for showing git repo status on change

integration-tests/Dockerfile, pr_check.sh
https://issues.redhat.com/browse/HAC-4007
In case a PR makes changes to the dockerfile, run the PR check with the updated image
=> Rebuild e2e runner image when dockerfile changes

src/components/ComponentSettingsForm/ComponentSettingsView.tsx, src/components/ImportForm/GitImportForm.tsx, src/components/ImportForm/SampleImportForm.tsx, src/components/ImportForm/__tests__/SampleImportForm.spec.tsx, src/components/ImportForm/utils/__tests__/submit-utils.spec.ts, src/components/ImportForm/utils/submit-utils.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-316
As workspace owner, I can create all secrets I want from the UI, but as admin in another workspace, I can't do it. This is because of the api call not having workspace context in it.
Before:
After:
1. You have to be an admin in other workspace.
2. Try to create build secrets while adding components in the shared workspace.
=> Fix secrets creation for admins in other workspaces.

src/utils/__tests__/environment-utils.spec.ts, src/utils/environment-utils.tsx
https://issues.redhat.com/browse/RHTAPBUGS-313
Environments list is alphabetically sorted on the first visit, but after deleting any environment before a default type environment (Development) the cards become unsorted.
**Before:**
https://github.com/openshift/hac-dev/assets/9964343/75ded679-d2b2-403f-8aaa-977e4dc53e16
**After:**
https://github.com/openshift/hac-dev/assets/9964343/301c48da-f3cb-4c82-939c-7e483d7bc00c
1.  You need to have multiple self managed environments
2. Delete an environment that is before default environment (Development) environment.
=> Fix environments list view sort order

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
https://issues.redhat.com/browse/RHTAPBUGS-261
we use a PF Docker icon in runtime selector, and that has to match the size of other icons (24px)
Note: Other smaller icons `Node and Go` is fetched dynamically from  https://registry.devfile.io/index/sample and it needs to be fixed from HAS team. cc: @elsony 
Before:
After:
=> fix dockerfile icon size in runtime selector dropdown

src/components/ApplicationDetails/tabs/overview/visualization/const.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppBuildNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppComponentsNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppReleaseNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppReleasePlanNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts, src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts, src/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts, src/components/topology/factories/layoutFactory.ts
Fixes [RHTAPBUGS-157](https://issues.redhat.com/browse/RHTAPBUGS-157)
Update the computations for widths of the app workflow nodes to be more accurate and handle the group nodes when there are no children.
=> Use consistent spacing for app workflow nodes

integration-tests/cypress.config.ts, integration-tests/support/constants/PageTitle.ts, integration-tests/support/pageObjects/pages-po.ts, integration-tests/support/pages/EnvironmentsPage.ts, integration-tests/tests/environments-tests.spec.ts, pr_check.sh
https://issues.redhat.com/browse/HAC-4147
BYOC automation : 
1. Create new Env from environments Nav Tab using the vcluster kubeconfig.
2. Validate the connection is successful and Details on environment cards are correct.
3. Create a new Application and component and wait for successful build.
4. Navigate to deployments Tab of the components and validate the Details on env card are correct and application status is healthy.
5. Delete the application.
6. Delete and validate the new Environment from Environments Nav Tab.
=> e2e: BYOC automation

config/remotePlugin.js, src/utils/__tests__/flag-utils.spec.ts, src/utils/flag-utils.ts
Not able to navigate if signup request fails.
Align the usage of routes, we can gate all routes behind overview if signup returns false.
If signup URL returns error (401 for instance) the navigation is shown, however none of the routes are properly working as we are not setting the signup to false. This can happen if user tries to access the UI on console.stage.redhat.com environment as this environment is not setup with prod SSO.
Since we can utilize `exact: false` when routing we can hide behind disallowed flag default overview page which'll consume all requests.
=> Set signup flag to false if any error

src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListRow.tsx, src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts, src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListRow.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-141
fix https:// append
=> Fix container img url

src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts, src/components/ImportForm/SourceSection/SourceSection.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx, src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx, src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx, src/components/IntegrationTest/IntegrationTestForm/types.ts, src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/validation-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts, src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts, src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListHeader.ts, src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListRow.tsx, src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts, src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListRow.spec.tsx, src/components/IntegrationTest/IntegrationTestsListView/useIntegrationTestActions.tsx, src/components/IntegrationTest/__tests__/IntegrationTestDetailsView.spec.tsx, src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx, src/components/IntegrationTest/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx, src/models/integration-test-scenario.ts, src/types/coreBuildService.ts
This PR is built on top of Abhi's Git resolver support PR - https://github.com/openshift/hac-dev/pull/574
This PR specifically handles
1. UI breaking issue if bundle resolver is added via CLI (also webhook will convert all the existing ITS to new bundle format)
2. Disable edit action for the new bundle resolver as the UI supports only GIT resolvers in the add/edit form at the moment.
=> Integration test git support

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx, src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx, src/components/ImportForm/utils/types.ts
https://issues.redhat.com/browse/RHTAPBUGS-401
Use the selected runtime value instead of the detected runtime value to show/hide the dockerfile field.
This shows the dockerfile field even if the cdq doesn't return the detected project type as `Dockerfile`.
Use a repo for which cdq doesn't return Dockerfile as the language/project type. Eg. https://github.com/openshift-cnv/cnv-fbc
=> Use selected runtime field value to show/hide dockerfile field

src/components/ImportForm/__tests__/GitImportForm.actions.spec.tsx, src/components/ImportForm/utils/__tests__/submit-utils.spec.ts, src/components/ImportForm/utils/submit-utils.ts, src/components/IntegrationTest/IntegrationTestForm/const.ts
When an IntegrationTestScenario running the Enterprise Contract executes, the UI for the corresponding Application is populated with various security results. This is valuable information to users.
This change makes it so when an Application is created, the EC IntegrationTestScenario is automatically created with default values. This lowers the entrybarrier to accessing the security results.
In the future, this auto creation may move to another RHTAP component, e.g. a new EC controller. Or, it may be desireable to introduce UI controls to customize its initial creation, e.g. different Tekton bundle. It's unclear at this point what our users will prefer.  For this reason, we make the most minimal change possible to introduce the feature to users without investing too much in a certain …
=> Create EC Integration when creating an Application

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-372
A user has encountered an issue wherein they changed the runtime from the recommendation and the UI won't let them proceed to create the component. There are no errors or any feedback of any kind provided to the user. The button to create is simply disabled. Specifically the workflow got broken because they supplied a git reference.
- create a new application / component for https://github.com/redhat-gamedev/shipwars-move-server
- make sure to set the git reference to `master` even though this is the default
- Observe the recommendation is Dockerfile. Although this Dockerfile is NOT meant for build.
- Since this is a python project, change the runtime to python
- The `Create application/component` button remains disabled
=> do not pass git revision in cdq when the runtime is changed

src/components/ApplicationDetails/DetailsPage.scss, src/components/Components/BuildStatusColumn.tsx, src/components/Components/__tests__/BuildStatusColumn.spec.tsx, src/components/Components/__tests__/ComponentListItem.spec.tsx, src/components/LogViewer/BuildLogViewer.scss, src/components/LogViewer/BuildLogViewer.tsx, src/components/LogViewer/__tests__/BuildLogViewer.spec.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx, src/shared/components/pipeline-run-logs/PipelineRunLogs.scss, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/MultiStreamLogs.spec.tsx, src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx
Fixes [RHTAPBUGS-98](https://issues.redhat.com/browse/RHTAPBUGS-98)
Update component list item link from `View build logs` to `View details`.
Update the BuildLogViewer to include a link to the build pipeline run.
Some minor layout fixes in the BuildLogViewer modal.
Make log viewer tasks list scroll rather than the window in the pipeline run logs tab.
=> Allow users to show running pipeline from components views

integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts, integration-tests/tests/basic-happy-path.spec.ts, integration-tests/utils/Applications.ts
Add a test to ensure the default integration test is created automatically when a new Application is created.
https://issues.redhat.com/browse/HACBS-2193
=> Add e2e test for default integration test

src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx, src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-211
When you have no integration tests, the empty state directs the user to create one. Once you have at least one integration test, and no longer see the empty state, it gets trickier to figure out how to add additional integration tests. There's no add button near the table.
Users who explore may find it within the Actions menu, but it should be presented right on the main page.
**Before:**
**After:**
=> show add integration button in the list view

src/components/TaskRunDetailsView/TaskRunDetailsView.tsx, src/components/TaskRunDetailsView/tabs/TaskRunDetailsTab.tsx, src/components/TaskRunListView/TaskRunListRow.tsx, src/consts/pipeline.ts, src/types/coreTekton.ts, src/types/pipeline.ts, src/utils/__tests__/pipeline-utils.spec.ts, src/utils/pipeline-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-432
If task name is not in a taskRuns's taskRef.name, try to determine it from metadata.labels or taskRef.params.
=> Attempt to determine task name from taskRef or labels

src/components/Secrets/OpaqueSecretForm.tsx, src/shared/components/formik-fields/SelectInputField.tsx, src/shared/components/formik-fields/field-types.ts
- https://issues.redhat.com/browse/RHTAPBUGS-405
- Updated `SelectInputField` to accept more PF related props and added `isInputValuePersisted`.
https://github.com/openshift/hac-dev/assets/6041994/2d42fc1a-cb95-40ac-bf42-a6f475dabfee
=> Update select input field to persist input value

src/components/PipelineRunDetailsView/sidepanels/TaskRunPanel.tsx, src/components/TaskRunDetailsView/tabs/TaskRunLogsTab.tsx, src/components/TaskRuns/TaskRunLogs.tsx, src/components/TaskRuns/__tests__/TaskRunLogs.spec.tsx, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/LogWrapperComponent.spec.tsx, src/shared/components/pipeline-run-logs/__tests__/MultiStreamLogs.spec.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx, src/shared/components/pipeline-run-logs/__tests__/TektonTaskRunLog.spec.tsx, src/shared/components/pipeline-run-logs/logs/LogsWrapperComponent.tsx, src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx, src/shared/components/pipeline-run-logs/logs/TektonTaskRunLog.tsx, src/shared/components/pipeline-run-logs/logs/log-snippet-utils.ts, src/shared/components/pipeline-run-logs/logs/logs-utils.ts, src/shared/components/pipeline-run-logs/logs/pipelineRunLogSnippet.ts
Fixes https://issues.redhat.com/browse/HAC-4318
Adds support for retrieving log results from Texton when pods are no longer available.
/cc @rohitkrai03 @christianvogt
=> Add support for Tekton result logs

integration-tests/support/constants/PageTitle.ts, integration-tests/utils/Common.ts
https://issues.redhat.com/browse/HAC-4543
Wait for all navigation items to be visible before clicking on something.
=> Stabilise clicking on navigation menu items

src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-483
Tekton results query for fetching pipelineruns returns all the records that matches the application, this leads to showing the pipelineruns for the components which was deleted long before.
**Solution:**
Updated the query to fetch the pipelinruns by passing the active components  in the application to avoid showing old invalid build pipelineruns.
**Before:** 
Shows deleted Component's build pipelinerun in the list view:
**After:**
Shows only the build pipeline runs of all active components.
The pipelinerun list view should not include the deleted component's pipelinerun
cc: @rohitkrai03
=> Fetch pipelineruns only for active components in an application

src/components/LogViewer/BuildLogViewer.tsx, src/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx, src/hooks/__tests__/usePipelineRuns.spec.ts, src/hooks/__tests__/useTektonResults.spec.ts, src/hooks/usePipelineRuns.ts, src/hooks/useTektonResults.ts, src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx, src/shared/components/pipeline-run-logs/logs/logs-utils.ts, src/utils/__tests__/tekton-results.spec.ts, src/utils/tekton-results.ts
https://issues.redhat.com/browse/RHTAPBUGS-522
Tekton results API is failing with `401` Unauthorised error while you are in a shared workspace and this causes UI to not load  visualisations and component list view pages. This happens because the workspace information is not included in the API call so it defaults to user's home workspace.
Solution:
This PR appends workspace information in the tekton-results API request to properly map to a correct workspace.
All tekton-results API calls should contain workspace context eg :
`workspaces/<worksspace-name>/apis/results.tekton.dev/v1alpha2/parents/<namespace>/results/-/records`
1. Switch to a shared workspace and visit application details page or components list pages.
=> add workspace context in the tekton results api requests

src/components/ImportForm/GitImportActions.tsx, src/components/ImportForm/GitImportForm.tsx, src/components/ImportForm/__tests__/GitImportActions.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-502
Add reset handler directly to git import actions so that clicking does not immediately reset formik state.
https://github.com/openshift/hac-dev/assets/20013884/066a556c-5150-4074-a407-39e404406b98
Click cancel in review form.
=> Add reset handler to review form cancel button

deploy.yml
Broken production by marking files to be busted by cache buster.
There's mechanism to mark files not to be cached between builds.
=> Add cache busted files entries to deploy

src/components/Commits/__tests__/CommitsListRow.spec.tsx, src/components/Commits/__tests__/CommitsListView.spec.tsx, src/shared/components/commit-label/CommitLabel.tsx, src/shared/components/commit-label/__tests__/CommitLabel.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-507
Fixes commit label shotName to use commit-util functionality
=> fix-commit-label-shortname

test.sh
Broken reference to stable static files from preview environment.
Since we are utilizing cache buster now, long standing bug has surfaced where we are referencing stable static assets from preview environment. This PR fixes that by setting `BETA=true` if the build has been triggered from `master` or `main` branch.
=> When build is triggered from main branch set BETA to true

src/components/PipelineRunListView/PipelineRunListRow.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx, src/hooks/useScanResults.ts, src/utils/workspace-context-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-568
https://issues.redhat.com/browse/RHTAPBUGS-564
Fetching workspaces returns empty array due to the invalid url.
RCA:
UI makes calls to list the workspaces and sets the active namespace and workspace, but for this call to work properly we should not set the workspace context prior to this call or else this will result in empty array and impact all other subsequent API calls that UI makes.
Solution:
Reset the active workspace before list workspaces
**Before:**
**After**:
https://github.com/openshift/hac-dev/assets/9964343/84dd0401-3d2e-4a5b-b1f5-3319af2ce784
=> reset active workspace before listing workspaces

src/utils/__tests__/tekton-results.spec.ts, src/utils/tekton-results.ts
! expression in tekton-results util was disabled because it was crashing the tekton-results service. It is now fixed and working properly, so enabling the filter back.
=> Enable `(!)` cel filter in tekton results API

src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppIntegrationTestNodes.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppBuildNodes.ts, src/hooks/__tests__/useBuildPipelines.spec.ts, src/hooks/useBuildPipelines.ts, src/hooks/useTestPipelines.ts
https://issues.redhat.com/browse/RHTAPBUGS-574
The default limit for a response in tekton results is 4mb but the lifecycle graph makes call with `100` pagesize so the response is more than the limit and fails to load the graph.
Included the component names in the query filter and also dynamically setting the pageSize based on the number of components in an application.
**Before**:
**After**:
Visit acm shared workspace application details page to see the graph loading.
=> update TR Api query filter and page size in lifecycle graph 

src/components/ImportForm/GitImportActions.tsx
- https://issues.redhat.com/browse/RHTAPBUGS-583
- `isValidating` gets updated multiple times as soon as detected components are added to formik values. We don't need to disable the submit button while validating because there's no async validation happening on the form.
Before ---
https://github.com/openshift/hac-dev/assets/6041994/01b19de9-2752-4b4d-946d-91aa57825de5
After ---
https://github.com/openshift/hac-dev/assets/6041994/9cd9ffb5-34c9-48a3-944c-cb1b62fce833
=> Fix create button flickering after component detection

integration-tests/Dockerfile, integration-tests/README.md, integration-tests/entrypoint.sh
https://issues.redhat.com/browse/HAC-4659
makes it possible to run e2e test image with arguments passed directly to cypress
=> enable passing cypress args to image entrypoint

src/components/Components/ComponentPACStateLabel.tsx, src/components/CustomizedPipeline/CustomizePipelines.tsx, src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx, src/hooks/__tests__/usePACState.spec.ts, src/hooks/usePACState.ts
https://issues.redhat.com/browse/HAC-4289
Switch from showing hardcoded error message to error from component build status annonation.
https://github.com/openshift/hac-dev/assets/20013884/e0ab5eba-9945-4e9f-a06b-121ba8ce70ea
Try to trigger pac error.
=> Show PAC build errors

src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx, src/hooks/useScanResults.ts, src/hooks/useTektonResults.ts, src/utils/__tests__/tekton-results.spec.ts, src/utils/tekton-results.ts
https://issues.redhat.com/browse/RHTAPBUGS-578
https://issues.redhat.com/browse/RHTAPBUGS-584 
when a user tries to use the name filter the browser goes unresponsive.
https://github.com/openshift/hac-dev/assets/9964343/540297c1-463b-48d1-a5fa-f5911d9f38f0
https://github.com/openshift/hac-dev/assets/9964343/aa8bd028-1073-45ce-a8a2-89c04b3852a6
Commit pipelineruns tab:
=> Fix namefilter in pipelinerun list page causing memory leaks

src/components/ImportForm/ReviewSection/ReviewSection.tsx, src/components/ImportForm/ReviewSection/RuntimeSelector.tsx, src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-469
Always allow component creation if dockerfile runtime is selected.
https://github.com/openshift/hac-dev/assets/20013884/eb951d2f-5c75-4501-93dd-e63e2ce1a7b8
Use a repo that returns error when detection, and select dockerfile runtime.
=> Always allow component creation if dockerfile runtime is selected

integration-tests/package-lock.json, integration-tests/package.json, integration-tests/support/commands/index.ts, integration-tests/support/pageObjects/global-po.ts, integration-tests/tsconfig.json, integration-tests/utils/UIhelper.ts
https://issues.redhat.com/browse/HAC-4758
As cypress has officially removed the support for xpath plugin remove the deprecated xpath plugin from all the e2e tests.
=> e2e: Remove the xpath plugin and update the tests

integration-tests/support/constants/PageTitle.ts, integration-tests/support/pageObjects/pages-po.ts, integration-tests/support/pages/GetStartedPage.ts, integration-tests/utils/Login.ts
https://issues.redhat.com/browse/HAC-4543
Tests are stuck on a loading page when the `Applications` are clicked after the login. Add a check for the `Get started` page to be fully loaded to prevent it.
=> Add check for all buttons to be ready.

src/hooks/useScanResults.ts
https://issues.redhat.com/browse/RHTAPBUGS-584
Vulnerability column is not updating when you first visit pipeline runs tab and then visit commit tab or vice versa
Before:
After:
=> fix vulnerability column not loading issue

src/components/ComponentSettingsForm/__tests__/ComponentSettingsView.spec.tsx, src/components/ImportForm/SecretSection/SecretSection.tsx, src/shared/components/formik-fields/key-value-file-input-field/KeyValueFileInputField.tsx, src/types/secret.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/HAC-4696
Use remoteSecrets while creating partner secrets like snyk, so that the partner secrets will be listed in the secrets list view.
This PR Replaces the spiAccessTokenBindings with RemoteSecret CR
No UI changes. Once the build secret is created you should see the secret in the listing page.
1. Edit a component -> Add secret -> Save.
2. Go to Secret list page and search the created build secret.
/cc @rohitkrai03 @rottencandy
=> use RemoteSecret for creating partner task secrets

src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx, src/shared/components/pipeline-run-logs/__tests__/PipelineRunLogs.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-515
Select first failed logs tab when active tab is not provided.
https://github.com/openshift/hac-dev/assets/20013884/5552b9f6-b197-47c5-8d33-43cb3407da6a
Try to open build logs for a component with failed build.
=> Select first failed logs tab by default

src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx, src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx
Fixes [RHTAPBUGS-755](https://issues.redhat.com/browse/RHTAPBUGS-755)
Display the empty indicator when the container image for a component is absent.
=> Fix component details when no container image

src/components/Components/ComponentDeployments/ComponentDeploymentsListHeader.tsx, src/components/Components/ComponentDeployments/ComponentDeploymentsListRow.scss, src/components/Components/ComponentDeployments/ComponentDeploymentsListRow.tsx, src/components/Components/ComponentDeployments/ComponentDeploymentsListView.tsx, src/components/Components/ComponentDeployments/__tests__/ComponentDeploymentsListRow.spec.tsx, src/components/Components/ComponentDetails/ComponentDetailsView.tsx, src/components/Components/ComponentDetails/__data__/mockComponentDetails.ts, src/components/Components/ComponentDetails/__tests__/ComponentActivityTab.spec.tsx, src/components/Components/ComponentDetails/__tests__/ComponentDeploymentsTab.spec.tsx, src/components/Components/ComponentDetails/tabs/ComponentActivityTab.tsx, src/components/Components/ComponentDetails/tabs/ComponentDeploymentsTab.tsx, src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx, src/components/PodLogs/PodLogsButton.tsx, src/hooks/useComponentDeployment.ts, src/shared/components/table/Table.tsx
Fixes [HAC-4697](https://issues.redhat.com/browse/HAC-4697)
Adds a `Deployments` tab to the component details page
=> Add Deployments tab to the Component Details page

integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
https://issues.redhat.com/browse/RHTAPBUGS-805
=> e2e: fix getPipelineRunNameByLabel not waiting for the resource

src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/validation-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-767
Add resource name validation for Integration test resource form, users should not be able to click on Create button until they fix the validation error.
Show validation error when a extra space is added:
Add integration test name with a extra space in the end.
=> Fix integration name validation issue

src/components/ImportForm/ReviewSection/ReviewSection.tsx, src/components/ImportForm/utils/__tests__/useValidApplicationName.spec.ts
https://issues.redhat.com/browse/RHTAPBUGS-775
Auto recommendation of applicaiton name was not invoked due to the git regex check failure. Trimming the source url before performing it to git regex fixes it.
**Before:**
**After**
1. Add a git url with extra spaces in the start and end of the url " https://github.com/trustification/trustification/ "
2. Click on `Import  code`
=> fix app name auto recommendation when git url has extra spaces

integration-tests/support/pageObjects/pages-po.ts, integration-tests/utils/Applications.ts, src/components/ApplicationDetails/ApplicationHeader.tsx, src/components/ApplicationDetails/__data__/WorkflowSnapshotsEnvironmentBindingsData.ts, src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppStaticEnvironmentNodes.ts, src/components/Environment/__tests__/EnvironmentListView.spec.tsx, src/hooks/__data__/mock-data.ts, src/hooks/useApplicationHealthStatus.ts, src/types/coreBuildService.ts, src/utils/environment-utils.tsx
Fixes [RHTAPBUGS-783](https://issues.redhat.com/browse/RHTAPBUGS-783)
Update the computation of the deployed application status to use status.gitopsDeployment instead of status.componentsDeploymentConditions
=> Update computation of deployed application status

src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts, src/components/IntegrationTest/FormikParamsField.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx, src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx, src/components/IntegrationTest/IntegrationTestForm/types.ts, src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts, src/components/IntegrationTest/__tests__/FormikParamsField.spec.tsx, src/pages/EditIntegrationTestPage.tsx, src/types/coreBuildService.ts
https://issues.redhat.com/browse/HAC-4596
- Adds parameter support for IntegrationTest
- Creates a Param component
=> feat(Integrationtest): integration test param support

src/components/IntegrationTest/IntegrationTestForm/const.ts, src/components/IntegrationTest/IntegrationTestForm/types.ts, src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts
[](https://issues.redhat.com/browse/HACBS-2547)
The auto-created Enterprise Contract IntegrationTestScenarios are now annotated with `test.appstudio.openshift.io/kind: enterprise-contract` annotation.
n/a
Create an Application, and check that the auto-generated Enterprise Contract IntegrationTestScenario has the `test.appstudio.openshift.io/kind: enterprise-contract` annotation.
This change should be browser independent, it only contains logic changes and doesn't touch the browser.
=> feat: add kind annotation to EC ITS

src/components/TaskRuns/TaskRunLogs.tsx
Fixes [HAC-5103](https://issues.redhat.com/browse/HAC-5103)
Attempt to get pod logs for skipped or idle tasks. Show existing messages only if the pod does not exist.
=> fix(task logs): show logs for skipped or idle tasks if they exist

src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts, src/utils/__tests__/component-utils.spec.ts, src/utils/component-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-771
Use exact label match for checking PAC state, since labels are immediately updated on PAC request and the done check is not relevant anymore.
(No UI updates)
1. Create component with custom pipeline
2. Switch to default pipeline
3. Check component kebab menu, it should show "start new build" option
=> fix: Use exact label match for PAC state check

src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/node-utils.spec.ts, src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
Fixes [HAC-5105](https://issues.redhat.com/browse/HAC-5105)
Fix for URL created for the `No builds yet` node in the overview graph. UI should navigate to the components list view.
=> fix(overview graph): navigate to components list on No builds node click

src/components/Secrets/__tests___/secret-utils.spec.ts, src/components/Secrets/utils/secret-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-913
Secret list page is throwing error when it is redirected from Add secret page. recently created secret is not having status field initially and the list page is looking for the status field to read the number of key/value pairs in the secret which is causing the page to fail.
https://github.com/openshift/hac-dev/assets/9964343/8f53643a-d88e-4162-aebd-0376d5158150
Add a build secret from the UI and wait for the UI to redirect to the secret list page.
=> fix(secret-list): fix secret list page error when secret is missing status field

src/components/UserAccess/UserAccessForm/UsernameSection.tsx, src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx, src/components/UserAccess/UserAccessForm/__tests__/form-utils.spec.ts, src/components/UserAccess/UserAccessForm/form-utils.ts
https://issues.redhat.com/browse/RHTAPBUGS-900
Use username API to validate usernames.
https://github.com/openshift/hac-dev/assets/20013884/f763d78c-da69-46cc-91ab-6e1ce0f8c252
Add access to users with grant access form.
=> fix(access): Use username API to validate usernames in access form

src/hooks/__tests__/useComponents.spec.ts, src/hooks/useComponents.ts
https://issues.redhat.com/browse/RHTAPBUGS-924
Activity tab in Component details page is loading forever and never resolves commit list view.
Before: 
After:
/cc @jeff-phillips-18
=> fix commit activity tab in components details page

integration-tests/tests/advanced-happy-path.spec.ts
https://issues.redhat.com/browse/RHTAPBUGS-951
Make sure the tests end up on the push triggered pipeline run when checking itests
=> fix(e2e): select the correct itest pipeline

pact-tests/contracts/contracts.ts, pact-tests/contracts/service-provider-integration/spiaccesscheck.ts, pact-tests/spi.pact.spec.ts, pact-tests/states/state-params.ts
https://issues.redhat.com/browse/HAC-5471
Introduce SPI contract tests to HAC-dev and SPi repo. Starting with a simple contract of 'spiaccesscheck' creation.
Depends on https://github.com/openshift/hac-dev/pull/808
=> Add SPI Pact contract test

src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts, src/components/SnapshotDetails/EnvironmentProvisionErrorAlert.tsx, src/components/SnapshotDetails/SnapshotDetailsView.tsx, src/components/SnapshotDetails/__tests__/EnvironmentProvisionErrorAlert.spec.tsx, src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx, src/components/SnapshotDetails/tabs/SnapshotOverview.tsx, src/components/SnapshotDetails/tabs/SnapshotPipelineRunsList.tsx, src/components/SnapshotDetails/tabs/SnapshotPipelineRunsTab.tsx, src/components/SnapshotDetails/tabs/__tests__/SnapshotOverview.spec.tsx, src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsList.spec.tsx, src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsTab.spec.tsx, src/components/SnapshotDetails/utils/__tests__/snapshot-utils.spec.ts
https://issues.redhat.com/browse/RHTAPBUGS-839
- Updates PLR list to include test PLRs with snapshot label
- capitalizes snapshot in breadcrumb
- capitalizes Environmenr names
=> fix(snapshot): add test pipelinerun list and capitalize breadcrumbs

src/components/ApplicationListView/ApplicationListRow.tsx, src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-815
Use SnapshotEnvironmentBindings directly instead of fetching all environment bindings to get an application's last deploy date.
Create applications, and check last deploy date.
=> fix(applications): Use SnapshotEnvironmentBindings directly to get last deploy date

src/components/Commits/CommitDetails/CommitDetailsView.tsx, src/components/Commits/CommitDetails/__tests__/CommitDetailsView.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-987
If using the first available commit pipelinerun for commit details, we accidentaly use the integration test pipeline instead of build pipeline.
Explicitly find the first build pipelinerun instead.
Use custom pipeline flow and see commit details
=> fix(commits): Avoid using test pipelineruns for commit details

src/components/ImportForm/SecretSection/SecretSection.tsx, src/components/ImportForm/SecretSection/__tests__/SecretSection.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-1004
Add access check to add secret button in git import form.
Try to add secret in a workspace without delete permissions.
=> fix(import): Add access check to add secret button

integration-tests/tests/create-application-from-sample.spec.ts
Followup on https://issues.redhat.com/browse/RHTAPBUGS-1010
E2E tests for the Quarkus sample are occasionally failing because of page refresh. I'm not sure what to add for the check other than ugly wait.
=> test(e2e): stabilize e2e quarkus sample test

src/shared/components/commit-label/CommitLabel.scss, src/shared/components/commit-label/CommitLabel.tsx, src/shared/components/commit-label/__tests__/CommitLabel.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-837
Use black color for commit label logo.
Go to a page that uses commit labels.
=> fix(commit): Use black color for GH commit logo

src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts, src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts, src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx, src/components/IntegrationTest/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx
https://issues.redhat.com/browse/RHTAPBUGS-884
- avoid showing params where value is not defined
- use `master` as default branch when revision param is not provided (GH automatically redirects to a valid default branch in this case)
Create an integration test without specifying git revision.
=> fix(integration-test): Handle missing revision in git url params

src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.scss
Fixes [RHTAPBUGS-1080](https://issues.redhat.com/browse/RHTAPBUGS-1080)
The height of the tooltips was not constrained at all so if there are a lot of builds (or any other items) in a tooltip it would be larger than the view height causing the window to scroll past the current view leaving lots of blank space.
Set the maximum height of the tooltip to be 600 pixels and have the individual items in a scrollable area so the user can view all the items if desired.
Create a project with many many builds. Hover over the build node in the overview section.
=> fix(overview): set max height for tooltips on nodes

src/utils/__tests__/tekton-results.spec.ts, src/utils/tekton-results.ts
https://issues.redhat.com/browse/RHTAPBUGS-1093
PipelineRun logs is not streaming properly in the UI because the tekton results logs API is now returning raw logs content directly, so UI doesn't need to decode the value again.
tekton-results PR introduced this change - https://github.com/tektoncd/results/pull/632
Before:
After:
- Visit logs tab in the pipelinerun details page
=> fix(logs): Update PLR logs fetch logic to match the new tekton results changes

integration-tests/support/constants/PageTitle.ts
https://issues.redhat.com/browse/HAC-5659
The "Learning resources" item was removed from a Menu. Removing it from tests.
=> fix(test): remove menu item Learning resources

src/components/ComponentRelation/ComponentRelationForm.tsx, src/components/ComponentRelation/ComponentRelationModal.tsx, src/components/ComponentRelation/ComponentRelationshipDropdowns.tsx, src/components/ComponentRelation/__tests__/ComponentRelationForm.spec.tsx, src/components/ComponentRelation/__tests__/ComponentRelationModal.spec.tsx, src/components/ComponentRelation/__tests__/ComponentRelationshipDropdowns.spec.tsx, src/components/ComponentRelation/__tests__/useNudgeData.spec.ts, src/components/ComponentRelation/cr-modals.tsx, src/components/ComponentRelation/useNudgeData.ts, src/hooks/__tests__/useComponents.spec.ts, src/hooks/useComponents.ts
https://issues.redhat.com/browse/HAC-5657
=> fix(ComponentRelation): use component from all applications

src/components/Commits/CommitsListView.tsx, src/components/Commits/__tests__/CommitsListView.spec.tsx, src/components/Commits/tabs/CommitsPipelineRunTab.tsx, src/components/Commits/tabs/__tests__/CommitsPipelineRunTab.spec.tsx, src/components/IntegrationTest/tabs/IntegrationTestPipelineRunTab.tsx, src/components/IntegrationTest/tabs/__tests__/IntegrationTestPipelineRunTab.spec.tsx, src/components/PipelineRunListView/PipelineRunListRow.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx, src/hooks/__tests__/useScanResults.spec.ts, src/hooks/__tests__/useTektonResults.spec.ts, src/hooks/useScanResults.ts, src/hooks/useTektonResults.ts
https://issues.redhat.com/browse/KFLUXBUGS-1168
https://issues.redhat.com/browse/KFLUXBUGS-1169 
This PR aims to improve the tekton results API fetching and error handling.
The changes includes
1.  Avoiding multiple re-fetches of same API call on load of the pipelinerun list view
2. Add error states in all the pipelinerun list views like commit page, integration page and in activity tab.
3. Incase of error while fetching the taskruns (vulnerability column) then UI will show `N/A` and avoids refetching.
**Initial load of Pipelinerun/taskruns:**
https://github.com/openshift/hac-dev/assets/9964343/19f2d4e7-a281-43e0-b3b5-a8567bae0e93
_Note: Previously Initial loads used to make two same Taskrun calls, that is now fixed._
---
**Pipelinerun API call failure:**
**Vulnerability Taskrun API call …
=> Add Tekton results API error handling and enable cache to avoid refetches on load

src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx, src/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx, src/components/PipelineRunListView/pipelinerun-actions.tsx
https://issues.redhat.com/browse/KFLUXBUGS-1132
When pipeline rerun action is hidden there is no way the user can know why the action is not present. Instead the disabled action with disabled tooltip provides user info as to why it is hidden.
=> fix(PLR): Remove hidden prop from rerun action

src/components/CustomizedPipeline/CustomizePipelines.tsx, src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
- https://issues.redhat.com/browse/KFLUXBUGS-1127
- Fix the way content inside the table behaved by adding proper modifier.
- Added a truncate option for image url.
=> fix(pipeline-modal): fix table row width and content for pipeline modal

integration-tests/tests/advanced-happy-path.spec.ts, integration-tests/utils/APIEndpoints.ts, integration-tests/utils/APIHelper.ts
https://issues.redhat.com/browse/KFLUXBUGS-1229
github removed the import API that e2e tests were using, replace it with generating repos from a template
=> fix(e2e): replace github import API with template generation

integration-tests/tests/advanced-happy-path.spec.ts, src/components/Commits/tabs/CommitsPipelineRunTab.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/SnapshotDetails/tabs/SnapshotPipelineRunsList.tsx
Advanced Happy Path test suite is constantly failing during the nightly job to load the Vulnerabilities. Stabilize the loading of Vulnerabilities by refreshing the page during the Advanced Happy Path test suite.
=> fix(test): stabilise vulnerabilities 

src/components/Secrets/SecretTypeSelector.scss, src/components/Secrets/SecretTypeSelector.tsx, src/components/Secrets/SecretsForm/ImagePullSecretForm.tsx, src/components/Secrets/SecretsForm/SecretTypeSubForm.scss, src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx, src/components/Secrets/SecretsForm/SourceSecretForm.tsx, src/components/Secrets/SecretsListView/SecretsList.tsx, src/components/Secrets/SecretsListView/SecretsListRow.tsx, src/components/Secrets/SecretsListView/SecretsListView.tsx, src/components/Secrets/__tests___/SecretsListView.spec.tsx, src/components/Secrets/__tests___/secret-utils.spec.ts, src/components/Secrets/secret-actions.ts, src/components/Secrets/secret-modal.tsx, src/components/Secrets/utils/__tests__/service-account-utils.spec.ts, src/components/Secrets/utils/secret-utils.ts, src/components/Secrets/utils/service-account-utils.ts, src/components/modal/DeleteResourceModal.tsx, src/hooks/UseRemoteSecrets.ts, src/models/index.ts, src/models/service-account.ts, src/types/secret.ts, src/utils/__tests__/create-utils.spec.ts, src/utils/create-utils.ts
https://issues.redhat.com/browse/HAC-5715
https://issues.redhat.com/browse/HAC-5717
- Adds input field for host & repo in AddSecret form.
- removes remote secret labels from Secret creation utils.
- For source secret adds scm labels and annotation in createSecret utils.
- Modifies and adds to related unit tests
- Updates Secret List View & related utils to use K8sSecrets instead of Remote Secrets.
- Links & unlinks Image pull Secrets to Service accounts on creation and deletion
=> feat(secrets): add scm host metadata

config/remotePlugin.js, src/pages/SecretsListPage.tsx, src/pages/WorkspacedPage.tsx, src/pages/__tests__/SecretsListPage.spec.tsx, src/pages/__tests__/WorkspacedPage.spec.tsx
https://issues.redhat.com/browse/KFLUXBUGS-1286
Add workspace switcher on the secret list page
=> fix(SecretListPage): add workspace breadcrumbs on secrets list page

integration-tests/tests/basic-happy-path.spec.ts
Don't remove the GitHub repository, if a test fails. It may ease the debugging of a failure.
=> fix(test): don't remove repo if test failed to easy failure debugging

integration-tests/tests/advanced-happy-path.spec.ts, pr_check.sh
Advanced tests started to fail when verifying a Pipeline label in the Pipeline run details view for the enterprise contract pipeline. It changed from pipeline name to `enterprise-contract`.
=> fix(test): update Pipeline label value in pipeline run details view

pr_check.sh
switch back to main branch of  [CICD-tools](https://github.com/RedHatInsights/cicd-tools)
A [hotfix](https://github.com/RedHatInsights/cicd-tools/pull/95) has been merged and released into the CICD tools repo to deal with the IMAGE_TAG value setting bug in some pipelines.
=> ci: switch back to main cicd-tools branch

src/components/IntegrationTest/IntegrationTestForm/const.ts
* https://issues.redhat.com/browse/EC-668
The build-definitions repo moved over to the new konflux-ci org in GitHub. Update the pipeline definition git resolver url accordingly.
One-liner to update a git url.
Should be zero visible change.
I expect the risk is almost zero here. CI might be enough, but to test it, create a component and make sure the automatically created Enterprise Contract Integration Test Scenario is create and runs as expected.
=> Use new git location for ec pipeline definition

src/components/ImportForm/PipelineSection/__tests__/usePipelineTemplate.spec.ts, src/components/ImportForm/PipelineSection/usePipelineTemplate.ts
https://issues.redhat.com/browse/EC-739
Switches the default pipeline to the OCI Trusted Artifacts pipeline. Also includes a bump of other pipeline versions.
Imagine different options provided on the drop down.
Add a new component and examine the offered pipelines.
=> feat: add and use docker-build-oci-ta as default

src/components/ImportForm/PipelineSection/__tests__/usePipelineTemplate.spec.ts, src/components/ImportForm/PipelineSection/usePipelineTemplate.ts
With https://github.com/konflux-ci/build-definitions/pull/1236, we started building a multi-arch pipeline. This change adds it to the config map so that it can be used for configuring components.
=> Add the multi-arch pipeline to the pipeline config

integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
The advanced test path started to fail as `sbom-json-check` task was removed ([PR#1330](https://github.com/konflux-ci/build-definitions/pull/1330)). Removing the task from tests too.
=> fix(test): remove sbom-json-check

src/components/ComponentRelation/ComponentRelationForm.tsx, src/components/ComponentRelation/ComponentRelationModal.tsx, src/components/ComponentRelation/__tests__/ComponentRelationForm.spec.tsx, src/components/ComponentRelation/__tests__/ComponentRelationModal.spec.tsx, src/components/ComponentRelation/__tests__/utils.spec.ts, src/components/ComponentRelation/cr-modals.tsx, src/components/ComponentRelation/utils.ts
Missing remove button on component relationship modal
Fixes [KFLUXBUGS-1197](https://issues.redhat.com//browse/KFLUXBUGS-1197)
- [x ] Chrome
=> fix(KFLUXBUGS-1197): component relationship remove button

integration-tests/utils/Applications.ts, src/components/Secrets/SecretForm.tsx, src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx, src/components/Secrets/__tests___/AddSecretForm.spec.tsx, src/components/Secrets/__tests___/SecretTypeSubForm.spec.tsx
[KFLUXBUGS-96](https://issues.redhat.com//browse/KFLUXBUGS-96)
The secret forms were not clear regarding the name of the secret variable. It was recommended to change to "Select or enter secret name" across multiple views.
=> fix(KFLUXBUGS-96): make the secret forms more clear

src/components/Releases/ReleaseOverviewTab.tsx, src/components/Releases/__data__/mock-release-data.ts, src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx, src/types/release.ts
https://issues.redhat.com/browse/KFLUXBUGS-1683
Release service updated the status of Releases as part of https://issues.redhat.com/browse/RELEASE-1109 `status.managedProcessing` should be used instead of `status.processing` to get the data for PipelineRun
=> fix: use status.managedProcessing to get the pipelineRun for Release

src/components/ImportForm/ComponentSection/GitOptions.tsx
[HAC-5855](https://issues.redhat.com/browse/HAC-5855)
Using a tag or commit can have unintended consequences. Lets only recommend that users use a branch when setting up their components.
**Before:**
**After:**
=> fix(HAC-5855): only suggest branches for component

src/components/UserAccess/UserAccessForm/UsernameSection.tsx, src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx
[KFLUXBUGS-1719](https://issues.redhat.com/browse/KFLUXBUGS-1719)
1. Change the username regex to ensure '.' is valid.
2. Improve the related test for the improved user format
1. Click the 'User Access'
2. Click the 'Grant User'
3. Enter the username as 'anatale.openshift'
=> fix(KFLUXBUGS-1719): support dot in the username format

src/components/IntegrationTest/FormikParamsField.tsx
https://issues.redhat.com/browse/KFLUXBUGS-1648
In the IntegrationTests edit parameter modal, only a generic `Parameter[i]` name was displayed, which made it difficult to find the right parameter. Instead, now the parameter name is displayed in the header. Same thing applies to the parameters when editing the whole integration test or creating a new release plan in the current workspace, which allows users to specify parameters.
Before:
After:
=> fix(KFLUXBUGS-1648): display parameter name for IntegrationTests

src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx, src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
https://issues.redhat.com/browse/KFLUXBUGS-1710
Adds null check for taskRun status and also adds block to fetch Tektonrecords if no taskrun is found
=> fix(pipeline): null check on status of taskrun

integration-tests/support/pageObjects/atlas-po.ts, integration-tests/tests/advanced-happy-path.spec.ts
Fix missing page objects for Atlas. Enable advanced test again, with SBOM check.
=> fix(e2e): enable sbom test, fix missing pageobjects

src/components/IntegrationTest/ContextSelectList.tsx, src/components/IntegrationTest/ContextsField.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx, src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx, src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestSection.spec.tsx, src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx, src/components/IntegrationTest/IntegrationTestForm/types.ts, src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts, src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts, src/components/IntegrationTest/__tests__/ContextsField.spec.tsx, src/components/IntegrationTest/__tests__/ContextsSelectList.spec.tsx, src/components/IntegrationTest/utils.tsx
[HAC-5814](https://issues.redhat.com/browse/HAC-5814)
Allow users to set and edit the `contexts`  field of IntegrationTestScenarios in the Konflux UI.
Users can choose to add or remove contexts from a predefined list of supported contexts.
The `application` context is set as the default context.
**Before**:
**After**:
=> feat(HAC-5814): allow users to set context in UI

src/components/ImportForm/ComponentSection/SourceSection.tsx, src/components/ImportForm/ComponentSection/__tests__/ComponentSection.spec.tsx, src/components/ImportForm/__tests__/submit-utils.spec.ts
[KFLUXBUGS-1372](https://issues.redhat.com/browse/KFLUXBUGS-1372)
When creating component, there is a switch labeled with 'is this a private repo?'. 
People consider it is talking about the 'git repo' itself but it is talking about 'image repo'. 
Enable the switch, the image repository would be private. The original switch context is confusing. 
The patch improve the label from 'is this a private repo' to 'is this a private image repo'.
1. Click 'Create an application'
2. Input the valid git repo
3. Check the switch 'Should the image produced be private?'
4. Input the Dockerfile path and component name
5. Click 'Add Component'
6. Run 'kubectl get imagerepository' to ensure the target imagerepository is private
7. After the build pipeline, navigate to quay.io to ensure the access of the …
=> feat(KFLUXBUGS-1372): improve the label of private image repo

pr_check.sh
https://issues.redhat.com/browse/KFLUXUI-171
Add paths to frontends to workaround issue with /beta path. It's a little hacky way, but it's agreed that hac-dev (and therefore hac-core) is being decommissioned soon. The other way is publishing a fixed image again but the process is currently not clear and easy.
=> fix(e2e): enable tests on eph env

src/components/Components/ComponentDetails/__tests__/ComponentActivityTab.spec.tsx, src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx, src/components/Components/ComponentDetails/tabs/ComponentActivityTab.tsx
[KFLUXBUGS-1537](https://issues.redhat.com/browse/KFLUXBUGS-1537)
There is one 'Activity' tab on Component Details page. When users click it, its navigation should
point to component.metadata.name(the unique ID of component).
1.  clone the repo https://github.com/testcara/KFLUXBUGS-1537-reproduce/tree/product-1
2. create the application, component and imagerepository with application-1.yaml, component-1.yaml, image-repo-1.yaml by cli
3. go to the konflux UI dashboard then navigate to the component details page
4. click the 'Activity' tab on it to ensure there is no '404' error.
=> fix(KFLUXBUGS-1537): activity tab should use component.metadata.name

src/components/Releases/__tests__/ReleasesListRow.spec.tsx, src/hooks/__tests__/useReleaseStatus.ts, src/hooks/useReleaseStatus.ts
https://issues.redhat.com/browse/KFLUXBUGS-1751
When type is 'Released', reason is 'Succeeded' and status is 'True', release should be shown as 'success'.
While if the release does not meet the requirements, its status would be progressing/failed/pending.
when the release resource is shown as:
```
carawang@pipeline-examples %oc get release five-release -o yaml | grep -b4 'type: Released'
554-  - lastTransitionTime: "2024-11-05T09:57:42Z"
601-    message: ""
617-    reason: Succeeded
639-    status: "True"
658:    type: Released
```
the UI of the release is Succeeded
Trigger a release, the status of the release on UI should be shown correctly.
=> fix(KFLUXBUGS-1751):  release status replies on status and reason of the release type

src/components/Activity/__tests__/ActivityTab.spec.tsx, src/components/Commits/__tests__/CommitsListView.spec.tsx, src/components/Components/ComponentDetails/__tests__/ComponentActivityTab.spec.tsx, src/components/Components/__tests__/ComponentListView.spec.tsx, src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx, src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx, src/components/PipelineRunListView/PipelineRunsListView.tsx, src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx, src/hooks/__tests__/useBuildPipelines.spec.ts, src/hooks/__tests__/useLatestBuildPipelines.spec.ts, src/hooks/__tests__/usePACStatesForComponents.spec.ts, src/hooks/__tests__/usePipelineRuns.spec.ts, src/hooks/useBuildPipelines.ts, src/hooks/useLatestBuildPipelines.ts, src/hooks/useLatestIntegrationTestPipelines.ts, src/hooks/usePACStatesForComponents.ts, src/hooks/usePipelineRuns.ts, src/utils/__tests__/tekton-results.spec.ts, src/utils/tekton-results.ts
[KFLUXBUGS-1680](https://issues.redhat.com//browse/KFLUXBUGS-1680)
Querying pipelineruns or records may include all component names making the query to long and throws an HTTP error 414 or 431. Component names were included in the filter to avoid a visual issue when recreating an application with the same name, previously ran pipelineruns are displayed.
The component filter array is removed and uses the record creationTimestamp filter to be greater than the application creationTimestamp.
Create a large number of components with large names.
[ ] Test A 
Initial issue:
When the query is too long, we should hit an http error 414 or as I do, a 431 locally.
[ ] Test B 
Once change applied,  the filter includes a creationTimestamp attribute and removed the component matchExpression filter. …
=> fix(KFLUXBUGS-1680):  filter records on creationTimestamp

src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx, src/components/GitLink/GitRepoLink.tsx, src/shared/components/links/ExternalLink.scss, src/shared/components/links/ExternalLink.tsx
[KFLUXBUGS-1779](https://issues.redhat.com/browse/KFLUXBUGS-1779)
The external links in the Component details page are not highlight-able for users, so they cannot copy those values. 
An optional CSS class was added so they can become highlight-able where desired.
[links-not-highlightable.webm](https://github.com/user-attachments/assets/bc4dffd6-1cbd-4f8a-be9e-7e5378ead476)
[links-now-highlightable.webm](https://github.com/user-attachments/assets/9e5f0933-e392-4dc8-bb25-bdaf6712a228)
=> fix(KFLUXBUGS-1779): allow highlightable links

src/components/ImportForm/ComponentSection/GitProviderDropdown.tsx, src/components/ImportForm/ComponentSection/SourceSection.tsx, src/components/ImportForm/ComponentSection/__tests__/ComponentSection.spec.tsx, src/components/ImportForm/validation.utils.ts
https://issues.redhat.com/browse/KFLUXBUGS-1745
Makes selection of git-provider annotation mandatory
Adds https:// to the git-url annotation
=> fix(import): make dropdown mandatory

src/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx, src/components/PipelineRunListView/pipelinerun-actions.tsx
Fixes: https://issues.redhat.com/browse/KFLUXBUGS-1910
It appears that the `PipelineRunTypeEvent` differs between Github and Gitlab (`push` vs `Push`). This prevents the user from re-running on-push pipelines.
=> fix(KFLUXBUGS-1910): add Gitlab push event type

src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts, src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx, src/components/Components/ComponentDetails/tabs/ComponentLatestBuild.tsx, src/components/Components/ComponentsListRow.tsx, src/components/CustomizedPipeline/CustomizePipelines.tsx, src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx, src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx, src/types/component.ts, src/utils/__tests__/component-utils.spec.ts, src/utils/component-utils.ts
[KFLUXUI-256](https://issues.redhat.com/browse/KFLUXUI-256)
The integration service recently migrated from using the component's spec.containerImage field to store the latest image to using the component's status.lastPromotedImage field.
The patch support the component.spec.containerImage as the latestImage when it's valid.
=> feat(KFLUXUI-256): support component.spec.containerImage as latestImage

integration-tests/tests/advanced-happy-path.spec.ts, src/hooks/__tests__/useUIInstance.spec.ts, src/hooks/useUIInstance.ts
Atlas was recently split into multiple instances and Konflux UI should use the new Build instance and its URL. The underneath instance is still the same but URL is more specific now.
=> Replace Atlas CNAMEs
