openshift/hac-dev

build.sh
test.sh

The config @florkbr is using to setup the OpenShift Bot to get `/lgtm` and `/approve` (among other things) into the HAC repos requires a couple of scripts. This PR is to add those so the bot can execute successfully on your repo.
Please https://github.com/openshift/release/pull/23230 for the release config powering this. 
Please merge this PR when you get a chance and the above PR probably will need a `/retest`. Hopefully it will pass at that point. If it does, the owners in this repo should have power over merging it with normal `/approve`-esk mechanics.
Once both of these PRs are merged. You should be good to make use of the OpenShift Bot as we do in OpenShift Console.

Init build/test scripts

---

OWNERS

This PR adds (Radim and Meer Sawood)  as Reviewers

Add QE Members As Reviewers 

---

OWNERS

add more QE as reviewers

---

test.sh

Fixing code coverage uploads on periodic job

fix : Code coverage not being uploaded in periodic job

---

src/components/AddComponent/AddComponentPage.tsx
src/components/AddComponent/SourceField.tsx
src/components/ComponentSamples/ComponentSamplesPage.tsx
src/components/CreateApplication/CreateApplicationPage.tsx
src/components/Page/Page.scss
src/components/Page/Page.tsx
src/components/ReviewComponents/ReviewComponentsForm.scss
src/components/ReviewComponents/ReviewComponentsForm.tsx
src/models/component.ts
src/shared/components/catalog/catalog.scss
src/shared/components/virtualized-grid/const.ts
src/utils/__tests__/devfile-utils.spec.ts
src/utils/create-utils.ts
src/utils/devfile-utils.ts

- https://issues.redhat.com/browse/HAC-462.
- Because of CORS issue in the devfile registry API, we were using mock data for devfile samples. https://github.com/devfile/api/issues/719 is fixed now. 
- Removed mock data and added logic to fetch devfile samples from real API.
- Updated some styles to match the UX designs accurately.
- Updated the model and usage of `ComponentDetectionQuery`.
https://user-images.githubusercontent.com/6041994/150354183-4673edbb-6bab-4159-9c2c-cc62841edaa6.mov

Update the devfile samples fetching and some css tweaks

---

OWNERS

Add Jai in OWNERS file

---

src/Routes.tsx
src/components/ComponentListView/ComponentListItem.scss
src/components/ComponentListView/ComponentListItem.tsx
src/components/ComponentListView/ComponentListView.tsx
src/components/ComponentListView/ComponentListViewPage.tsx
src/components/ComponentListView/__tests__/ComponentListViewPage.spec.tsx
src/components/CreateApplication/CreateApplicationPage.tsx
src/components/ReviewComponents/ReviewComponentsForm.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/types.ts
src/components/ReviewComponents/utils.ts
src/components/form-context.tsx
src/dynamic-plugin-sdk.ts
src/hooks/useActiveNamespace.ts
src/models/application.ts
src/models/component.ts
src/shared/components/status-box/StatusBox.tsx
src/types/application.ts
src/types/component.ts
src/types/index.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-464
Adds basic application view showing all components in an application.
Go through import flow form and create some components, page should get redirected to components list view.

Add basic application view list page

---

src/components/AddComponent/AddComponentForm.tsx
src/components/AddComponent/AddComponentPage.tsx
src/components/AddComponent/GitOptions.tsx
src/components/AddComponent/SourceField.tsx
src/components/AddComponent/__tests__/SourceField.spec.tsx
src/components/AddComponent/validation-utils.ts
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/ReviewSourceComponentCard.tsx
src/components/ReviewComponents/utils.ts
src/components/form-context.tsx
src/models/component.ts
src/types/component-detection-query.ts
src/types/index.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-438
Remove git source detection mock data and use ComponentDetectionQuery creation to detect components in git import flow.
Example repo with single comopnent: https://github.com/devfile-samples/devfile-sample-python-basic
Example repo with multiple components: https://github.com/maysunfaisal/multi-components

Replace component detection mock data with calls to ComponentDetectionQuery

---

src/components/AddComponent/GitOptions.tsx
src/components/AddComponent/SourceField.tsx
src/components/AddComponent/__tests__/SourceField.spec.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/ReviewSourceComponentCard.tsx

https://issues.redhat.com/browse/HAC-540
Update text and some layouts to align with UX designs.

Update text to align with UX designs

---

src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/__tests__/submit-utils.spec.ts
src/components/ReviewComponents/submit-utils.ts
src/components/form-context.tsx
src/dynamic-plugin-sdk.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-561
- Add dry run support to sdk
- Perform dry run of resource creation before actual creation.
https://user-images.githubusercontent.com/20013884/152528557-0e85ef16-df08-4687-88c8-f23198cc51f6.mp4
Try to add a resource with the same name as an existing resource.
Dry run check should prevent creating any other resources.

Dry run resource creation before actual creation

---

package-lock.json
package.json
src/Routes.tsx
src/components/AppFlow.tsx
src/components/ApplicationListView/ApplicationList.tsx
src/components/ComponentListView/ComponentListViewPage.tsx
src/components/ComponentListView/__tests__/ComponentListViewPage.spec.tsx
src/components/__tests__/AppFlow.spec.tsx
src/hooks/__tests__/useApplicationInfo.spec.ts
src/hooks/index.ts
src/hooks/useApplicationsInfo.ts

https://issues.redhat.com/browse/HAC-541
On app load 
- Show create application flow when no application exists in the workspace.
- Show application list view if one or more applications exist in the workspace.
added `@testing-library/react-hooks` for testing hooks
If no application exists then the user is shown with create application flow.
If application exists then the user is shown with an application list view if one or more applications exist in the workspace.
Applications can be deleted via CLI if exits for verification
```
oc delete applications --all
```

update landing page for user's based on application exists or not

---

package-lock.json
src/App.tsx
src/AppBanner.scss
src/AppBanner.tsx
src/__tests__/AppBanner.spec.tsx
src/__tests__/AppEntry.spec.tsx

Fixes: https://issues.redhat.com/browse/HAC-724
This PR adds a Development Preview Banner to AppStudio
https://user-images.githubusercontent.com/20724543/155292877-8207a8ca-bbb0-4c9a-84a0-8aac8c720062.mov

Add Dev Preview Banner

---

src/shared/components/close-button/CloseButton.tsx
src/shared/components/dropdown/BasicDropdown.tsx
src/shared/components/form-components/ActionGroupWithIcons.tsx
src/shared/components/form-components/FormFooter.tsx
src/shared/components/form-components/FormHeader.tsx
src/shared/components/form-components/PageBody.tsx
src/shared/components/form-components/__tests__/ActionGroupWithIcons.spec.tsx
src/shared/components/form-components/__tests__/FlexForm.spec.tsx
src/shared/components/form-components/__tests__/FormBody.spec.tsx
src/shared/components/form-components/__tests__/FormFooter.spec.tsx
src/shared/components/form-components/__tests__/FormHeader.spec.tsx
src/shared/components/form-components/__tests__/PageBody.spec.tsx
src/shared/components/formik-fields/BaseInputField.tsx
src/shared/components/formik-fields/EditableLabelField.tsx
src/shared/components/formik-fields/__tests__/BaseInputField.spec.tsx
src/shared/components/formik-fields/__tests__/CheckboxField.spec.tsx
src/shared/components/formik-fields/__tests__/DropdownField.spec.tsx
src/shared/components/formik-fields/__tests__/EditableLabelField.spec.tsx
src/shared/components/formik-fields/__tests__/ToggleableFieldBase.spec.tsx
src/shared/components/formik-fields/field-types.ts

https://issues.redhat.com/browse/HAC-397
This PR adds tests for form components added from console.
`npm test` to run all tests.

tests for form components

---

src/components/ComponentListView/ComponentListItem.tsx
src/components/ComponentListView/ComponentListViewPage.tsx
src/hooks/__data__/mock-data.ts
src/hooks/__tests__/useApplicationRoutes.spec.ts
src/hooks/useApplicationRoutes.ts
src/models/route.ts
src/types/component.ts
src/types/index.ts
src/types/routes.ts
src/utils/__tests__/route-utils.spec.ts
src/utils/route-utils.ts

- https://issues.redhat.com/browse/HAC-787
- Fetch routes and show route URL for each component in details page.
- Show built container image for each component in details page.
https://user-images.githubusercontent.com/6041994/157449351-ac260de5-57d1-42b5-8d65-a59a97b0afc0.mov

Show route and built container image for each component

---

build_deploy.sh
nginx.conf
pr_check.sh
test.sh

Add pr_check and build deploy scripts. Once this repository is onboarded to app-sre we will have automatic image releases enabled.

Add PR check and build deploy scripts

---

deploy.yaml

Added deploy

---

src/components/AddComponent/AddComponentForm.tsx
src/components/AddComponent/AddComponentPage.tsx
src/components/AddComponent/SourceField.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/ReviewSourceComponentCard.tsx
src/components/ReviewComponents/__tests__/submit-utils.spec.ts
src/components/ReviewComponents/submit-utils.ts
src/components/ReviewComponents/types.ts
src/components/form-context.tsx
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

- https://issues.redhat.com/browse/HAC-850
- Pass devfileUrl while creating component CR.

Fix builds for git repo without devfiles

---

deploy.yml

We are now building just the plugin, no need to have dpeloyment of regular CRC app.
Remove navigation element and module definition from deplyment config.

Use plugin deployment config

---

config/dev.webpack.config.js
config/prod.webpack.config.js
src/App.scss
src/components/AppFlow.tsx
src/components/ApplicationListView/ApplicationList.tsx
src/components/ComponentListView/ComponentListView.tsx
src/components/ComponentSamples/ComponentSamplesPage.tsx
src/components/SamplesFlow.tsx
src/pages/SamplePage/SamplePage.tsx
src/pages/TestK8s.tsx

After the hac-dev plugin conversion there was css issue with the layout. Fixed by adding global level styles for consistent layout.
Before --
https://user-images.githubusercontent.com/6041994/159716400-88f7fbea-9108-4d97-bf68-dbccda3be709.mov
After --
https://user-images.githubusercontent.com/6041994/159716426-334582fd-4f6f-4fc3-a3aa-65dc1b8a3cd8.mov

Fix CSS layout issue for all pages

---

src/components/ReviewComponents/submit-utils.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-559
- Send env data while creating component CR. 
No change in the UI.

Send Env data while creating components.

---

src/components/AddComponent/utils.ts

- https://issues.redhat.com/browse/HAC-1048
- The CDQ added a new `Processing` status in the resource. We need to stop looking for CDQ resource once the status is `Completed`.

Check for completed status in CDQ

---

config/remotePlugin.js
src/components/ApplicationDetailsView/ComponentListItem.tsx
src/components/ApplicationDetailsView/__tests__/ComponentListItem.spec.tsx
src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
src/components/ComponentSettingsForm/ComponentSettingsView.tsx
src/components/ComponentSettingsForm/__tests__/ComponentSettingsView.spec.tsx
src/components/ReviewComponents/ReviewComponentsForm.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/ReviewSourceComponentCard.tsx
src/components/ReviewComponents/__tests__/submit-utils.spec.ts
src/components/ReviewComponents/types.ts
src/components/ReviewComponents/utils.ts
src/pages/ComponentSettingsPage.tsx
src/shared/components/action-menu/ActionMenuItem.tsx
src/shared/components/button-bar/ErrorMessage.tsx
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

- https://issues.redhat.com/browse/HAC-1062
- Added a new edit form for editing component values.
- Updated the review component card and used it in the form.
https://user-images.githubusercontent.com/6041994/165109143-24d8b9d0-3d84-49bd-9be7-f82c7ed52199.mov

Add support for editing of component settings

---

src/components/AddComponent/AddComponentPage.tsx
src/components/AddComponent/SourceSection.tsx
src/components/AddComponent/__tests__/utils.spec.ts
src/components/AddComponent/utils.ts
src/components/CreateApplication/CreateApplicationPage.tsx
src/hooks/useActiveNamespace.ts

- https://issues.redhat.com/browse/HAC-1167
- The namespace was being set in namespaced context and initialised into form context in application create page. But if we add component to already created application this step would not happen and namespace would not be initialized.

Fix namespace not being initialised into form context

---

src/components/AddComponent/SourceSection.tsx
src/components/AddComponent/__tests__/utils.spec.ts
src/components/AddComponent/utils.ts
src/shared/hooks/useDebounceCallback.ts

https://issues.redhat.com/browse/HAC-1285
When git options are entered, the callback is triggered which sets the field to validating, but since git options aren't used by the detection hook a new CDQ is not created. This causes the field to never get validated.
Solution:
- Do not hide git options section if any value is changed.
- Pass git options to detection hook so it creates a new CDQ when they change, even though we don't use git options currently.
- Debounce the creation of CDQ in the hook so that it doesn't try to create a new CDQ on every keystroke.
https://user-images.githubusercontent.com/20013884/169376786-f7b0fc63-bcac-4680-adf4-9b461e865404.mp4
Try to update git options after a repo is entered.

Pass git options to component detection hook

---

integration-tests/package-lock.json
integration-tests/package.json
integration-tests/plugins/index.ts
integration-tests/support/commands/index.ts

into a file so we can see in detail what happens in CI runs

e2e tests: collect cypress logs

---

src/components/AddComponent/__tests__/utils.spec.ts
src/components/AddComponent/utils.ts
src/components/ComponentSettingsForm/ComponentSettingsView.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/submit-utils.ts
src/types/component.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-1325
- Update component create util to use new fields.
- Pass git context directory and reference to component & CDQ creation utils.
N/A

Use updated component fields from latest HAS changes

---

src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/__tests__/submit-utils.spec.ts
src/components/ReviewComponents/submit-utils.ts
src/types/component.ts
src/utils/create-utils.ts

- https://issues.redhat.com/browse/HAC-1322
- https://issues.redhat.com/browse/HAC-1420
- CDQ can now detect a dockerfile in a git repository and we can specify that in component CR to support dockerfile.
- Updated the component creation to use dockerfileUrl from the CDQ.
- Revert the changes that send context into component creation until the HAS issue is resolved.
- No UI change.

Update component creation to support dockerfile

---

.codecov.yml
src/components/ApplicationDetailsView/__tests__/ComponentListView.spec.tsx
src/hooks/__data__/mock-data.ts
src/hooks/__tests__/useApplicationRoutes.spec.ts
src/hooks/useApplicationRoutes.ts
src/utils/__tests__/route-utils.spec.ts
src/utils/route-utils.ts

- https://issues.redhat.com/browse/HAC-1326
- Updated the label to filter routes for specific components.
https://user-images.githubusercontent.com/6041994/170737486-07835ce4-0302-44c9-bd9a-b2f3947da8db.mov

Fix route filtering logic based on new labels from HAS

---

src/components/ApplicationDetailsView/ComponentListView.tsx
src/components/ApplicationDetailsView/__tests__/ComponentListView.spec.tsx
src/hooks/__data__/mock-data.ts
src/hooks/__tests__/useGitOpsDeploymentCR.spec.ts
src/hooks/useGitOpsDeploymentCR.ts
src/models/gitops-deployment.ts
src/types/gitops-deployment.ts
src/utils/gitops-utils.tsx

https://issues.redhat.com/browse/HAC-1436
Show GitOps Deployment Health Status on Application details page

show gitops deployment health status on Application details page

---

src/components/ApplicationListView/ApplicationListRow.tsx
src/components/ApplicationListView/application-actions.ts

https://issues.redhat.com/browse/HAC-1317
Add application delete modal.
https://user-images.githubusercontent.com/20013884/171449496-49d44d0d-4e80-4b8a-95de-044640c51805.mp4
Delete application from application list view.

Add application delete modal

---

integration-tests/.gitignore
integration-tests/cypress.json
integration-tests/package-lock.json
integration-tests/package.json
integration-tests/reporter-config.json
pr_check.sh

Add xunit reporter to e2e tests

---

src/shared/components/table/Table.scss
src/shared/components/table/Table.tsx

https://issues.redhat.com/browse/HAC-1529
The table's kebab menu had scroll overflow, and would cause table rows to get pushed upwards when opened.
https://user-images.githubusercontent.com/20013884/172821693-f81d367c-c6ae-4135-adfe-9844dd498a74.mp4
Navigate to applications list page and open the kebab menu of the last item.

Make table menu overflow visible

---

config/dev.webpack.config.js
src/components/AddComponent/AddComponentForm.tsx
src/components/AddComponent/AddComponentPage.tsx
src/components/AddComponent/GitAuthorization.tsx
src/components/AddComponent/SourceSection.tsx
src/components/AddComponent/__tests__/GitAuthorization.spec.tsx
src/components/AddComponent/__tests__/SourceSection.spec.tsx
src/components/AddComponent/__tests__/utils.spec.ts
src/components/AddComponent/utils.ts
src/components/AddComponent/validation-utils.ts
src/components/ApplicationDetailsView/ComponentListItem.tsx
src/components/NamespacedPage/NamespacedPage.tsx
src/components/ReviewComponents/ReviewComponentsForm.tsx
src/components/ReviewComponents/ReviewComponentsPage.tsx
src/components/ReviewComponents/submit-utils.ts
src/components/ReviewComponents/utils.ts
src/components/form-context.tsx
src/hooks/useOnMount.ts
src/models/service-provider-integration.ts
src/types/component.ts
src/types/service-provider-integration.ts
src/utils/create-utils.ts
src/utils/test-utils.tsx

https://issues.redhat.com/browse/HAC-1082
Support the new SPI oAuth APIs changes in UI

support new spi api for OAuth flow

---

integration-tests/support/pages/AddComponentPage.ts
integration-tests/tests/create-application-from-quay-image.spec.ts
integration-tests/utils/Common.ts

Add test for creating an app with a component from quay image.
See [doc](https://github.com/openshift/hac-dev/tree/main/integration-tests#run-tests) how to run tests.

Add test for app creating from quay image

---

src/components/ReviewComponents/ReviewSourceComponentCard.tsx
src/components/ReviewComponents/__tests__/validation-utils.spec.ts
src/components/ReviewComponents/validation-utils.ts
src/shared/components/formik-fields/NumberSpinnerField.tsx
src/shared/components/formik-fields/field-types.ts

https://issues.redhat.com/browse/HAC-1286
Avoid accepting negative values for form input.
https://user-images.githubusercontent.com/20013884/173111800-3d393b67-7709-43a9-ba68-77ac050a3ead.mp4

Avoid accepting negative values for form input

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pages/ApplicationDetailPage.ts
integration-tests/tests/create-application-from-git-source.spec.ts
integration-tests/tests/create-application-from-quay-image.spec.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/utils/Applications.ts
integration-tests/utils/Common.ts

Add test for app removal. Add that also for other tests to the *after* suite. Refactor common page objects.
Run tests as described in a readme.

Add the deletion of application to the tests.

---

src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
src/components/ComponentSettingsForm/ComponentSettingsView.tsx
src/components/ReviewComponents/ReviewComponentsForm.tsx
src/components/ReviewComponents/ReviewSourceComponentCard.tsx
src/components/ReviewComponents/__tests__/ReviewSourceComponentCard.spec.tsx

- https://issues.redhat.com/browse/HAC-1530

Fix component settings page for container image flow

---

src/components/ReviewComponents/ReviewComponentsForm.tsx

- https://issues.redhat.com/browse/HAC-1625
- Null check was needed in case of git flow where container image is undefined.

Fix review components page crash

---

package-lock.json
package.json

Fixes the build failure
Error: ENOENT: no such file or directory, open '/home/karthik/Git/hac-dev/node_modules/@redhat-cloud-services/frontend-components-config-utilities/repos/insights-chrome-build/snippets/index.html

Bump frontend-components-config to fix failing builds

---

jest.config.js

Temporarily disables test code coverage for the hacbs dir until we get a decent foundation put together.
N/A

temp remove coverage for hacbs

---

src/components/AddComponent/SourceSection.tsx
src/components/AddComponent/__tests__/SourceSection.spec.tsx

https://issues.redhat.com/browse/HAC-1612
CDQ for private repository failed when next is clicked quickly because the secret was not yet fetched in the previous page.
Solved by disabling next button until secret is fetched in case of private repos.
https://user-images.githubusercontent.com/20013884/175344862-72eebc55-e504-4158-bbe7-924e95192ea5.mp4
- Enter a private repo in source input page
- Click next/press enter as soon as url is validated

Validate private repository only after secret is fetched

---

integration-tests/support/pageObjects/createApplication-po.ts
src/components/ApplicationDetailsView/ComponentListItem.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx

- https://issues.redhat.com/browse/HAC-1949
https://user-images.githubusercontent.com/6041994/180198233-af13e8ff-87a5-429e-9155-c7b7a8dc9e84.mov

Fix disabled create button for container image with a tag

---

integration-tests/support/constants/PageTitle.ts
integration-tests/support/constants/Units.ts
integration-tests/support/pageObjects/global-po.ts
integration-tests/tests/create-application-from-git-source.spec.ts
integration-tests/tests/create-application-from-quay-image.spec.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/utils/Applications.ts
integration-tests/utils/Common.ts

also some lint errors resolved

Make use of side navigation in cypress tests

---

src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
src/components/ApplicationDetailsView/__tests__/ApplicationDetailsView.spec.tsx

- https://issues.redhat.com/browse/HAC-1403
- Added an error state to handle all application load errors.
https://user-images.githubusercontent.com/6041994/181743886-d377ba7a-f72f-4fad-ab90-97f63b967e9a.mov

Handle 404 error state in application details view

---

src/components/LogViewer/BuildLogViewer.tsx

https://issues.redhat.com/browse/HAC-1975
Rename build logs modal

rename build logs modal

---

config/remotePlugin.js
src/components/ImportForm/ImportForm.scss
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/components/ImportForm/utils/validation-utils.ts
src/hacbs/components/ImportForm/BuildSection.tsx
src/hacbs/components/ImportForm/ImportForm.tsx
src/hacbs/components/ImportForm/__tests__/BuildSection.spec.tsx
src/hacbs/components/ImportForm/__tests__/useImportSteps.spec.ts
src/hacbs/components/ImportForm/types.ts
src/hacbs/components/ImportForm/useImportSteps.tsx
src/hacbs/pages/ImportPage.tsx
src/pages/ImportPage.tsx
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

Fixes: https://issues.redhat.com/browse/HACBS-814
Customizes the import wizard for HACBS.
Constructs a new ImportForm component specifically for HACBS and re-uses the existing pages for application and component creation.
Adds a new Build page to the import wizard.
Outstanding issues:
- A pipeline is always created for a Component and therefore the state of the Build page will quickly change to "merged".
- `Cancel` button needs to be updated to `Go to application` after the application has been created. Requires an update to the Formik wizard.
- Going `Back` in the wizard doesn't make sense once the application and component has been created.

add HACBS build page to import wizard

---

src/components/ApplicationDetailsView/ComponentListItem.tsx
src/components/ApplicationDetailsView/__data__/mock-data.ts
src/components/ApplicationDetailsView/__tests__/ComponentListItem.spec.tsx
src/types/common-types.ts
src/types/component.ts
src/types/index.ts
src/utils/__tests__/common-utils.spec.ts
src/utils/common-utils.ts

https://issues.redhat.com/browse/HAC-504
Show Conditions status on UI after a component is created

show condition status on component list page

---

src/components/Environment/EnvironmentCard.tsx
src/components/Environment/__tests__/EnvironmentCard.spec.tsx

https://issues.redhat.com/browse/HAC-1968
Visual changes for Environment cards

change Environemnt cards visuals on settings page

---

src/hacbs/components/ImportForm/useImportSteps.tsx

https://issues.redhat.com/browse/HACBS-814
Updates the wizard navigation for hacbs now that formik-pf has been updated.
Disabled back button and cancel button goes to application:
Enabled back button (because the component has yet to be created) and cancel button goes to application:
Disabled back button and cancel button goes to application:
Enable hacbs using `hacbs=true` in the query string param and go to create a new application.

update hacbs wizard navigation

---

config/prod.webpack.config.js

Topology PF styling issues in staging/prod environment.

Fix PF topology styling in staging environment

---

jest.config.js
src/hacbs/components/ImportForm/__tests__/ImportForm.spec.tsx

HACBS code coverage was disabled originally but we have enough tests re-enable coverage.
Also added a test for a file that had 0 coverage.

enable code coverage for hacbs

---

src/hacbs/components/Modals/GettingStartedModal.tsx
src/hacbs/components/Modals/__tests__/GettingStartedModal.spec.tsx
src/hacbs/components/Modals/imgs/Enterprise-contract.svg
src/hacbs/components/Modals/imgs/Integration-test.svg
src/pages/ApplicationsPage.tsx

https://issues.redhat.com/browse/HACBS-817
> I reached out to Abi to help us update the grammar / spelling a bit, and here's what we'd like to correct, please:
> 
> * **From** should replace **form** in the first modal. Whole body text will then read: "Complete automation, from commit to application release, in a single click. Maximize your security with our off-the-shelf CI/CD solutions."
> * For the "How does it work" modal, we could change the heading to "How it works," or leave as-is and add a question mark: "How does it work?"
> * On the "Integration test" step, we're missing a comma after "Before attempting to release")
> * The button "Get Started" should be sentence case: "Get started"
> 
> Thank you! @Ranelim FYI
I updated. Please check the screenshots and approve

Getting started modal HACBS

---

src/hacbs/components/ImportForm/ImportForm.tsx
src/hacbs/components/ImportForm/IntegrationTestSection.tsx
src/hacbs/components/ImportForm/__tests__/useImportSteps.spec.ts
src/hacbs/components/ImportForm/submit-utils.ts
src/hacbs/components/ImportForm/types.ts
src/hacbs/components/ImportForm/useImportSteps.tsx
src/hacbs/components/ImportForm/utils/__tests__/submit-utils.spec.ts
src/hacbs/components/ImportForm/utils/validation-utils.ts
src/hacbs/models/hacbs.ts

https://issues.redhat.com/browse/HACBS-815
Contains Add Integration test scenario step
```
Create Utils
✓ Should call k8sCreateResource with integration test data (3 ms)
✓ Should contain the display name in the annotations (1 ms)
✓ Should contain kubernetes formatted resource name (1 ms)
```
This step can be found in Create Application wizard

Add Integration test step in App creation wizard

---

src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/hacbs/components/PipelineRunDetailsView/tabs/PipelineRunTaskRunsTab.tsx
src/hacbs/components/TaskRunListView/TaskRunListHeader.ts
src/hacbs/components/TaskRunListView/TaskRunListRow.tsx
src/hacbs/components/TaskRunListView/TaskRunListView.tsx
src/hacbs/components/TaskRunListView/__data__/mock-TaskRun-data.ts
src/hacbs/components/TaskRunListView/__tests__/TaskRunListRow.spec.tsx
src/hacbs/components/TaskRunListView/__tests__/TaskRunListView.spec.tsx
src/hacbs/types/taskRun.ts
src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx

Lists all task runs associated with the pipeline run for the Task runs tab of the pipeline run details page.
There are currently no actions per row or links out to task runs details pages.
Create an application and component.
Go to the application details PipelineRuns tab.
Click on a pipeline run name to go to the PLR details page.
Go to the Task runs tab.

add task runs list to pipelinerun details

---

src/hacbs/components/ImportForm/__tests__/useImportSteps.spec.ts
src/hacbs/components/ImportForm/useImportSteps.tsx

Remove the Environment creation step
Add Application:
Add Component:

Remove Environment step in app creation wizard

---

config/remotePlugin.js
src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
src/components/ApplicationDetailsView/ComponentDetails.tsx
src/components/ApplicationDetailsView/ComponentListView.tsx
src/components/ApplicationListView/ApplicationListView.tsx
src/components/ComponentSettingsForm/ComponentSettingsView.tsx
src/components/Environment/EnvironmentListView.tsx
src/components/Environment/create/CreateEnvironment.tsx
src/components/ImportForm/ImportForm.tsx
src/components/ImportForm/utils/auth-utils.ts
src/components/ImportForm/utils/cdq-utils.ts
src/components/NamespacedPage/NamespacedPage.tsx
src/components/NamespacedPage/__tests__/NamespacedPage.spec.tsx
src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
src/hacbs/components/ImportForm/BuildSection.tsx
src/hacbs/components/ImportForm/ImportForm.tsx
src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/hacbs/components/PipelineRunListView/PipelineRunsListView.tsx
src/hooks/index.ts
src/hooks/useEnvironments.ts
src/hooks/usePipelineRunsForApplication.ts
src/utils/namespace-context-utils.ts
src/utils/test-utils.tsx

https://issues.redhat.com/browse/HAC-1980
use context provider extension to get the namespace
No UI changes

use context provider for Namespace

---

src/components/Environment/EditStrategyModal.tsx
src/components/Environment/__tests__/EditStrategyModal.spec.tsx
src/components/Environment/environment-actions.ts

https://issues.redhat.com/browse/HAC-2004
Add modal to edit environment strategy.
https://user-images.githubusercontent.com/20013884/184175603-2481905b-33f4-4c9e-ab38-6a5f45cdd426.mp4

Add modal to edit environment strategy

---

src/components/Environment/EnvironmentListView.tsx
src/components/Environment/__tests__/EnvironmentListView.spec.tsx
src/pages/WorkspaceSettingsPage.tsx

https://issues.redhat.com/browse/HAC-1981
add Help topic for settings page

add help topic for settings page

---

src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/components/ImportForm/utils/useImportSteps.tsx
src/pages/ImportPage.tsx

- https://issues.redhat.com/browse/HAC-2003
- Add step level title, description and help links to import wizard.
https://user-images.githubusercontent.com/6041994/186869001-4fb4ed70-5486-4178-afd9-d2f23c27ce57.mov

Update import wizard with step level title, description and help links

---

src/components/Environment/ApplicationEnvironmentCards.tsx
src/components/Environment/EnvironmentListView.tsx
src/components/Environment/create/ParentEnvironmentField.tsx
src/hooks/useEnvironments.ts
src/shared/components/formik-fields/DropdownField.tsx
src/shared/components/formik-fields/__tests__/DropdownField.spec.tsx
src/shared/components/formik-fields/field-types.ts
src/types/environment.ts
src/utils/__tests__/environment-utils.spec.ts
src/utils/environment-utils.ts

https://issues.redhat.com/browse/HAC-1967
Sort Environments in promotion order

list Environments based on the promotion

---

src/hacbs/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx
src/hacbs/components/Commits/AppRecentCommits.tsx
src/hacbs/components/Commits/CommitsListHeader.tsx
src/hacbs/components/Commits/CommitsListRow.tsx
src/hacbs/components/Commits/CommitsListView.tsx
src/hacbs/components/Commits/__data__/pipeline-with-commits.ts
src/hacbs/components/Commits/__tests__/CommitsListRow.spec.tsx
src/hacbs/components/Commits/__tests__/CommitsListView.spec.tsx
src/hacbs/components/Commits/commit-actions.ts
src/hacbs/consts/pipelinerun.ts
src/hacbs/types/commit.ts
src/hacbs/types/index.ts
src/hacbs/types/pipelineRun.ts
src/hacbs/utils/__tests__/commits-utils.spec.ts
src/hacbs/utils/commits-utils.ts

https://issues.redhat.com/browse/HACBS-824
https://issues.redhat.com/browse/HACBS-819
Adds commits table in application commits tab and recent commits in overview tab. The table is populated with mock data as we don't have sufficient live data as of today.

HACBS Commits List

---

src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/utils/__tests__/cdq-utils.spec.ts
src/components/ImportForm/utils/cdq-utils.ts

https://issues.redhat.com/browse/HAC-1984
Set & return the CDQ only for the provided source.
https://user-images.githubusercontent.com/20013884/186921549-e7d26d25-a8f5-4f27-a2c4-5181bdfc9e15.mp4
Select sample multiple times in the sample selection page.

Set CDQ only for current source

---

src/components/Environment/environment-actions.ts

https://issues.redhat.com/browse/HAC-2022
Use display name when for prompting for confirmation in the environment delete modal.
https://user-images.githubusercontent.com/20013884/187502197-7c2f0c9e-7895-4762-a1f2-bee35017bd47.mp4
Delete an environment.

Use display name for environment delete modal

---

integration-tests/support/pages/CreateApplicationPage.ts
integration-tests/tests/create-application-from-git-source.spec.ts
integration-tests/tests/create-application-from-quay-image.spec.ts

e2e test fixes

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
src/components/ImportForm/utils/__tests__/useDevfileSamples.spec.ts
src/components/ImportForm/utils/cdq-utils.ts
src/components/ImportForm/utils/useDevfileSamples.tsx

- https://issues.redhat.com/browse/HAC-2048
- Updated the loading condition to show message when CDQ is not able to detect components.
- Added a common hook to fetch devfile samples which will be needed for runtime selection work.
https://user-images.githubusercontent.com/6041994/189358143-364a10cc-44bc-45ce-95fb-998886c31508.mov

Fix loading state when detection fails and create common devfile hook

---

integration-tests/tests/create-application-from-sample.spec.ts
src/components/ImportForm/SampleSection/SampleSection.tsx

- https://issues.redhat.com/browse/HAC-539
- Add application name to the samples component name to avoid name clashes.

Add app name in sample component to avoid name clash

---

config/remotePlugin.js
src/hacbs/components/Commits/CommitDetailsView.tsx
src/hacbs/components/Commits/__data__/pipeline-with-commits.ts
src/hacbs/components/Commits/tabs/CommitsPipelineRunTab.tsx
src/hacbs/components/Commits/tabs/__tests__/CommitsPipelineRunTab.spec.tsx

https://issues.redhat.com/browse/HACBS-828
Adds PipelineRun tab to commits details

Commit pipelinerun tab

---

src/components/ComponentsListView/ComponentListItem.tsx
src/components/ComponentsListView/__tests__/ComponentListItem.spec.tsx
src/components/Environment/EnvironmentListView.tsx
src/components/WorkspaceSettings/WorkspaceSettings.scss
src/components/WorkspaceSettings/WorkspaceSettings.tsx
src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
src/hacbs/components/EnterpriseContractView/EnterpriseContractView.scss
src/hacbs/components/EnterpriseContractView/EnterpriseContractView.tsx
src/hacbs/components/EnterpriseContractView/ReleasePolicyPackageItem.scss
src/hacbs/components/EnterpriseContractView/ReleasePolicyPackageItem.tsx
src/hacbs/components/EnterpriseContractView/__data__/mockECPolicy.ts
src/hacbs/components/EnterpriseContractView/__data__/mockEnterpriseContractPolicies.ts
src/hacbs/components/EnterpriseContractView/__tests__/EnterpriseContractView.spec.tsx
src/hacbs/components/EnterpriseContractView/const.ts
src/hacbs/components/EnterpriseContractView/types.ts
src/hacbs/components/EnterpriseContractView/useEnterpriseContractPolicies.tsx
src/hacbs/components/WorkspaceSettings/WorkspaceSettings.tsx
src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
src/pages/WorkspaceSettingsPage.tsx

Fixes [HACBS-1127](https://issues.redhat.com/browse/HACBS-1127)
Adds Enterprise Contract info to the settings page for HAC BS.
Updates to getting started info:
Package Info:
Expanded:
Github link:

Add HACBS Enterprise Contract settings

---

integration-tests/package-lock.json
integration-tests/package.json
integration-tests/plugins/index.ts
integration-tests/support/commands/a11y.ts
integration-tests/support/commands/index.ts
integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pages/AddComponentPage.ts
integration-tests/support/pages/ApplicationDetailPage.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/create-application-from-quay-image.spec.ts
integration-tests/tsconfig.json
integration-tests/utils/Applications.ts
integration-tests/utils/Common.ts
integration-tests/utils/Login.ts

test a11y on each page with cypress

Setup for accessibility testing

---

src/components/ImportForm/SourceSection/AuthOptions.tsx
src/components/ImportForm/SourceSection/AuthTokenModal.tsx
src/components/ImportForm/SourceSection/__tests__/AuthTokenModal.spec.tsx
src/components/ImportForm/utils/__tests__/auth-utils.spec.ts
src/components/ImportForm/utils/auth-utils.ts
src/types/service-provider-integration.ts

https://issues.redhat.com/browse/HAC-2209
Use `uploadUrl` for token upload flow instead of using a hardcoded URL.
https://user-images.githubusercontent.com/20013884/192510486-66c34ece-feb5-4438-b596-6a1bba6fd390.mp4
Use token upload flow.

Use uploadUrl for token upload flow

---

src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx

https://issues.redhat.com/browse/HAC-2212
Sanitize app prefix for sample name.
https://user-images.githubusercontent.com/20013884/192333268-c362a05a-4834-4525-8445-2273eaafad18.mp4
Create a sample app in an application with whitespace in it's name.

Sanitize app prefix for sample component name

---

src/hacbs/components/ApplicationDetails/ApplicationQuickstartContent.ts
src/hacbs/components/IntegrationTestForm/IntegrationTestForm.tsx
src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx
src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx
src/hacbs/components/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
src/hacbs/components/Modals/GettingStartedModal.tsx

Fixes [HACBS-1171](https://issues.redhat.com/browse/HACBS-1171)
Change all instances of `integration test pipeline` to `integration test` for consistency.
Bugfix

Change 'Integration test pipelines' to 'Integration tests' globally

---

src/hacbs/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunTaskRunsTab.spec.tsx
src/hacbs/components/TaskRunListView/TaskRunListView.tsx
src/hacbs/components/TaskRunListView/__data__/mock-TaskRun-data.ts
src/hacbs/components/TaskRunListView/__tests__/TaskRunListRow.spec.tsx
src/hacbs/components/TaskRunListView/__tests__/TaskRunListView.spec.tsx

https://issues.redhat.com/browse/HACBS-1170?
Adds filter for Task name to filter by metadata.name and spec.taskRef.name

Filter task run

---

src/components/Environment/create/CreateEnvironment.tsx
src/components/Environment/create/CreateEnvironmentForm.tsx
src/components/Environment/create/ParentEnvironmentField.tsx
src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
src/components/Environment/create/__tests__/ParentEnvironment.spec.tsx
src/components/Environment/environment-utils.ts

- https://issues.redhat.com/browse/HAC-1966
This PR updates the following things in the create environment form based on UX recommendation - 
- Removed the type dropdown and defaulted to non-poc type for now. This hard coded value will be removed once backend is updated.
- Updated the help text for deployment strategy field.
- Updated the label and help text for parent environment field.
- Updated the dropdown items in parent environment field to show the order of the environment.
https://user-images.githubusercontent.com/6041994/194394091-2ddd49de-0415-475e-956f-a9eaaa0d5558.mov

Update create environment form based on new design

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/create-application-from-git-source.spec.ts
integration-tests/tests/create-application-from-quay-image.spec.ts
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
src/components/ImportForm/utils/types.ts
src/components/ImportForm/utils/useDevfileSamples.tsx
src/components/ImportForm/utils/validation-utils.ts

https://issues.redhat.com/browse/HAC-1605
Add a runtime selector to components review section. That uses the devfile sample API to fetch list of runtimes.
- Allows selecting a runtime when CDQ detection fails to detect one automatically.
- Allows optionally selecting a different runtime if the automatic detection is not satisfactory.
https://user-images.githubusercontent.com/20013884/194301862-e7d82b9a-322c-42bd-9bed-66efb0c39dd2.mp4
https://user-images.githubusercontent.com/20013884/194301877-931bcb0b-c21c-4aa2-aac4-1adae2c22801.mp4
Use a non-detectable repo, or try to change the runtime after detection has happened.

Add component runtime selector

---

src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx

Add loading indicator for component detection in samples flow

add loading indicator for component detection

---

src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
src/components/ApplicationDetailsView/ComponentCard.tsx
src/components/ApplicationDetailsView/__tests__/ComponentCard.spec.tsx
src/components/Environment/ApplicationEnvironmentCards.tsx
src/components/Environment/EnvironmentListView.tsx
src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx
src/hacbs/components/ApplicationDetails/tabs/EnvironmentsTab.tsx
src/hacbs/components/Environment/EnvironmentCard.tsx
src/hacbs/components/Environment/EnvironmentListView.tsx
src/hacbs/components/Environment/EnvironmentToolbarGroups.tsx
src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
src/hooks/useApplicationEnvironmentsWithHealthStatus.ts
src/hooks/useApplicationHealthStatus.ts
src/hooks/useLastApplicationDeployTime.ts

Fixes [HACBS-831](https://issues.redhat.com/browse/HACBS-831)
Update HACBS environment cards in the application details, environments tab per the UX story [DTUX-1232](https://issues.redhat.com/browse/DTUX-1232)

Update application environment tab cards and filters

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pages/AddComponentPage.ts
integration-tests/tests/create-application-from-private-git-source.spec.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts
pr_check.sh

This PR serves for testing a new test for private repo.

Test private GH repo

---

integration-tests/support/pages/AddComponentPage.ts
integration-tests/tests/create-application-from-private-quay-image.spec.ts
integration-tests/tests/create-application-from-public-quay-image.spec.ts
pr_check.sh

Add test for private quay.io repo.

Add test for private quay.io repo

---

src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/hacbs/components/PipelineRunListView/PipelineRunListRow.tsx
src/hacbs/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx
src/hacbs/components/PipelineRunListView/pipelinerun-actions.tsx

Fixes https://issues.redhat.com/browse/HACBS-990
Stop and delete commands added. Rerun is still TBD.
Go to the pipelinerun list page, select the kabob on a particular pipelinerun row and select Stop (to cancel a running PLR) or Delete (to bring up a modal and eventually delete the PLR).

Pipelinerun actions

---

src/hacbs/components/Commits/CommitDetailsView.tsx
src/hacbs/components/Commits/CommitSidePanel.tsx
src/hacbs/components/Commits/CommitSidePanelBody.tsx
src/hacbs/components/Commits/CommitSidePanelHeader.tsx
src/hacbs/components/Commits/__data__/pipeline-with-commits.ts
src/hacbs/components/Commits/__tests__/CommitSidePanelBody.spec.tsx
src/hacbs/components/Commits/__tests__/CommitSidePanelHeader.spec.tsx
src/hacbs/components/Commits/tabs/CommitsOverviewTab.tsx
src/hacbs/consts/pipelinerun.ts
src/hacbs/utils/__tests__/commits-utils.spec.ts
src/hacbs/utils/commits-utils.ts
src/shared/components/pipeline-run-logs/StatusIcon.tsx
src/shared/components/pipeline-run-logs/utils.ts

https://issues.redhat.com/browse/HACBS-1136
Adds status and task side panel to commit details
Added unit tests for commit-utils, CommitSidePanelHeader, CommitSidePanelbody

Commit-status-and-panel

---

README.md
config/dev.webpack.config.js
package.json
src/utils/namespace-context-utils.ts

- https://issues.redhat.com/browse/HAC-2197
This PR 
- Adds a custom proxy for KCP.
- Adds a new npm script to run for KCP.
- Fixes the namespace selection utility when running on KCP.
No UI change.
- Setup KCP locally.
- Follow the KCP onboarding guide or the App Studio quick start guide for KCP.

Update webpack proxy and fix namespace issue for KCP

---

integration-tests/README.md
integration-tests/docker/Dockerfile
pr_check.sh

Add our own Dockerfile and run tests with our own image. 
Now, the image has also `oc` and `which` installed.
The image is updated and pushed manually.

Add our own dockerfile

---

src/components/ApplicationDetailsView/ApplicationDetailsView.tsx
src/components/ApplicationDetailsView/ApplicationSwitcher.tsx
src/components/ApplicationDetailsView/__tests__/ApplicationDetailsView.spec.tsx
src/components/ContextSwitcher/ContextSwitcher.scss
src/components/ContextSwitcher/ContextSwitcher.spec.tsx
src/components/ContextSwitcher/ContextSwitcher.tsx
src/components/ContextSwitcher/context-switcher-utils.tsx
src/components/ContextSwitcher/index.ts
src/components/PageLayout/PageLayout.tsx
src/shared/components/breadcrumbs/BreadCrumbs.tsx

https://issues.redhat.com/browse/HAC-2309
- Create a generic ContextSwitcher component for workspaces and applications
- Use ContextSwitcher to implement application switcher in applications list page
https://user-images.githubusercontent.com/20013884/199749526-151cfcc8-2550-48c5-bc39-e8a4cc02256f.mp4
Click on context switcher next to application name breadcrumb.

Add ContextSwitcher component

---

src/hacbs/components/IntegrationTestForm/IntegrationTestForm.tsx
src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx
src/hacbs/components/IntegrationTestsListView/IntegrationTestsListView.tsx

https://issues.redhat.com/browse/HACBS-1169
Remove learn more link and alert as per the latest UX design doc in the integration test pages.
**Add Integration in wizard:**
**Add Integration Page:**
**Integration List page:**
Visit Integration creation/list pages.

Remove learn more link in integration test pages

---

integration-tests/support/pageObjects/hacbs-po.ts
integration-tests/support/pages/hacbs/AddIntegrationTestPage.ts
integration-tests/support/pages/hacbs/ComponentsTabPage.ts
integration-tests/support/pages/hacbs/tabs/ComponentsTabPage.ts
integration-tests/support/pages/hacbs/tabs/IntegrationTestsTabPage.ts
integration-tests/support/pages/hacbs/tabs/OverviewTabPage.ts
integration-tests/tests/hacbs/add-component-to-application-via-hacbs-tab.spec.ts
integration-tests/utils/Common.ts
integration-tests/utils/HACBSApplications.ts
src/hacbs/components/IntegrationTestsListView/useIntegrationTestActions.tsx

https://issues.redhat.com/browse/HACBS-1450
Also addresses the https://github.com/openshift/hac-dev/pull/250#issuecomment-1309358912
Captured video of this automation: [Link](https://drive.google.com/file/d/17V7zI0IfzOX7P2CfEwB0v4sb0PUQGdJy/view?usp=sharing).
(If you're in a hurry, watch the video from 3:27 onwards to see the main changes related to the PR).

HACBS UI Test: Integration Tests details and list view

---

src/hacbs/components/ApplicationDetails/ApplicationQuickstartContent.ts
src/hacbs/components/ApplicationDetails/DetailsPage.tsx
src/hacbs/components/ApplicationDetails/HacbsApplicationDetails.tsx

https://issues.redhat.com/browse/HACBS-1168
Following doc -> https://docs.google.com/document/d/1MkPSzk-pwzXeKT2oWrYUu87XYNtWlGkzhfnWPzBuRuI/edit#heading=h.2dz13zkk5prj
Enhances Application actions

Enhance application action

---

config/remotePlugin.js
src/hacbs/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppReleaseNodes.ts
src/hacbs/components/ImportForm/create-utils.ts
src/hacbs/components/ImportForm/utils/__tests__/create-utils.spec.ts
src/hacbs/components/ImportForm/utils/submit-utils.ts
src/hacbs/components/ImportForm/utils/validation-utils.ts
src/hacbs/components/IntegrationTest/IntegrationTestDetailsView.tsx
src/hacbs/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx
src/hacbs/components/IntegrationTestForm/IntegrationTestForm.tsx
src/hacbs/components/IntegrationTestForm/IntegrationTestSection.tsx
src/hacbs/components/IntegrationTestForm/IntegrationTestView.tsx
src/hacbs/components/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/hacbs/components/IntegrationTestsListView/useIntegrationTestActions.tsx
src/hacbs/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/hacbs/pages/EditIntegrationTestPage.tsx

https://issues.redhat.com/browse/HACBS-1172
Adds support to edit integration test scenarios.
Enables the `Edit` action on the details page.
Updated copy for Add integration test scenario form which is used in both the wizard and stand alone add page. 
The `Integration test name` input is marked as read only and cannot be edited.
The `Save changes` button only gets enabled if the edit form has changes.
empty state if the URL points to an invalid integration test scenario name:
Add integration test scenario:
Add integration test scenario in wizard:
Add integration test scenario standalone page:
Invalid name error:
Add integration test scenario through wizard.
Add integration test scenario from application details page action menu.
Edit integration test scenario from its details page action …

edit integration test scenario

---

src/components/ApplicationListView/ApplicationListHeader.ts
src/components/ApplicationListView/ApplicationListRow.tsx
src/components/ApplicationListView/__tests__/ApplicationListView.spec.tsx

https://issues.redhat.com/browse/HAC-2538
Removes the environment column from the application list view.
**Before:**
**After:**
large screen:
Small screen:
Create an application and visit application list view.
cc: @Ranelim @MariaLeonova @christianvogt @rohitkrai03

remove environments column from application list view

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
src/components/Components/BuildStatusColumn.tsx
src/components/Components/ComponentListView.tsx
src/components/Components/__data__/mock-data.ts
src/components/Components/__tests__/BuildStatusColumn.spec.tsx

https://issues.redhat.com/browse/HAC-2540
Use the HACBS application details page by default.
Do not show merge PR link if component does not have PAC annotation.
https://user-images.githubusercontent.com/20013884/208122408-a26cadfc-35ff-4384-9ce8-137d1d201c95.mp4

Update application details page

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/DetailsPage.tsx
src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx

https://issues.redhat.com/browse/HAC-2623
add application deployment status to details page

add application deployment status to details page

---

src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts

https://issues.redhat.com/browse/HAC-2645
PipelineRun visualization alignment is fixed in this PR.
**Before:** 
After:

Fix pipelinerun graph alignment

---

src/components/ApplicationDetails/ApplicationDetails.tsx

- https://issues.redhat.com/browse/HAC-2594
- Removed redundant action items from application details page.

Remove redundant action menu items from application details

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/shared/components/links/ExternalLink.tsx

- https://issues.redhat.com/browse/HAC-2383
- Updated font weight for source URL in review component card.

Updated font weight style for review component card link

---

src/components/modal/DeleteResourceModal.tsx
src/components/modal/resource-modals.tsx

- https://issues.redhat.com/browse/HAC-2365
- https://issues.redhat.com/browse/HAC-2364
- https://issues.redhat.com/browse/HAC-2363
- https://issues.redhat.com/browse/HAC-2358
- https://issues.redhat.com/browse/HAC-2359
- https://issues.redhat.com/browse/HAC-2360
- Updated delete application modal texts based on UX recommendation.
- Updated delete component modal texts based on UX recommendation.
https://user-images.githubusercontent.com/6041994/209315998-cbe2aa92-dc5f-45a8-8c65-32e635975a03.mov

Update delete resource modal texts

---

src/components/ComponentSettingsForm/ComponentSettingsForm.tsx

https://issues.redhat.com/browse/HAC-2336
Adds breadcrumbs for component name.

add breadcrumb for component

---

OWNERS

add @karthikjeeyar to OWNERS as an approver

add karthik to OWNERS as an approver

---

src/components/ImportForm/SampleSection/SampleInfoAlert.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx

https://issues.redhat.com/browse/HAC-2782
https://user-images.githubusercontent.com/9964343/211596192-71377400-b22c-470c-b103-d7402aa42956.mov
```
SourceSection
✓ should render the samples info alert (7 ms)
✓ should not render the samples info alert (6 ms)
```
1. Use Create application flow or Add component flow

Add sample info alert to visually highlight start with samples flow

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts

https://issues.redhat.com/browse/HAC-2788
Hide integration test tab and component, application test nodes from lifecycle and commit visualization.
Application lifecycle graph:
expanded graph:
Commit graph:
```
ApplicationDetails
✓ should not display integration test tab if the mvp flag is set to true (59 ms)
```  
```
useCommitWorkflowData hook
✓ should return commit nodes without integration tests, releases and managed environments when mvp flag is true (2 ms)
```    
```
useAppWorkflowData hook
✓ should return workflow nodes without integration tests, releases and managed environments when mvp flag is true (1 ms)
```
1. Visit Application details page and commit visualization page.

Hide integration tests tab, nodes in the graph for mvp

---

src/hacbs/components/Environment/EnvironmentListView.tsx
src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx

https://issues.redhat.com/browse/HAC-2791
Updates text for Environment subtitle

update Environment subtitle copy

---

src/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx
src/components/Components/ComponentListView.tsx

- https://issues.redhat.com/browse/HAC-2813
- https://issues.redhat.com/browse/HAC-2814
- Remove learn more links from app overview and component tab.
https://user-images.githubusercontent.com/6041994/211860718-8c9a79fc-bce8-4963-83b2-3879a5d510fb.mov

Remove learn more link from app overview and components tab

---

src/components/ImportForm/ImportForm.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx
src/components/ImportForm/utils/__tests__/cdq-utils.spec.ts
src/components/ImportForm/utils/__tests__/submit-utils.spec.ts
src/components/ImportForm/utils/__tests__/transform-utils.spec.ts
src/components/ImportForm/utils/__tests__/useImportSteps.spec.ts
src/components/ImportForm/utils/cdq-utils.ts
src/components/ImportForm/utils/submit-utils.ts
src/components/ImportForm/utils/transform-utils.ts
src/components/ImportForm/utils/types.ts
src/components/ImportForm/utils/useImportSteps.tsx
src/components/ImportForm/utils/validation-utils.ts
src/types/component-detection-query.ts

https://issues.redhat.com/browse/HAC-2697
Run detection for samples after submit.
https://user-images.githubusercontent.com/20013884/211789561-3f59936f-25c3-4784-b8cf-ba8baedc04b6.mp4
Add sample components.

Run detection for samples after submit

---

src/components/Components/BuildStatusColumn.tsx

https://issues.redhat.com/browse/HAC-2868
The merge pull request link goes to a page that shows all PRs whether they are open or closed.
This can result in many entries that are irrelevant to the user at the time. They only need to see the open PRs.
**Before**:
**After:**
**Recording:**
https://user-images.githubusercontent.com/9964343/212000912-b85de3bf-3627-43da-833e-7a6dff0a40a8.mov
1. Add a component with Send pull request flow
2. You can see the Merge build PR link in the components details page.  (Tip: Incase if the default build pipelineruns starts immediately then this Option will not be visible, to test you can delete the running build pipelinerun to view this option)

View pull request link should redirect to open pull requests page

---

src/components/PipelineRunDetailsView/RelatedPipelineRuns.tsx
src/components/PipelineRunDetailsView/visualization/utils/__tests__/RelatedPipelineRuns.spec.tsx

https://issues.redhat.com/browse/HAC-2839
Related pipelineruns should be fetched based on the PAC sha label and it should use different labels to fetch the build and test pipelineruns. The PAC labels are modified in the test pipeline run in-order to avoid conflict with PAC detecting test pipelineruns as PAC pipelineruns.
1 . Now using the below labels to find the related pipelineruns:
build pipelinerun: 
```
pipelinesascode.tekton.dev/sha=a6186ee9992eb6afb4e831372a0d7c0e780e921e 
```
test pipelinerun:
```
pac.test.appstudio.openshift.io/sha=a6186ee9992eb6afb4e831372a0d7c0e780e921e 
```
Also I have added link to the related pipelinerun so that users can navigate between the related pipelineruns
Popover with link to navigate between related pipelines: …

Fix related pipelineruns field and add links to the related pipelineruns

---

integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
integration-tests/tests/add-component-to-application.spec.ts

Integration test Tab Edit test scenarios.
https://issues.redhat.com/browse/HACBS-1462
Reach the "Edit integration test" page by:
1. Go to an IT's Details page and click on the "Edit integration test" option under the "Actions" dropdown.
2. Go to IT list view, and click on the "Edit" option under IT's kebab menu.
Then test the Edit form by making sure that:
- `Integration test name` input is marked as read-only and cannot be edited.
- `Save changes` button only gets enabled if the edit form has new changes.
- update the `pipelineName` and `Mark Optional For Release` 
- Verify that the latest changes are reflected on the IT list and detail view.

Integration test Tab Edit test scenarios.

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx

https://issues.redhat.com/browse/HAC-2624
Update detecting components message.
https://user-images.githubusercontent.com/20013884/212109157-8d33d4f8-1f02-4998-bbfc-8126f6041f4a.mp4
Add components.

Update review section loading message

---

src/components/Environment/EnvironmentListView.tsx
src/components/Environment/__tests__/EnvironmentListView.spec.tsx
src/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx
src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx
src/hacbs/components/WorkspaceSettings/__tests__/WorkspaceSettings.spec.tsx

https://issues.redhat.com/browse/HAC-2790
Removes filter from Environment details view.

remove filter from Environments view

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx

https://issues.redhat.com/browse/HAC-2933
Removes the option to change the `route`.
Right now the option doesn't function as expected. The decision was made to remove this option altogether for now.
wizard:
settings form:

remove route option from component settings

---

integration-tests/support/pages/AddComponentPage.ts
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx

https://issues.redhat.com/browse/HAC-2784
Updates text for SourceSection validation

update validation text

---

integration-tests/config/hac-dev-default.json
pr_check.sh

Differents fixes to be able to have green PR check again.
As the environment was not ready for quite some time, we must clean and polish our tests to run well there now. This is what this PR is serving for.

Fix tests.

---

integration-tests/support/pages/AddComponentPage.ts
integration-tests/support/pages/AddIntegrationTestPage.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/CreateApplicationPage.ts
integration-tests/support/pages/CreateBuildPage.ts
integration-tests/utils/Applications.ts
package-lock.json
package.json

- https://issues.redhat.com/browse/HAC-2227
- Upgrade formik-pf to latest version which fixes the double submit issue.
- Update the e2e test.

Upgrade formik-pf to fix submit errors and fix e2e tests

---

src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-2959
Deleting environment variables from UI was not reflecting in the components CR.
https://user-images.githubusercontent.com/9964343/213451990-367c5587-13fb-4e97-bbe4-5fbcf01e6457.mov
```
Create Utils
✓ Should delete the environment variables while updating (1 ms)
✓ Should update the environment variables with new values (1 ms)
```
1. While creating components, Add environment variables under advanced deployment options 
2. Go to component setting page from component list view and remove all the environment variables under advanced options.

fix environment variables deletion while updating a component

---

src/components/ComponentSettingsForm/ComponentSettingsView.tsx

- https://issues.redhat.com/browse/HAC-2973
- Update the redirect URL to land in components tab from components settings page.
https://user-images.githubusercontent.com/6041994/213674168-39439792-6b45-418d-9ee9-5540e8b82e90.mov

Redirect components tab from component settings page

---

src/components/ImportForm/SampleSection/SampleInfoAlert.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx

- https://issues.redhat.com/browse/HAC-2969
- Update copy for forking samples based on UX recommendation.

Update the instructions to fork samples

---

src/components/Commits/CommitDetailsView.tsx
src/components/Commits/CommitsListRow.tsx
src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/shared/components/pipeline-run-logs/StatusIcon.tsx

https://issues.redhat.com/browse/HAC-2952
There is no icon present for the status of the commit in the commit list view:
**Before:**
**After:**

Add status icon to the commit list status column

---

src/components/Components/ComponentListView.tsx

https://issues.redhat.com/browse/HAC-2999
remove the self-reference of "Stonesoup" as this is an internal project name. 
**Before:**
**After:**

remove Stonesoup referenece from component description

---

src/shared/components/pipeline-run-logs/StatusIcon.tsx

https://issues.redhat.com/browse/HAC-3023
Cancelling status is breaking into two lines.
https://user-images.githubusercontent.com/9964343/214356297-170ac82d-d3f1-4b51-b7dc-01bd9974d29f.mov
1. Cancel a running pipeline to see the Cancelling status.

Fix cancelling status alignment

---

src/components/Commits/CommitsListView.tsx
src/components/Commits/__data__/pipeline-with-commits.ts
src/components/Commits/__tests__/CommitsListRow.spec.tsx
src/components/Commits/__tests__/CommitsListView.spec.tsx
src/utils/__tests__/commits-utils.spec.ts
src/utils/commits-utils.ts

https://issues.redhat.com/browse/HAC-2997
https://issues.redhat.com/browse/HAC-3010
1. "Filter by name"  filter performs a case sensitive search in the commit list view name field rather it should perform case insensitive search.
~2. The name field should display a valid PR number (eg: `#4`) , previously it was showing `# undefined`  string.~ (fixed already in another PR, so reverted the change)
**Filter by name:** 
https://user-images.githubusercontent.com/9964343/214000314-2c0e3524-9609-4957-84f5-eaa2512f81f7.mov
https://user-images.githubusercontent.com/9964343/214000375-e3d9b094-77a3-424e-ae14-ef18981dae2b.mov

remove case sensitive filters in the commit list view

---

helpers/resources/component.yaml
helpers/setup.sh
src/components/ApplicationDetails/tabs/overview/sections/__data__/WorkflowComponentsData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
src/components/Components/BuildStatusColumn.tsx
src/components/Components/ComponentListView.tsx
src/components/Components/__data__/mock-data.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

Related issue: [PLNSRVCE-959](https://issues.redhat.com/browse/PLNSRVCE-959)
Update build related annotations used on AppStudio Component.
Related PR into Build Service is [here](https://github.com/redhat-appstudio/build-service/pull/103).
- Build related changes

Update AppStudio Component build annotations

---

src/components/ApplicationDetails/ApplicationDetails.tsx

https://issues.redhat.com/browse/HAC-2934
Clicking Explore documentation links in the Actions menu gives 404. Removed link until we have a proper documentation link.

remove explore documentation link from action dropdown in application details view

---

integration-tests/config/hac-dev-default.json
integration-tests/config/hac-dev-experimental.json

https://issues.redhat.com/browse/HAC-3020
Merged hac-dev test reports into the appstudio-qe report portal
Updated the reportPortal endpoints in config file.

Merged hac-dev test reports into the appstudio-qe report portal

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/DetailsPage.tsx
src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
src/components/Commits/CommitDetailsView.tsx
src/components/HeadTitle.tsx
src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/IntegrationTest/IntegrationTestDetailsView.tsx
src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/pages/ApplicationDetailsPage.tsx
src/pages/ApplicationsPage.tsx
src/pages/CommitsPage.tsx
src/pages/ComponentSettingsPage.tsx
src/pages/ImportPage.tsx
src/pages/IntegrationTestDetailsPage.tsx
src/pages/PipelineRunPage.tsx

https://issues.redhat.com/browse/HAC-2702
updates page title based on the view.

change browser tab title based on different views

---

src/components/PipelineRunListView/PipelineRunListHeader.ts
src/components/PipelineRunListView/PipelineRunListRow.tsx
src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx

https://issues.redhat.com/browse/HAC-2916

add component column to pipelinerun list

---

src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SampleSection/__tests__/SampleSection.spec.tsx

https://issues.redhat.com/browse/HAC-2905
Samples page filter should match tags as well
```
SampleSection
✓ should filter sample items based on tags (45 ms)
```

modify sample page filter to match the results based on tags

---

src/components/ApplicationListView/ApplicationListRow.tsx
src/components/ApplicationListView/__tests__/ApplicationListRow.spec.tsx

https://issues.redhat.com/browse/HAC-2207
The `Last deploy` column of the application list view renders the application's `creationTimestamp` as the value. This is misleading as it does not represent the last deploy timestamp.
**Solution:**
Using snapshotEnvironmentBinding cr's `.status.componentDeploymentConditions[0].lastTransitionTime` value to fetch the latest deployed time, however this is not a guaranteed/accurate at the moment so we have a backend ticket to improve the accuracy of the lastDeployed time https://issues.redhat.com/browse/GITOPSRVCE-375 till then we can use the `lastTransitionTime` to get the timestamp.
---
Check the last deployed timestamp in the application list view and environment list view.
```
Application List Row
✓ should render the last deployed environment …
```

fix last deploy time in application list view

---

package-lock.json
package.json
src/utils/create-utils.ts

- https://issues.redhat.com/browse/HAC-1268
- Start using uuid instead of pseudo random generator for unique names.
No UI change.

Use uuid for generating unique names

---

src/components/PipelineRunListView/PipelineRunListRow.tsx
src/components/PipelineRunListView/PipelineRunsListView.tsx
src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx

https://issues.redhat.com/browse/HAC-2789
Adds status and name filter to PLR list
yet to update tests

add filter to Pipeline run list

---

src/components/Commits/CommitDetailsView.scss
src/components/Commits/CommitDetailsView.tsx
src/components/Commits/CommitIcon.scss
src/components/Commits/CommitIcon.tsx
src/components/Commits/CommitsListRow.scss
src/components/Commits/CommitsListRow.tsx
src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/consts/pipelinerun.ts
src/types/commit.ts
src/utils/__tests__/commits-utils.spec.ts
src/utils/commits-utils.ts

https://issues.redhat.com/browse/HAC-2938
update commit details view information

Update commit information on CommitDetailsView

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

- https://issues.redhat.com/browse/HAC-3084
- Fix the build node link of app visualisation to go to correct pipelineruns link.
https://user-images.githubusercontent.com/6041994/216334250-b162c401-064a-4ce0-beeb-82203a8f71a8.mov

Fix build node link to go to pipelineruns tab

---

src/components/Components/ComponentListView.tsx
src/hacbs/components/Environment/EnvironmentListView.tsx
src/hacbs/components/Environment/__tests__/EnvironmentListView.spec.tsx

- https://issues.redhat.com/browse/HAC-3015
- Updated descriptions for component and environments tab in application details page.

Update component and environment descriptions in details page

---

src/components/ApplicationDetails/ApplicationDetails.tsx

- https://issues.redhat.com/browse/HAC-2913
- Hide quick start action from application details page for MVP.
- Remove no standard separators and section titles.
https://user-images.githubusercontent.com/6041994/216299979-52ef32f2-2ccb-48cf-a7c3-91f3bf9508ec.mov

Hide create application quickstart action for mvp

---

src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
src/components/PipelineRunListView/pipelinerun-actions.tsx

https://issues.redhat.com/browse/HAC-3091
Remove pipeline rerun action from pipeline run list view.
Visit pipelinerun list view and details view.

remove pipeline rerun action from list view

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/node-utils.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

https://issues.redhat.com/browse/HAC-2972
On importing multiple samples simultaneously, PR needs merge status is showing briefly on the build node popover in the lifecycle visualization.
Before fix:
After fix:
Create multiple samples from samples flow, and go to the overview page and hover on the build node.
```
getBuildNodeForComponent
✓ should return pending status if the build has not started yet for the simple pipeline flow (2 ms)
✓ should return PR needs merge status only for the componentes with advanced pipeline flow
```    
cc: @jeff-phillips-18

PR needs merge status should not be shown for simple pipeline flow

---

integration-tests/config/hac-dev-default.json
integration-tests/support/pages/tabs/OverviewTabPage.ts
integration-tests/tests/create-application-from-private-git-form.spec.ts
integration-tests/utils/Tokens.ts
pr_check.sh

Enable private git tests again

---

integration-tests/plugins/index.ts
pr_check.sh

Fixes: https://issues.redhat.com/browse/HAC-3082
Enhanced the Report Portal description with PR number, title and link

Enhanced Report Portal description

---

src/components/ImportForm/SourceSection/SourceSection.tsx

Fixes [HAC-3039](https://issues.redhat.com/browse/HAC-3039)
Updates the description text for the Add components step for application creation.

Revise import flow add component description

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/component-actions.tsx
src/components/Components/ComponentListItem.tsx
src/components/Components/__tests__/ComponentListItem.spec.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/utils/component-utils.ts

https://issues.redhat.com/browse/HAC-2684
https://issues.redhat.com/browse/HAC-3049
https://issues.redhat.com/browse/HAC-2690
- addresses additional UX changes
- updated copy
- fix `Start new build` action which lost the annotation encoding for the patch request
- add status message to Customize pipeline modal

ux updates to customize pipelines related actions

---

src/components/Commits/CommitDetailsView.tsx
src/components/Commits/__tests__/CommitDetailsView.spec.tsx
src/components/Commits/tabs/CommitsOverviewTab.tsx

https://issues.redhat.com/browse/HAC-2937
- Removes Getting started modal
- Removes Learn more link

remove commit getting started modal

---

src/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx

- https://issues.redhat.com/browse/HAC-3124
- Update the help topic ids in whats next section based on changes in https://github.com/RedHatInsights/quickstarts/pull/58.
No UI change.

Update the help toppic ids for whats next section

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

- https://issues.redhat.com/browse/HAC-2914
- Updated build node description in lifecycle visualization.

Update build node description in lifecycle visualization

---

integration-tests/support/pageObjects/createApplication-po.ts
src/components/ApplicationDetails/component-actions.tsx
src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.tsx
src/components/Components/__tests__/ComponentListItem.spec.tsx
src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/modal/DeleteResourceModal.tsx

https://issues.redhat.com/browse/HAC-2838
1. Updates "Name your application"
2. Remove "?"
3. Updates "Read more" -> "show more" -- portion is removed
4. Delete Application Modal: Change the label to "Type [application name] to confirm deletion:" 
5. App Overview tab > Lifecycle visualization: The "View in tab" links on Components and Static environments popovers should be more descriptive. ex. "View Components" "View Environments"
6. Components tab: Change "Component settings" in action menu to "Edit component settings"

update screen copies

---

integration-tests/plugins/index.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/create-application-from-private-git-form.spec.ts

fix UI tests getting 404 because the application name sometimes gets mixed up with pre-generated value

Fix e2e test instability

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/WorkspaceSettings/WorkspaceSettings.tsx

https://issues.redhat.com/browse/HAC-3101
https://issues.redhat.com/browse/HAC-2904
Updated learn more links in import wizard to point to the updated docs: 
https://github.com/RedHatInsights/quickstarts/blob/main/docs/help-topics/stonesoup-import/stonesoup-import.yml
Note: the reference doc is pending updates to fix the formatting and wording. Also one of the help links won't show up until the fixes are in and deployed.
- add a new component
- on each of the import wizard pages there is a learn more link

update import learn more links

---

integration-tests/tests/create-application-from-private-git-form.spec.ts
integration-tests/utils/Common.ts

https://issues.redhat.com/browse/HAC-3169
Force tests to wait until navitems are loaded

e2e tests: wait for navigation to load before clicking

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/DetailsPage.tsx
src/components/ApplicationDetails/WorkspaceSwitcher.tsx
src/components/ContextSwitcher/ContextSwitcher.scss
src/components/ContextSwitcher/ContextSwitcher.tsx
src/components/ContextSwitcher/context-switcher-utils.tsx
src/components/PageLayout/PageLayout.tsx
src/shared/components/breadcrumbs/BreadCrumbs.tsx

https://issues.redhat.com/browse/HAC-2747
- Add workspace switcher using the ContextSwitcher component.
- Update ContextSwitcher component to support recursive menu items
- Update breadcrumb to support custom components
https://user-images.githubusercontent.com/20013884/216656542-c1b39f26-629a-4338-b42f-45e724a11c9a.mp4

Add workspace switcher

---

integration-tests/support/pages/ApplicationDetailPage.ts
integration-tests/tests/basic-happy-path.spec.ts
pr_check.sh

newest version of chrome doesn't work with ephemeral environment, try an older one

Run pr check with a partiular chrome image

---

src/components/ImportForm/SourceSection/SourceSection.tsx
src/shared/components/formik-fields/BaseInputField.scss
src/shared/components/formik-fields/BaseInputField.tsx

https://issues.redhat.com/browse/HAC-2342
https://issues.redhat.com/browse/HAC-2340
https://issues.redhat.com/browse/HAC-2347
Width on text input spans across window. Input field should be set to a maximum width of 750px
**Integration test page:**
**Small screen:**
**Import page:**

reduce input field length in all the forms

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx

https://issues.redhat.com/browse/HAC-2998

remove selectable from component settings card

---

src/hooks/useStoneSoupGitHubApp.ts

Fixes:
https://issues.redhat.com/browse/HAC-3251
Update production Github App link https://github.com/apps/red-hat-appstudio-ci-cd  for custom build setup.

udpate production Github app link for custom build flow

---

package-lock.json
package.json
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx

Fixes [HAC-3137](https://issues.redhat.com/browse/HAC-3137)
Check the URL using `git-parse-url` to determine if the accessible git URL has an `organization`
/cc @rohitkrai03 @christianvogt

Add gitUrlParse check for valid source repo URL

---

src/components/PipelineRunDetailsView/MetadataList.tsx

https://issues.redhat.com/browse/HAC-2920
setting max-width for metadatDataList labels and text-overflow elipsis

max width out metadata list

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/__tests__/ApplicationDetails.spec.tsx
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppWorkflowData.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useCommitWorkflowData.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppWorkflowData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useCommitWorkflowData.ts

- https://issues.redhat.com/browse/HAC-3273
- Remove MVP flag from integration tests tab and nodes in graph.
https://user-images.githubusercontent.com/6041994/222459839-c29a9f0c-dc5d-49e9-860a-0c3a035c0835.mov

Bring back integration tests tab and nodes in visualization

---

src/components/Components/ComponentListItem.tsx
src/components/Components/__tests__/ComponentListItem.spec.tsx

- https://issues.redhat.com/browse/HAC-3318
- Show download SBOM command in the components list page.
https://user-images.githubusercontent.com/6041994/223459240-4c4cb9d4-761b-492d-ab9d-4ddbb5446b04.mov

Show command to download SBOM in component list page

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx

https://issues.redhat.com/browse/HAC-3046
change detecting components text

change "detecting components" loading text

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/visualization-utils.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/utils/visualization-utils.ts

Fixes [HAC-3416](https://issues.redhat.com/browse/HAC-3416)
Fix crash in commit visualization due to incorrectly set node type
/cc @karthikjeeyar

Fix for Commit Visualization error

---

src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
src/components/topology/const.ts
src/components/topology/factories/VisualizationFactory.tsx

https://issues.redhat.com/browse/HAC-3290
Vertical and horizontal scrollers should not be shown for a pipeline with single task. Add a min height for the graph to avoid the scrollers.
**Before**:
**After**:
cc: @MariaLeonova

remove vertical scroll from the  pipeline run graph

---

src/components/Commits/CommitsListHeader.tsx
src/components/PipelineRunListView/PipelineRunListHeader.ts
src/components/TaskRunListView/TaskRunListHeader.ts
src/shared/components/table/Table.scss

https://issues.redhat.com/browse/HAC-2991
- Allow some columns to wrap at any char when content doesn't fit in cell
- Restrict kebab cell width for small screen sizes
**Before:**
https://user-images.githubusercontent.com/20013884/223377169-5b13ba99-2f06-4fca-a5c0-4a8f588ab926.mp4
https://user-images.githubusercontent.com/20013884/223377208-a2b0c4a4-1018-4568-bdeb-fb03456a8077.mp4
https://user-images.githubusercontent.com/20013884/223377222-e2831d34-2d5b-4eea-9d89-51ae6e4f2d1b.mp4
**After:**
https://user-images.githubusercontent.com/20013884/223377326-33b79b0a-58c9-4491-8543-176aee3f001e.mp4
https://user-images.githubusercontent.com/20013884/223377361-067287ee-f714-46eb-ae2a-7db1af357031.mp4
https://user-images.githubusercontent.com/20013884/223377375-2acc7fa9-0090-4b36-9d5d-9489ab809a77.mp …

Align table columns of list views

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/tests/advanced-happy-path.spec.ts
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/utils/useDevfileSamples.tsx
src/utils/__data__/mock-devfile-data.ts
src/utils/__tests__/__snapshots__/devfile-utils.spec.ts.snap
src/utils/__tests__/devfile-utils.spec.ts
src/utils/devfile-utils.ts

https://issues.redhat.com/browse/DEVHAS-239
Updates the samples to override names and descriptions. Also filters the `.Net` sample out.
View samples catalog.

update samples metadata with new names and descriptions

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
src/components/ImportForm/ReviewSection/__tests__/RuntimeSelector.spec.tsx
src/components/ImportForm/utils/types.ts

https://issues.redhat.com/browse/HAC-3347
https://issues.redhat.com/browse/HAC-3351
https://issues.redhat.com/browse/HAC-3372
In runtime selector, add `Dockerfile`option instead of `Other`
https://user-images.githubusercontent.com/9964343/223156485-343cb0f1-1a01-41b4-961a-27641e8e267c.mp4
1. Add a repository and in the review step, you can see new Dockerfile option.

add `Dockerfile` option instead of `Other` in runtime selector

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
src/consts/pipelinerun.ts

- https://issues.redhat.com/browse/HAC-3425
- Added a new section to show download SBOM command in pipeline run details page.
https://user-images.githubusercontent.com/6041994/224770077-d2f4d508-23b8-4f1b-8669-27825cd21e65.mov

Show download SBOM command in pipeline run details page

---

integration-tests/Dockerfile

Update dockerfile for tests

---

src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/test-pipeline-data.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__tests__/useAppIntegrationTestNodes.spec.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppIntegrationTestNodes.ts

https://issues.redhat.com/browse/HAC-3484
Integration test nodes should use the latest test pipeline run status in the lifecycle visualization.
1. Add a failing integration test - https://quay.io/repository/redhat-appstudio/example-tekton-bundle?tab=tags&tag=integration-pipeline-fail.
2.  start a new build and wait for the build and test pipeline to complete
3. Then edit the integration pipeline to `integration-pipeline-pass`
4. start a new build again and wait for the build and test pipeline to complete
5. lifecycle visualization should show the latest succeeded pipeline status.
```
useAppApplicationTestNodes
✓ should return integration test nodes (35 ms)
✓ should return failed status (9 ms)
✓ should return status from latest pipelinerun (10 ms)
```

use latest test pipelinerun status in lifecycle visualization

---

src/components/ImportForm/utils/__tests__/validation-utils.spec.ts
src/components/ImportForm/utils/validation-utils.ts

https://issues.redhat.com/browse/HAC-3150
Better validation messaging around app name
Updates to "Must start with a letter and end with a letter or number. Valid characters include lowercase letters from a to z, numbers from 0 to 9, and hyphens ( - )."

update application name validation message

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx

https://issues.redhat.com/browse/HAC-2341
Adds accessible text visually hidden using class = 'pf-u-screen-reader'

make learn more links accesible

---

integration-tests/tsconfig.json

Update e2e tsconfig `cypress-grep` to  `@cypress/grep`

Update e2e tsconfig

---

src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNode.tsx

https://issues.redhat.com/browse/HAC-3505
To avoid default Pending status value, I have added a check to perform status mapping only if the status is set.
Before:
After:
/cc @jeff-phillips-18

remove pending status from component nodes

---

src/hooks/useStoneSoupGitHubApp.ts

- https://issues.redhat.com/browse/HAC-3506
- The GitHub apps were updated to reflect new product name.
- Updated the github app links.
NO UI change.

Update github app links to latest ones

---

integration-tests/cypress.config.ts
integration-tests/package-lock.json
integration-tests/package.json
pr_check.sh

wait for cypress agent to finish before shutting down

Fix report portal reports

---

integration-tests/cypress.config.ts
integration-tests/support/commands/hooks.ts

periodic test run login

---

src/components/ApplicationListView/ApplicationListView.tsx

- https://issues.redhat.com/browse/HAC-3274
- Updated the application description in list page.

Update the application description in list page

---

src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx
src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx

- https://issues.redhat.com/browse/HAC-3423
- Update the empty state description of integration tests based on new design recommendation.

Update integration test empty state based on new design

---

integration-tests/Dockerfile
pr_check.sh

permission tweaks to the dockerfile

Update cypress runner image for openshift-ci

---

src/utils/__tests__/component-utils.spec.ts
src/utils/component-utils.ts

https://issues.redhat.com/browse/HAC-3417
While the `.git` suffix is allowed for all sorts of git operations including URL links, the Component git URL is parsed to create the filter for the link that tells the user to merge the PR in github.
For example, the Component git url `https://github.com/christianvogt/devfile-sample-java-springboot-basic.git` is parsed to create the PR link `https://github.com/pulls?q=is:pr+is:open+author:app/rh-trusted-application-pipeline+repo:christianvogt/devfile-sample-java-springboot-basic.git`. However this is invalid because of the `.git` suffix. The correct url is: `https://github.com/pulls?q=is:pr+is:open+author:app/rh-trusted-application-pipeline+repo:christianvogt/devfile-sample-java-springboot-basic`
No visual UI change.
Create a new component with …

remove .git suffix from pr filter

---

src/components/ContextSwitcher/ContextSwitcher.scss

- https://issues.redhat.com/browse/HAC-3103
- Added a minimum height to context switcher content area.
https://user-images.githubusercontent.com/6041994/226937482-962a1eee-2de8-4c1d-88db-52077e716d63.mov

Add a minimum height to context switcher content area

---

src/hooks/useStoneSoupGitHubApp.ts

Related to rebranding: https://issues.redhat.com/browse/PLNSRVCE-1171
As part of the brand update, the prod github app was republished to url: https://github.com/apps/red-hat-trusted-app-pipeline
Customize a build pipeline.
Ensure that the install github app link goes to a valid page.
After installing the app and sending a PR.
Ensure the `merge in github` link is a valid filter in github for the sent PR.

update prod github app url

---

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx

- https://issues.redhat.com/browse/HAC-3100
- Add icon to dropdown toggle when runtime is selected.
- Also use the icon prop to show spinner when runtime detection is happening.
https://user-images.githubusercontent.com/6041994/226909358-0b302b81-6f74-4927-8c56-d09a549b59fd.mov

Fix icon not showing up for selected item in runtime selector

---

src/components/Commits/CommitDetailsView.tsx
src/components/Commits/tabs/__tests__/CommitsPipelineRunTab.spec.tsx
src/hooks/useCommitPipelineruns.ts

https://issues.redhat.com/browse/HAC-3535
commit pipeline runs tab should include Test pipeline runs as well.
**Before:**
**After:**
1. Add integration test and add a new commit in the repository.

Add test pipelineruns in commit pipeline runs tab

---

src/shared/components/pipeline-run-logs/logs/Logs.tsx

https://issues.redhat.com/browse/HAC-3247
Re-instate websocket support for streaming logs.
Start a pipeline build.
Navigate to the PLR details page.
Select a task node, preferably the `build-container` node.
In the side bar, select `Logs` tab.
Observe logs streaming in.

re-instate websockets for logs

---

integration-tests/Dockerfile

cypress removed it from the base image :shrug:

Add curl to test runner

---

src/components/PipelineRunDetailsView/tabs/ClairScanDescriptionListGroup.tsx

As per UX.
Removed the title from the `Vulnerabilities scan` popover for consistency.
Visit the pipeline details page.

remove title from popover for consistency

---

integration-tests/support/pages/ComponentsPage.ts

Work around for issue : [HAC-3585](https://issues.redhat.com//browse/HAC-3585) to reduce test flakiness
Wait for Runtime to enable before editing the component name
issue : https://issues.redhat.com/browse/HAC-3585

Wait for Component Runtime to enable.

---

integration-tests/tests/basic-happy-path.spec.ts
src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/component-actions.tsx
src/components/Components/ComponentListItem.tsx
src/components/Components/ComponentListView.tsx
src/components/Components/ComponentPACStateLabel.tsx
src/components/Components/ComponentsFilterToolbarGroups.tsx
src/components/Components/__tests__/ComponentListView.spec.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/CustomizedPipeline/__tests__/CustomizeComponentPipeline.spec.tsx
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx

Manage builds model and label updates as per
Updated all pipeline build status labels with new content and tooltips.
Added `Roll back to default pipeline` kebab menu item to manage build pipelines.
Update microcopy for modal.
Note: Updated close button to secondary variant but did not produce new screenshots.
removed `Merge build PR` filter:
Put component into various states of upgrading to custom build pipelines.

update UI for manage builds modal and labels

---

src/components/TaskRunDetailsView/tabs/TaskRunDetailsTab.tsx
src/components/TaskRunDetailsView/tabs/__tests__/TaskRunDetailsTab.spec.tsx
src/components/TaskRunListView/__data__/mock-TaskRun-data.ts

https://issues.redhat.com/browse/HAC-3369
Add description and task results to task run details page.
Visit the task run details page.
Note that not all tasks will have a description or results.

add description and results to task run details

---

.husky/pre-commit
lint-staged.config.js
package-lock.json
package.json

Use `lint-staged` with pre-commit hook.
Runs commands only on files part of the commit instead of the entire code repo.
Runs the following commands:
- `prettier --write`: this will update code formatting for all committed files
- `eslint`: reports any lint failures
Failures will continue to prevent the commit from being added.

add lint-staged to speed up commits

---

OWNERS

Get assigned automatically to a lot of hac-dev PRs where I'm not involved. Unsure if this helps, but I removed myself from the reviewers list...

Remove myself as a reviewer

---

src/components/CustomizedPipeline/CustomizePipelines.tsx

Removes the table row border when an info alert is displayed for the sample component:
before:
after:
Create a new component from a sample.
From the Components tab, select the kebab for the sample component and choose `Manage build pipeline`

remove border in table rows of a sample component in the manage build pipelines modal

---

src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

- https://issues.redhat.com/browse/STONEBUGS-76
- Fix the link to integration test details page in integration tests node.
https://user-images.githubusercontent.com/6041994/228892243-b7bb4478-aa7e-436b-8f98-e20bc5ec3135.mov

Fix the link on integration test node in lifecycle visualization

---

src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-3623
Add annotation `image.redhat.com/generate: 'true'` to the Component creation.
No UI change.
Create a new component in the UI. Inspect the yaml.
While the annotation value begins as `true`, the controller will update the value to `false` and add a new annotation named `image.redhat.com/image`.

include annotation for component creation to new quay repo

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx

https://issues.redhat.com/browse/HACDOCS-342
Add help text to the dockerfile path field and update the label from `Docker file path` => `Dockerfile path`.

add help text to dockerfile path field

---

package-lock.json
package.json
src/components/Components/ComponentListItem.tsx
src/components/Components/__tests__/ComponentListItem.spec.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/GitLink/GitRepoLink.tsx
src/components/GitLink/__tests__/GitRepoLink.spec.tsx
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/shared/components/links/ExternalLink.tsx
src/utils/__tests__/git-utils.spec.tsx
src/utils/git-utils.tsx

https://issues.redhat.com/browse/HAC-3580
Update all UI where we render git repo URLs.

UI treatment for displaying Application repositories

---

src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/validation-utils.spec.ts
src/components/IntegrationTest/IntegrationTestForm/utils/validation-utils.ts

https://issues.redhat.com/browse/STONEBUGS-66
Correct validation message for integration test name which is allowed to start with a number.
Create an integration test and enter various names.

update integration test name validation message

---

integration-tests/cypress.config.ts
integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
integration-tests/tests/create-application-from-private-git-form.spec.ts
integration-tests/tests/create-application-from-private-git-source.spec.ts

https://issues.redhat.com/browse/HAC-3682
1) Update Advance e2e flow as per the recent UI changes on commit Details
2) Add GH_USERNAME to cypress config

e2e test: Update Commit details UI changes

---

src/components/ApplicationDetails/__data__/WorkflowTestPipelinesData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/useAppApplicationTestNodes.ts
src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.scss
src/components/ApplicationDetails/tabs/overview/visualization/nodes/WorkflowNodeTipContent.tsx
src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts
src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractRow.spec.tsx
src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx
src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContractView/types.ts
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
src/components/EnterpriseContractView/utils.ts
src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/components/TaskRunDetailsView/TaskRunDetailsView.tsx

https://issues.redhat.com/browse/HAC-3424
add Enterprise contract result under security tab in pipeline runs
[TODO]:
- []  ~Update the label to identify the Enterprise contract pipeline run (https://github.com/openshift/hac-dev/pull/530/files#diff-9eaec787536555e3f629da6787ae72f774c60541223c569ec9a582d6067e0222R71)~
Created issue https://issues.redhat.com/browse/HAC-3644 to update the label once https://github.com/redhat-appstudio/build-definitions/pull/369 gets merged
Task Run Security Tab

add table view for the enterprise contract results

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/shared/components/formik-fields/BaseInputField.tsx
src/shared/components/formik-fields/InputField.tsx

https://issues.redhat.com/browse/STONEBUGS-92
use html input attributes `min` and `max` to limit the port number input values
no visual change
edit the target port of a component using built in input arrows:

limit port input value

---

src/shared/components/action-menu/ActionMenuToggle.tsx
src/shared/components/action-menu/__tests__/ActionMenu.spec.tsx

https://issues.redhat.com/browse/STONEBUGS-95
Clicking on kebab button also ran the click event handler for outside button click, so the toggle would be changed to false before the actual toggle handler was run, this caused the toggle handler to update from an incorrect state.
https://user-images.githubusercontent.com/20013884/229834266-887f5674-9c50-47ad-a09d-d284bdab335d.mp4
Toggle any kebab menu.

Avoid toggling menu open state on outside menu click handler

---

integration-tests/cypress.config.ts
pr_check.sh

https://issues.redhat.com/browse/HAC-3684
Added Option to run all e2e test suite on pr check

Added Option to run all e2e test suite on pr check

---

src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
src/components/Modals/GettingStartedModal.tsx
src/hacbs/components/WorkspaceSettings/WorkspaceSettings.tsx

https://issues.redhat.com/browse/HAC-3640
consistent capitalization (in-app) of "Enterprise Contract"

consistent capitalization (in-app) of "Enterprise Contract"

---

src/components/EnterpriseContractView/utils.ts

https://issues.redhat.com/browse/HAC-3644
update the label that is used to identify the enterprise contract pipelinerun

update label to identify enterprise-contract pipeline run

---

src/components/PipelineRunDetailsView/tabs/ClairScanDescriptionListGroup.tsx

https://issues.redhat.com/browse/HAC-3719
add clair scan documentation link

add clair scan documentation link in popover

---

package-lock.json
package.json
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

Fixes [RHTAPBUGS-31](https://issues.redhat.com/browse/RHTAPBUGS-31)
When determining node width, use the displayed label on the node not just the resource name.
/cc @karthikjeeyar

Fix width of visualization nodes based on labels

---

src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx

https://issues.redhat.com/browse/HAC-3696
typo fixes

fix typo in enterprise contract security tab

---

src/components/Components/ComponentListItem.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/GitLink/GitRepoLink.tsx
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/utils/__tests__/git-utils.spec.tsx
src/utils/git-utils.tsx

https://issues.redhat.com/browse/RHTAPBUGS-127
Updated the rendering of the git repo links related to a component to include the revision and context.
If the revision is `main` or `master`, we will omit this from the link text to reduce visual clutter.
Furthermore, if you do not specify a revision at component creation time, then the Component resource will not include a  revision; it could be `main` or it could be `master`. Therefore we are unable to make direct links to the repository context directory and therefore will link, as done before, will go to the repository root.

update component git repo links to include revision and context

---

package-lock.json
package.json
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
src/components/Environment/create/CreateEnvironment.tsx
src/components/Environment/create/CreateEnvironmentForm.tsx
src/components/Environment/create/KubeconfigUploadField.tsx
src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
src/components/Environment/create/__tests__/KubeconfigUploadField.spec.tsx
src/components/Environment/environment-utils.ts
src/models/index.ts
src/models/secret.ts
src/shared/components/formik-fields/FileUploadField.tsx
src/types/environment.ts
src/types/index.ts
src/types/secret.ts

https://issues.redhat.com/browse/HAC-3599
Update create environment form to add support for updated fields.
https://user-images.githubusercontent.com/20013884/230921744-c940cc2c-5642-4b47-88ba-310155de6cd8.mp4
Navigate to create env form.

Update create environment form

---

integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/utils/Applications.ts

https://issues.redhat.com/browse/HAC-3705
Test Case: Integration Pipeline run Validation

e2e: Integration tests pipeline runs details validation test

---

integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts

https://issues.redhat.com/browse/HAC-3184
https://issues.redhat.com/browse/HAC-3779
1. e2e:Update resolved issue tests case
2. Update e2e test to repo with 2 components with GH reference and Context Dir validation

e2e: test Update with GH reference and context dir validation

---

integration-tests/cypress.config.ts
integration-tests/package-lock.json
integration-tests/package.json
integration-tests/support/commands/index.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts

https://issues.redhat.com/browse/HAC-3778
mochawesome html report for e2e tests

mochawesome html report for e2e tests

---

integration-tests/support/constants/PageTitle.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/utils/Applications.ts
src/components/ApplicationDetails/DetailsPage.tsx
src/components/ApplicationDetails/__tests__/DetailsPage.spec.tsx
src/components/ImportForm/ApplicationSection/ApplicationSection.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/Overview/IntroBanner.tsx
src/consts/labels.ts
src/pages/ApplicationsPage.tsx
src/pages/ComponentSettingsPage.tsx
src/pages/EnvironmentsListPage.tsx
src/pages/OverviewPage.tsx

https://issues.redhat.com/browse/RHCLOUD-25402
See slack discussion here: https://redhat-internal.slack.com/archives/C038DJAP7HR/p1681913902784649
Follow up to https://github.com/openshift/hac-dev/pull/367 - renames `CI/CD` to `Red Hat Trusted Application Pipeline`. 
There is a PR open in app-interface to update the nav title to `Trusted Application Pipeline`: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/65408

RHCLOUD-25402: Update CI/CD to Red Hat Trusted Application Pipeline

---

Caddyfile

Broken requests for hac-dev on console.dev.redhat.com environment.

Enable TLS in caddy file

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
src/components/topology/__data__/pipeline-test-data.ts
src/utils/pipeline-utils.ts

https://issues.redhat.com/browse/HAC-3788
- Add `View SBOM` link that navigates to the show-sbom taskrun logs of a pipelinerun
- Add a link to cosign install instructions below the download SBOM command
https://user-images.githubusercontent.com/20013884/234289489-2a484a87-2f07-4eaf-aa04-54eb3c8fe8d2.mp4

Add view sbom link in pipelinerun details page

---

src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts

https://issues.redhat.com/browse/RHTAPBUGS-196
In BYOC flow, even after a successful deployment to remote cluster, the UI still show 'Missing' application status in the Self Managed environment card.
**Before:**
**After:**
1. Create an environment with a remote cluster's kubeconfig file with token ([use this format](https://gist.github.com/jgwest/b084cdff007d7c0433edb28b6a4e6bcc#file-create-managed-env-secret-sh-L159)  )
2. Add component and navigate to applications -> environment tab.

Fix managed environment health status in environment card

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pages/ApplicationDetailPage.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/create-application-from-private-git-form.spec.ts
integration-tests/tests/create-application-from-private-git-source.spec.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/utils/Applications.ts

https://issues.redhat.com/browse/HAC-3803
Validate View Pod log on Components Page.

e2e: View pod log test case

---

src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractTable.tsx
src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractRow.spec.tsx
src/components/EnterpriseContractView/EnterpriseContractTable/__tests__/EnterpriseContractTable.spec.tsx
src/components/EnterpriseContractView/SecurityEnterpriseContractTab.scss
src/components/EnterpriseContractView/SecurityEnterpriseContractTab.tsx
src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
src/components/EnterpriseContractView/__tests__/SecurityEnterpriseContractTab.spec.tsx
src/components/EnterpriseContractView/types.ts
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
src/components/EnterpriseContractView/utils.ts
src/components/EnterpriseContractView/utils.tsx

https://issues.redhat.com/browse/HAC-3760
https://issues.redhat.com/browse/RHTAPBUGS-172
**Click area for expand icon**

enterprise contract enhancements

---

src/components/ApplicationDetails/__data__/WorkflowTestPipelinesData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/test-pipeline-data.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
src/components/CustomizedPipeline/pr.yaml
src/components/EnterpriseContractView/__data__/mockEnterpriseContractPolicies.ts
src/components/PipelineRunDetailsView/__data__/mockVisualizationData.ts
src/components/PipelineRunDetailsView/__tests__/PipelineVisualization.spec.tsx
src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts
src/components/topology/__data__/pipeline-test-data.ts
src/utils/pipeline-utils.ts

https://issues.redhat.com/browse/HAC-3820
Use `TEST_OUTPUT` for getting taskrun & status visualizations along with `HACBS_TEST_OUTPUT`.
Replace any occurences of `HACBS_TEST_OUTPUT` in tests.

Use TEST_OUTPUT task definition for task result status

---

src/components/Components/ComponentListItem.tsx
src/components/Components/ComponentListView.tsx

- https://issues.redhat.com/browse/RHTAPBUGS-181 
- Add null checks for gitops deployment resources.

Fix breaking component list page

---

src/components/ApplicationDetails/tabs/overview/visualization/nodes/__tests__/WorkflowNodeTipContent.spec.tsx
src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-26
Add filter to link data for PIpelineRun node.
https://user-images.githubusercontent.com/20013884/235201161-8766e534-5273-48dd-9c8c-141c8fee4a5e.mp4

Add filter to pipelinerun link data

---

pact-tests/application-creation.pact.spec.ts

Fix the contract, it was containing two headers.

Fix headers in contract tests

---

src/components/ComponentSettingsForm/ComponentSettingsView.tsx

https://issues.redhat.com/browse/RHTAPBUGS-222
The `Save` button is immediately disabled when a change is made.
https://user-images.githubusercontent.com/9964343/236508671-90b302b0-4559-4652-b708-60c8aaff178a.mov
Steps to reproduce:
1. create an application and new component
2. go to the Application details page for the new component
3. go to the Components tab
4. use the kebab menu for the component and select `Edit component settings`
5. edit any field in the form

fix edit component flow

---

src/components/ImportForm/ImportForm.tsx
src/components/ImportForm/__tests__/ImportForm.spec.tsx
src/pages/ImportPage.tsx
src/pages/__tests__/ImportPage.spec.tsx

- https://issues.redhat.com/browse/HAC-3875
- Update the title, description and help topics when user goes from source to review section.
https://user-images.githubusercontent.com/6041994/236403594-a392f2ee-b6b8-4083-93da-4b60e056ff0e.mov

Update the title, description and help topics when in review mode

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/Environment/create/CreateEnvironmentForm.tsx
src/components/Environment/create/__tests__/CreateEnvironment.spec.tsx
src/components/Environment/environment-utils.ts

Fixes [RHTAPBUGS-189](https://issues.redhat.com/browse/RHTAPBUGS-189)
Updates the text for the create environment form based on designs.
Fix link to create environment from the application actions menu.
/cc @rohitkrai03 @karthikjeeyar

Fixe create environment screen text

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
src/components/ImportForm/utils/__data__/mock-cdq.ts
src/components/ImportForm/utils/__tests__/transform-utils.spec.ts
src/components/ImportForm/utils/transform-utils.ts
src/components/ImportForm/utils/types.ts

Fixes [RHTAPBUGS-140](https://issues.redhat.com/browse/RHTAPBUGS-140)
Adds message text when target port cannot be detected.
/cc @karthikjeeyar @rohitkrai03 @misjohns

Inform user when target port is not detected

---

src/components/ApplicationListView/ApplicationListHeader.ts
src/components/Commits/CommitsListHeader.tsx
src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListHeader.ts
src/components/PipelineRunListView/PipelineRunListHeader.ts
src/components/TaskRunListView/TaskRunListHeader.ts
src/components/TaskRunListView/TaskRunListRow.tsx
src/shared/components/table/Table.scss
src/shared/components/table/Table.tsx

Fixes [RHTAPBUGS-206](https://issues.redhat.com/browse/RHTAPBUGS-206)
Fixes the column alignment for list view caused by the kebab column. PF table removes padding for cells with no content.
Use a space for content for the action header cell and add padding to equal the width of the kebab button.
/cc @christianvogt @karthikjeeyar

Fix list view column alignments

---

src/components/Overview/AboutSection.tsx
src/components/Overview/IntroBanner.tsx

https://issues.redhat.com/browse/RHTAPBUGS-145
https://issues.redhat.com/browse/RHTAPBUGS-168
- Update overview page microcopy
- Add channel to slack url

Overview page content updates

---

src/components/Environment/create/CreateEnvironmentForm.tsx
src/components/Environment/create/KubeconfigUploadField.tsx
src/shared/components/formik-fields/FileUploadField.tsx

https://issues.redhat.com/browse/RHTAPBUGS-221
Update environment form microcopy

Update environment form microcopy

---

src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/ImportForm.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx
src/components/ImportForm/SampleImportForm.tsx
src/components/ImportForm/__tests__/GitImportForm.actions.spec.tsx
src/components/ImportForm/__tests__/GitImportForm.rendering.spec.tsx
src/components/ImportForm/__tests__/ImportForm.spec.tsx
src/components/ImportForm/__tests__/SampleImportForm.spec.tsx
src/components/ImportForm/utils/__tests__/useValidApplicationName.spec.ts
src/components/ImportForm/utils/useValidApplicationName.ts

https://issues.redhat.com/browse/RHTAPBUGS-237
Use repo name from component url as a default application name, and allow user to change it in the review step, if it is desired.
https://user-images.githubusercontent.com/9964343/237036607-20b76e49-c5a9-43c3-9253-25f10ebfe211.mov

recommend better application name based on the component url

---

src/__data__/pipelinerun-data.ts
src/__data__/pod-data.ts
src/components/ApplicationDetails/__data__/WorkflowBuildPipelinesData.ts
src/components/ApplicationDetails/__data__/WorkflowTestPipelinesData.ts
src/components/ApplicationDetails/__data__/mock-pipeline-run.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/test-pipeline-data.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
src/components/Commits/__data__/pipeline-with-commits.ts
src/components/Components/__data__/mock-pipeline-run.ts
src/components/LogViewer/__data__/pipelineRunMocks.ts
src/components/PipelineRunDetailsView/__data__/mockVisualizationData.ts
src/components/PodLogs/__data__/pod-mock-data.ts
src/components/TaskRunListView/__data__/mock-TaskRun-data.ts
src/components/topology/__data__/pipeline-test-data.ts
src/consts/pipeline.ts
src/utils/create-utils.ts

- https://issues.redhat.com/browse/HAC-3913
- Update the pipeline service account name to `appstudio-pipeline`.
No UI change.

Update pipeline service account to appstudio-pipeline

---

integration-tests/cypress.config.ts
integration-tests/package-lock.json
integration-tests/package.json

https://issues.redhat.com/browse/HAC-3914
e2e: enhance ss and video quality

e2e: enhance ss and video quality

---

src/components/ApplicationDetails/ApplicationHeader.tsx
src/components/ApplicationDetails/__tests__/ApplicationHeader.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-144
Application header update

Application header URL change

---

src/pages/EnvironmentsListPage.tsx

https://issues.redhat.com/browse/RHTAPBUGS-218
Remove help topic link from environments page
/cc @rohitkrai03

Remove environments page help topic link

---

src/components/Commits/CommitDetails/__tests__/CommitDetailsView.spec.tsx
src/components/IntegrationTest/tabs/IntegrationTestPipelineRunTab.tsx
src/components/PipelineRunListView/PipelineRunsListView.tsx
src/hooks/__tests__/usePipelineRunsWithStatus.ts
src/hooks/index.ts
src/hooks/useCommitPipelineruns.ts
src/hooks/usePipelineRunsWithStatus.ts

https://issues.redhat.com/browse/RHTAPBUGS-255
The pipelinerun scan status row was recently updated to use pipelinerun object with augmented scan status, but the commits & integration tests tabs were not updated along with it.
/cc @jeff-phillips-18 @rohitkrai03

Use pipelinerun with scan status for commits & integration tests tabs

---

src/components/ImportForm/ReviewSection/RuntimeSelector.tsx

https://issues.redhat.com/browse/RHTAPBUGS-244
enable docker runtime even when CDQ fails

enable docker runtime when detection fails

---

integration-tests/cypress.config.ts

https://issues.redhat.com/browse/HAC-3932
Fix Mochawesome report's screenshot attachment.

fix screenshots in mocha report

---

src/components/Overview/AboutSection.tsx

- https://issues.redhat.com/browse/RHTAPBUGS-260
- Update the link for SLSA spec in Overview page.
NO UI change.

Update the SLSA spec link in overview page

---

src/components/ApplicationDetails/tabs/overview/visualization/utils/node-utils.ts

- https://issues.redhat.com/browse/RHTAPBUGS-273
- Fix the links for deployments tab in app lifecycle visualization.
Uploading Screen Recording 2023-05-15 at 3.28.42 PM.mov…

Fix app lifecycle node links for deployments tab

---

integration-tests/cypress.config.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
pr_check.sh

Don't remove app if the test fails. Applies to Basic Happy Path and Advanced Happy Path tests.
Related issue: [HAC-3982](https://issues.redhat.com/browse/HAC-3982)

Don't remove app if test failed.

---

integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-3936
- Validate CVE clair scan results in pipeline run details page.
- Click on Vulnerabilities  view logs and validate Logs.
- Validate CVE clair scan results in pipeline run List page.
- Validate Clair scan node on Pipeline runs details page.
- Validate Logs on Logs Tab in Drawer Panel.

e2e: cve scan test case

---

src/components/PageAccess/NoAccessState.tsx
src/components/PageAccess/__tests__/NoAccessState.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-146
Replace the microcopy in the "no access" empty state for RHTAP users.  
**Before:**
---
**After:**
cc: @abigaeljamie

update no-access empty state message

---

integration-tests/Dockerfile
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-3990
e2e automation : SBOM
- Validate SBOM link is displayed on components Tab.
- Validate SBOM is displayed on Pipeline Run details.
- Copy cosign Download sbom CMD and execute in terminal and verify.
- Validate SBOM logs on Pipeline Run details by clicking on View SBOM link.

e2e: sbom test case automation

---

src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/SampleImportForm.tsx

- https://issues.redhat.com/browse/RHTAPBUGS-311
- Track failed import events along with successful creation of application and components.
NO UI change.

Track failed import events

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx

- https://issues.redhat.com/browse/RHTAPBUGS-239
- Only show one label for default build pipeline switch.
https://github.com/openshift/hac-dev/assets/6041994/89c9144f-fe57-4117-b48d-87f3ae5d2650

Show only one label for default build pipeline switch

---

integration-tests/README.md

https://issues.redhat.com/browse/HAC-3927
https://issues.redhat.com/browse/HAC-3928
Updated documentation on the cypress tests, how to run them, and the CI they also run on
- Documentation content changes

Update tests readme

---

README.md

- https://github.com/openshift/hac-dev/issues/432
- Updating the Readme to remove KCP related npm command and adding legacy peer dependency flag for npm install.
- Trying out the new main-next branch CI.

Update readme and check main-next CI

---

src/shared/components/dropdown/BasicDropdown.scss
src/shared/components/dropdown/BasicDropdown.tsx
src/shared/components/formik-fields/DropdownField.tsx

https://issues.redhat.com/browse/RHTAPBUGS-245
Add invalid indicator styles to dropdown, and indicate when runtime is not detected.
https://github.com/openshift/hac-dev/assets/20013884/02256fdd-062c-4f77-a602-eca5d7d02b61

Add error styles to runtime dropdown

---

integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-4046
**Create A new Integration Test using the image bundle**
Make a commit and validate the EC on pipeline run details.
Validate **Logs** Tab.
Validate **Security** Tab : check Result summary, Rules are displayed and check `Blocking CVE check` is failed and verify its Message is displayed.
Add above Test case in **Advance flow**.

e2e: Enterprise Contract

---

src/components/Overview/IntroBanner.tsx
src/hooks/__tests__/useSignupStatus.spec.ts
src/hooks/index.ts
src/hooks/useSignupStatus.ts
src/utils/flag-utils.ts
src/utils/signup-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-351
Poll for signup status in the landing page if a user is in the waitlist.

Poll for signup status if signup is pending

---

pact-tests/get-application.pact.spec.ts

Update the expected body of a contract for the `Get application` test case.

Update expected body for the Get application response.

---

README.md
pactTests.md

Add documentation about Pact tests.

Add a README about Pact tests.

---

integration-tests/support/pageObjects/pages-po.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/utils/Applications.ts

https://issues.redhat.com/browse/HAC-4225
1. Add secret while creating component.
2. validate the created secret using the API.

e2e: Add Secret validation

---

integration-tests/cypress.config.ts
integration-tests/package-lock.json
integration-tests/package.json
integration-tests/support/commands/index.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/tests/create-application-from-private-git-form.spec.ts
integration-tests/tests/create-application-from-private-git-source.spec.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/tests/environments-tests.spec.ts
integration-tests/tsconfig.json

https://issues.redhat.com/browse/HAC-4226
Removed unused grep lib and added build validation in env test

e2e update : Removed unused grep lib and added build validation in env test

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/SampleImportForm.tsx
src/components/ImportForm/SampleSection/SampleSection.tsx
src/components/ImportForm/__tests__/SampleImportForm.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-246

Sample update copy

---

src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/components/ImportForm/utils/validation-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-67
- Removes help popover
- Updates validation text for incorrect URL
- Updates validation text for private repository

update repo validation texts

---

src/components/ImportForm/CloseImportFormModal.tsx
src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/__tests__/CloseImportFormModal.spec.tsx
src/components/ImportForm/__tests__/GitImportForm.actions.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-258
If the user tries to leave the import form, confirmation modal should be shown

add modal for back, cancel action in import form

---

src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx
src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListHeader.ts
src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx

https://issues.redhat.com/browse/HAC-4275
Changes `Github URL` to `GitHub URL`, `Integration Test` to `Integration test`

Fix integration test text

---

integration-tests/tests/advanced-happy-path.spec.ts
src/components/Commits/CommitsListView.tsx
src/components/Commits/__tests__/CommitsListView.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-268
Update commit list section heading to use "Latest commits" in all the places.
cc: @Ranelim

update commit list title to be consistent

---

src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.scss
src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx
src/components/IntegrationTest/IntegrationTestForm/IntegrationTestView.tsx
src/components/IntegrationTest/IntegrationTestForm/__tests__/IntegrationTestView.spec.tsx
src/components/IntegrationTest/IntegrationTestForm/types.ts
src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts
src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts
src/shared/components/formik-fields/DropdownField.tsx
src/types/coreBuildService.ts

https://issues.redhat.com/browse/HAC-4171
Adds environment dropdown to integration test creation form

Add ephemeral environment dropdown

---

config/remotePlugin.js
src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/tabs/ReleasesTab.tsx
src/components/Releases/ReleaseDetailsView.tsx
src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/ReleasesEmptyState.tsx
src/components/Releases/ReleasesListHeader.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/ReleasesListView.tsx
src/components/Releases/__data__/mock-release-data.ts
src/components/Releases/__tests__/ReleaseDetailsView.spec.tsx
src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/components/Releases/__tests__/ReleasesListRow.spec.tsx
src/components/Releases/__tests__/ReleasesListView.spec.tsx
src/hooks/__tests__/useApplicationReleases.ts
src/hooks/__tests__/useApplicationSnapshots.ts
src/hooks/__tests__/useReleaseStatus.ts
src/hooks/index.ts
src/hooks/useApplicationReleases.ts
src/hooks/useApplicationSnapshots.ts
src/hooks/useReleaseStatus.ts
src/pages/ReleasePage.tsx
src/types/index.ts
src/types/release.ts

https://issues.redhat.com/browse/HAC-4086
https://issues.redhat.com/browse/HAC-4087
Add release objects pages.
Set up releases: https://gist.github.com/rottencandy/372135fbef5f8530f748eb3abedf8fe2

Add release object list & details pages

---

src/components/PipelineRunDetailsView/visualization/utils/__tests__/pipelinerun-graph-utils.spec.ts
src/components/PipelineRunDetailsView/visualization/utils/pipelinerun-graph-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-328
UI shows `Test failure` status for the task that produces error/failure in `TEST_OUTPUT`  result but while hovering over those task, it shows all the steps inside is `succeeded`. This PR marks the status of last step in those tasks as `Test Failure` step.
**Before:**
**After:**
1. Hover on the pipeline run task which has Test failures.
cc: @MariaLeonova

show test failure warning status for the last step of a task in the tooltip

---

integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-4267
e2e update: updated integration Test and Enterprise Contracts Test
Update ImageBundle to github repo for following scenarios :
1. Integration test pass pipeline
2. Integration test fail pipeline
3. Enterprise Contract pipeline and validation.
4. Integration test add and update.

e2e update: updated integration Test and Enterprise Contracts Test

---

integration-tests/support/pages/EnvironmentsPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-4383
e2e update :
1. Increase deployment validation timeout in BOYC test case and
2. add pipeline run status validation in advance flow.

e2e update: add pipeline run status validation and increase BOYC dep timeout

---

src/components/ApplicationListView/ApplicationListHeader.ts
src/components/Commits/CommitsListHeader.tsx
src/components/Commits/CommitsListRow.tsx
src/components/Commits/CommitsListView.tsx
src/components/Commits/__data__/pipeline-with-commits.ts
src/components/Commits/__tests__/CommitsListRow.spec.tsx
src/components/Commits/__tests__/commit-status.spec.ts
src/components/Commits/commit-status.ts
src/components/Commits/tabs/CommitOverviewTab.tsx
src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestListHeader.ts
src/components/PipelineRunDetailsView/RelatedPipelineRuns.tsx
src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/visualization/utils/__tests__/RelatedPipelineRuns.spec.tsx
src/components/PipelineRunListView/PipelineRunListHeader.ts
src/components/TaskRunListView/TaskRunListHeader.ts
src/components/TaskRunListView/TaskRunListRow.tsx
src/consts/pipelinerun.ts
src/hooks/__tests__/usePipelineRuns.spec.ts
src/hooks/useBuildPipelines.ts
src/hooks/usePipelineRuns.ts
src/hooks/useSnapshots.ts
src/shared/components/action-menu/ActionMenu.scss
src/shared/components/action-menu/ActionMenu.tsx
src/shared/components/table/Table.scss
src/utils/__tests__/commits-utils.spec.ts
src/utils/commits-utils.ts

Fixes [HAC-3712](https://issues.redhat.com/browse/HAC-3712)
Show commits from manual/default build pipelines. Not all fields are available but show the fields that are.

Show commits for manual/default build pipelines

---

integration-tests/tests/create-application-from-public-git-source.spec.ts
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/utils/__tests__/validation-utils.spec.ts
src/components/ImportForm/utils/validation-utils.ts
src/shared/components/formik-fields/field-types.ts
src/shared/utils/number-spinner.tsx
src/shared/utils/request-size-input.tsx

https://issues.redhat.com/browse/RHTAPBUGS-51
add default min max values for CPU/memory based on https://github.com/codeready-toolchain/host-operator/blob/master/deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml#L177-L190

add default min and max limit for CPU and memory on Review component card

---

integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/tests/environments-tests.spec.ts

https://issues.redhat.com/browse/HAC-4418
**e2e : Download pipeline run logs of all the e2e test case's.**
update all the e2e to Download pipeline run logs irrespective of the pipeline run status.
Pipeline runs logs are essential to debug the issue in case of e2e test failure.

e2e : Download pipeline run logs of all the e2e test cases

---

src/components/IntegrationTest/IntegrationTestForm/IntegrationTestForm.tsx

https://issues.redhat.com/browse/RHTAPBUGS-195
Removed the text around "Only validated versions" from IntegrationTest creation page

Remove validated version notice from subtitle

---

integration-tests/support/pages/AddComponentPage.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/utils/Applications.ts

https://issues.redhat.com/browse/HAC-4453
e2e : update task run name

e2e : update task run name

---

src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts
src/types/coreBuildService.ts

https://issues.redhat.com/browse/HAC-4384
When creating the IntegrationScenario and using the Environment dropdown, the IntegrationTestScenario that is created is missing the mandatory [spec.environment.configuration.env](https://github.com/redhat-appstudio/application-api/blob/main/api/v1alpha1/environment_types.go#L155) field, causing issues when creating the ephemeral environment.
**Add/Edit integration test result:**
**Ephemeral environment gets created:**
**Deployed successfully to development environment:**
1.  Create an RHTAP Application with a single example component
2. Create an IntegrationTestScenario and select the development environment from the Environment dropdown
3. Run a component build.
4. After the build pipelinerun execution, an ephemeral environment should be created …

add ephemeral environment configuration field

---

src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/RuntimeSelector.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/components/ImportForm/utils/cdq-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-270
If the git url contains branch & context segments, use that to fill the reference & context directory fields.
https://github.com/openshift/hac-dev/assets/20013884/260d0573-a858-451c-99dc-b258dbc8b9cd
Use a git url with context/path segments.

Set git branch & context fields if present in url

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-480
Adds link back to the Integration test object thats is defines this test pipelinerun.
Visit test pipelinerun details page to see the link of the Integration test object.

add integration test link in test pipelinerun details page

---

src/components/Commits/CommitDetails/CommitDetailsView.tsx

https://issues.redhat.com/browse/RHTAPBUGS-187
Adds `Commit <id>` to header title

Fix commit title

---

src/components/ApplicationDetails/ApplicationHeader.tsx
src/components/Components/ComponentListItem.tsx
src/components/Components/ComponentListView.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/EnterpriseContractView/EnterpriseContractView.tsx
src/components/EnterpriseContractView/ReleasePolicyPackageItem.tsx
src/components/ImportForm/SampleSection/SampleCard.tsx
src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx
src/components/Overview/AboutSection.tsx
src/components/Overview/IntroBanner.tsx
src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/shared/components/links/ExternalLink.tsx
src/utils/render-utils.tsx

https://issues.redhat.com/browse/RHTAPBUGS-150
- Updates `ExternalLink` to have icon by default and hide it using `hideIcon` prop
- Updates `ExternalLink`s with normal text to have icon
- Hides Icons with normal url text to not to have an icon
P.S: Alignment issue solved here -> https://github.com/openshift/hac-dev/pull/658

Add icon externallink

---

integration-tests/support/constants/PageTitle.ts
integration-tests/utils/Login.ts

[https://issues.redhat.com/browse/HAC-4543](https://issues.redhat.com/browse/HAC-4543)
Second attempt to stabilize clicking on navigation items. It seems that click happens before the page is loaded, so it may cause flakiness. Adding wait for the overview page after login and before clicking on the menu item.

Add check for Overview page.

---

pact-tests/get-application.pact.spec.ts

Add a new item to conditions to fix failing tests here: https://github.com/redhat-appstudio/application-service/actions/runs/5601035583/job/15172588699
Update the existing Pact test.

Update Pact tests

---

src/components/Releases/ReleasesEmptyState.tsx

https://issues.redhat.com/browse/RHTAPBUGS-460
Updates ReleaseList Empty state

Fix release empty state

---

src/components/EnterpriseContractView/EnterpriseContractTable/EnterpriseContractRow.tsx
src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContractView/types.ts
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx

https://issues.redhat.com/browse/RHTAPBUGS-445
add solutions to EC results
-------------------------------

add solution field to EC results expanded section

---

helpers/resources/component.yaml
helpers/setup.sh
src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts
src/components/ApplicationDetails/tabs/overview/visualization/hooks/__data__/workflow-data.ts
src/components/ApplicationDetails/tabs/overview/visualization/utils/__tests__/node-utils.spec.ts
src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
src/components/Components/__data__/mock-data.ts
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
src/hooks/__tests__/usePACState.spec.ts
src/hooks/usePACState.ts
src/utils/__tests__/component-utils.spec.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/component-utils.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-4229
Switch to using new build request system annotations and update utils to use new build status format.
Use all methods of configuring PaC.

Switch to new build request system annotations

---

src/components/Commits/tabs/CommitsPipelineRunTab.tsx
src/components/PipelineRunListView/PipelineRunListRow.tsx
src/components/PipelineRunListView/PipelineRunsListView.tsx
src/consts/pipelinerun.ts
src/hooks/__tests__/useScanResults.spec.ts
src/hooks/useScanResults.ts
src/hooks/useTektonResults.ts
src/utils/__tests__/tekton-results.spec.ts
src/utils/tekton-results.ts

https://issues.redhat.com/browse/RHTAPBUGS-545
PipelineRun list view was making too many calls to tekton-results API and the users were hitting rate limit issue in the prod. 
This PR improves the performance of the list page with following changes
1. Batch request the vulnerability calls (added the fetching logic to get vulnerability data for 30 rows in a table in a single API call)
2. reduce the pageSize from `50` -> `30`
3. do not fetch extra calls if the same request is already inflight.
With this changes, each pipelineruns list row will not make any api calls instead the parent will make a single call to fetch all the vulnerabilities and set them accordingly.
Before:
https://github.com/openshift/hac-dev/assets/9964343/4bb2e708-66e5-4ddc-bc00-be2070909480
After: …

Improve performance by batching tekton-results API requests in PLR list pages.

---

config/prod.webpack.config.js
pr_check.sh

Stage environemnt is requesting static assets from stable build which causes the UI not to load.
Let's force the beta build temporary while we focus on the proper fix of creating beta/stable builds.

Force beta build via hard coded deployment

---

integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-4645
e2e update: add wait for page load after deleting IT test in advance flow.

e2e update: add wait for page load after deleting IT test

---

integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts

https://issues.redhat.com/browse/HAC-4706
e2e: Update advance flow pipelineruns Task names.
advance flow failing in Periodic job due to pipeline runs task name got changed.

e2e: Update advance flow pipelineruns Task names

---

src/components/ComponentSettingsForm/ComponentSettingsForm.tsx
src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx
src/components/ImportForm/utils/__tests__/submit-utils.spec.ts
src/components/ImportForm/utils/__tests__/validation-utils.spec.ts
src/components/ImportForm/utils/submit-utils.ts
src/components/ImportForm/utils/types.ts
src/components/ImportForm/utils/validation-utils.ts

- https://issues.redhat.com/browse/HAC-3661
- Added support for selecting or deselecting a component during import flow.
https://github.com/openshift/hac-dev/assets/6041994/00cb2eba-a0b5-4d3e-8b16-7707a76c4906

Add support for selecting components during import flow

---

integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/tests/environments-tests.spec.ts

https://issues.redhat.com/browse/HAC-4740
Add Enterprise contract assertion after Build pipeline run assertion in bellow tests:
1. advance flow.
2. basic flow.
3. environment-tests.spec

e2e: enterprise contract test update

---

src/utils/__tests__/flag-utils.spec.ts
src/utils/flag-utils.ts
src/utils/signup-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-380
Show pending state for signup ProvisioningSpace status.
Ensure UI shows pending state when signup API returns ProvisioningSpace status.

Show pending state for signup ProvisioningSpace status

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx

https://issues.redhat.com/browse/RHTAPBUGS-544
Changes error to warning alert and validation for target port in ComponentReviewCard

make target port warning

---

config/remotePlugin.js
src/components/ImportForm/SecretSection/SecretSection.tsx
src/components/Secrets/SecretForm.tsx
src/components/Secrets/SecretModal.tsx
src/components/Secrets/SecretTypeSelector.tsx
src/components/Secrets/SecretsListView/SecretsList.tsx
src/components/Secrets/SecretsListView/SecretsListHeader.tsx
src/components/Secrets/SecretsListView/SecretsListRow.tsx
src/components/Secrets/SecretsListView/SecretsListView.tsx
src/components/Secrets/__tests___/SecretModal.spec.tsx
src/components/Secrets/__tests___/SecretTypeSelector.spec.tsx
src/components/Secrets/__tests___/SecretsListView.spec.tsx
src/components/Secrets/__tests___/secret-data.ts
src/components/Secrets/__tests___/secret-utils.spec.ts
src/components/Secrets/secret-actions.ts
src/components/Secrets/secret-modal.tsx
src/components/Secrets/secret-utils.ts
src/hooks/UseRemoteSecrets.ts
src/models/index.ts
src/models/remotesecret.ts
src/pages/SecretsListPage.tsx
src/pages/__tests__/SecretsListPage.spec.tsx
src/types/secret.ts
src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

https://issues.redhat.com/browse/HAC-4557
https://issues.redhat.com/browse/HAC-4559
This PR adds Secret list page and delete action on the list.
Additional details:
-  `Learn more` button will be added once docs team provides the required `id`.
- `Add Secret` button will be added in separate PR while we implement Add secret feature.
Access Denied Page:
Secret List page:
Row with labels:
Delete Secret action:
https://github.com/openshift/hac-dev/assets/9964343/73faff0d-5650-4073-9871-8f673eaaa421
cc: @pankajshivpuje @Misjohns

Add secrets list and delete action

---

config/remotePlugin.js
src/components/ApplicationDetails/__data__/WorkflowComponentsData.ts
src/components/Commits/CommitDetails/visualization/__data__/MockCommitWorkflowData.ts
src/components/Commits/__data__/pipeline-with-commits.ts
src/components/Components/__data__/mock-data.ts
src/components/Environment/EnvironmentCard.tsx
src/components/GitLink/GitRepoLink.tsx
src/components/SnapshotDetails/SnapshotDetailsView.tsx
src/components/SnapshotDetails/__tests__/SnapshotDetailsView.spec.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsEmptyState.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsList.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsListHeader.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsListRow.tsx
src/components/SnapshotDetails/tabs/SnapshotOverview.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsEmptyState.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsList.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotOverview.spec.tsx
src/hooks/useAllApplicationEnvironmentsWithHealthStatus.ts
src/pages/SnapshotDetailsPage.tsx
src/pages/__tests__/SnapshotDetailsPage.spec.tsx
src/types/coreBuildService.ts

https://issues.redhat.com/browse/HAC-4576

Add snapshot details

---

src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx

- https://issues.redhat.com/browse/RHTAPBUGS-529
- Added context directory and git ref fields in review section.
https://github.com/openshift/hac-dev/assets/6041994/a2f5410f-f05f-4094-a5cd-aa196660311a

Add git ref and build context fields in review section of import

---

integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/EnvironmentsPage.ts

https://issues.redhat.com/browse/HAC-4843
Update the locators in tests to PF5.

e2e: PF5 upgrade fix

---

pr_check.sh

maybe this time jenkins is going to notice

e2e: deploy fewer dependencies with bonfire

---

integration-tests/support/constants/PageTitle.ts
integration-tests/support/pages/SecretsPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-4885
Add Secrets validation and deletion from UI by navigating to secrets Page in Advance flow.
remove the secrets validation through API in advance flow. 

e2e: Secrets validation and deletion using UI

---

config/dev.webpack.config.js

- https://issues.redhat.com/browse/HAC-4899
- The assets were not loading because of webpack config having `/beta/hac` in the URL instead or `preview`.
No UI change.

Fix the broken style issue on local setup

---

integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pages/tabs/ComponentsTabPage.ts
integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/tests/environments-tests.spec.ts
integration-tests/utils/Applications.ts
integration-tests/utils/UIhelper.ts

https://issues.redhat.com/browse/HAC-4912
Add component details  [HAC-4534](https://issues.redhat.com/browse/HAC-4534) test automation to advance flow.
Refactor the advance flow and basic flow and use common test code validate the latest commits, route, PLR status.

e2e: Component details automation

---

src/components/Environment/EditStrategyModal.tsx
src/components/ImportForm/CloseImportFormModal.tsx
src/components/ImportForm/__tests__/CloseImportFormModal.spec.tsx
src/components/modal/DeleteResourceModal.tsx
src/components/modal/createModalLauncher.tsx

https://issues.redhat.com/browse/RHTAPBUGS-476
fix back and cancel actions for git import form

fix back and cancel action for git import form

---

config/remotePlugin.js
src/components/ImportForm/SourceSection/AuthOptions.tsx
src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/AuthOptions.spec.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/components/ImportForm/SourceSection/useEnablePrivateAuthFlowFlag.ts
src/components/ImportForm/utils/__tests__/auth-utils.spec.ts
src/components/ImportForm/utils/auth-utils.ts
src/utils/flag-utils.ts

https://issues.redhat.com/browse/HAC-4350
Enable private repo auth flow under feature flag

Enable auth flow for private repo

---

src/components/SnapshotDetails/SnapshotDetailsView.tsx

https://issues.redhat.com/browse/RHTAPBUGS-768
Removes action from SnapshotDetails page

Remove snapshot details action

---

pact-tests/application-creation.pact.spec.ts
pact-tests/contracts/application-service/create-application.ts
pact-tests/contracts/application-service/get-application.ts
pact-tests/contracts/application-service/state-params.ts
pact-tests/get-application.pact.spec.ts

https://issues.redhat.com/browse/HAC-4879
During the HAS refactoring, the state handlers were changed. Adopting changes on HAC-dev side.
Related HAS [PR#391](https://github.com/redhat-appstudio/application-service/pull/391/files)

Add parametrized statuses

---

integration-tests/cypress.config.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/utils/Applications.ts
pr_check.sh

https://issues.redhat.com/browse/RHTAPBUGS-822
Make snyk checks run on advanced flow by using the appropriate token as secret.

e2e: enable snyk check

---

.commitlintrc.js
.husky/commit-msg
package-lock.json
package.json

- https://issues.redhat.com/browse/HAC-4811
- Add commit linter to enforce conventional commit messages.

chore: add commitlint to enforce conventional commit messages

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pageObjects/pages-po.ts
integration-tests/tests/basic-happy-path.spec.ts
src/components/Activity/ActivityTab.tsx
src/components/ApplicationDetails/tabs/ApplicationOverviewTab.tsx
src/components/ApplicationDetails/tabs/__tests__/__snapshots__/useWhatsNextItems.spec.ts.snap
src/components/ApplicationDetails/tabs/overview/sections/AppWorkflowSection.tsx
src/components/ApplicationDetails/tabs/useWhatsNextItems.ts
src/components/Commits/CommitsListView.tsx
src/components/Commits/__tests__/CommitsListView.spec.tsx
src/components/Components/ComponentDeployments/ComponentDeploymentsListView.tsx
src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx
src/components/IntegrationTest/IntegrationTestsListView/__tests__/IntegrationTestsListView.spec.tsx
src/components/PipelineRunListView/PipelineRunsListView.tsx
src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
src/components/WhatsNext/WhatsNextSection.tsx
src/shared/components/status-box/StatusBox.tsx
src/shared/components/table/Table.scss
src/shared/components/table/Table.tsx
src/shared/components/table/TableComponent.tsx

Fixes [RHTAPBUGS-138](https://issues.redhat.com/browse/RHTAPBUGS-138)
Removes the `Latest Commits` list from the overview page. Removes the Add Component button from the overview page.
Simplifies the commits list view since we no longer need the `mostRecent` parameter and to utilize the StatusBox portion of the Table component to show loading and empty states.
Update list view components to utilize StatusBox to handle empty state and loading state.
Updates the `Table` component to be testable when using the StatusBox to show empty and loading states.
/cc @Ranelim @misjohns

Improve application overview screen

---

integration-tests/tests/advanced-happy-path.spec.ts

https://issues.redhat.com/browse/HAC-5193
Fixes e2e Advanced flow as the Latest commits were removed from the overview page.

Fix e2e Advanced flow

---

integration-tests/utils/APIHelper.ts

https://issues.redhat.com/browse/RHTAPBUGS-849
Make e2e tests probe the github repo they create until it definitely exists to avoid occasional 404s.

fix(test): wait for new github repo availability

---

integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts

https://issues.redhat.com/browse/RHTAPBUGS-877
pipeline & build service got updated, some labels/names got changed, update the e2e tests

fix(test): update pipeline labels

---

src/components/IntegrationTest/IntegrationTestForm/IntegrationTestSection.tsx

https://issues.redhat.com/browse/RHTAPBUGS-723
Fix the description text in integration form.
**Before:**
**After:**
cc: @MariaLeonova

fix(path-description): modify the integration test path description

---

src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/utils/submit-utils.ts
src/components/ImportForm/utils/types.ts

https://issues.redhat.com/browse/HAC-4586
add `image.redhat.com/generate` annotation to components on creation

feat(import flow): add visibility annotation on component creation

---

src/components/IntegrationTest/IntegrationTestsListView/IntegrationTestsListView.tsx

https://issues.redhat.com/browse/RHTAPBUGS-881
Modify integration filter search to be consistent with component page filter.
**Before:**
**After:**
cc: @MariaLeonova

fix(int-filter): modify integration test search filter field

---

src/components/IntegrationTest/EditParamsModal.tsx
src/components/IntegrationTest/FormikParamsField.tsx
src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts
src/components/IntegrationTest/__tests__/EditParamsModal.spec.tsx
src/components/IntegrationTest/tabs/IntegrationTestOverviewTab.tsx
src/components/IntegrationTest/tabs/__tests__/IntegrationTestOverviewTab.spec.tsx

https://issues.redhat.com/browse/HAC-4840
Add Edit Params modal and params in ITS details view

feat( Integration test):  edit params in details section

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-858
Build and test Pipelinerun details page should contain the snapshot section (if snapshot is available) and it should link us to the snapshot details page.
https://github.com/openshift/hac-dev/assets/9964343/cb8e85c6-f2a9-4652-a9b5-cee0f1f60dfe

fix(add-snpshot-link): add snapshot link in pipelinerun details page

---

src/components/Filter/FilterToolbar.tsx
src/components/Filter/__tests__/FilterToolbar.spec.tsx
src/components/Releases/ReleasesListHeader.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/ReleasesListView.tsx
src/components/Releases/__data__/mock-release-data.ts
src/components/Releases/__tests__/ReleaseOverviewTab.spec.tsx
src/components/Releases/__tests__/ReleasesListRow.spec.tsx
src/components/Releases/__tests__/ReleasesListView.spec.tsx
src/hooks/useSortedResources.ts
src/shared/components/table/Table.tsx
src/shared/components/table/__tests__/Table.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-742
- Create generic filter & sort utils
- Add creation date column to releases list view
- Update releases list page to allow sorting & filtering
https://github.com/openshift/hac-dev/assets/20013884/51436692-8a6c-417b-bf95-5499f42791fe
cc @misjohns
Go to releases list page and use filter/sort.

fix(releases): Enable filtering & sorting on Releases list view

---

integration-tests/cypress.config.ts
integration-tests/package-lock.json
integration-tests/package.json
integration-tests/support/commands/hooks.ts

Cypress should do it automatically with test isolation disabled

chore: remove cypress manual cookie preservation

---

integration-tests/support/pageObjects/global-po.ts
src/components/ApplicationListView/application-actions.ts

https://issues.redhat.com/browse/RHTAPBUGS-491
One liner updates `Delete` action to `Delete application` in Application List view for consistency.

fix(application list): make delete application consistent

---

Caddyfile
build_deploy.sh
pr_check.sh

Revert "Remove caddy file in favor of universal build"

---

src/components/CustomizedPipeline/CustomizePipelines.tsx

https://issues.redhat.com/browse/RHTAPBUGS-717
change the text for custom build pipeline dialog

fix(Custom-build-pipeline-dialog): update text for custom build pipeline

---

integration-tests/cypress.config.ts
integration-tests/support/pageObjects/global-po.ts
integration-tests/support/pageObjects/pages-po.ts
integration-tests/support/pages/ApplicationDetailPage.ts
integration-tests/support/pages/ComponentDetailsPage.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/DeploymentSettingsPage.ts
integration-tests/support/pages/EnvironmentsPage.ts
integration-tests/support/pages/SecretsPage.ts
integration-tests/support/pages/tabs/ComponentsTabPage.ts
integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/tests/create-application-from-public-git-source.spec.ts
integration-tests/tests/create-application-from-sample.spec.ts
integration-tests/tests/environments-tests.spec.ts
integration-tests/utils/APIHelper.ts
integration-tests/utils/Applications.ts
integration-tests/utils/Common.ts
integration-tests/utils/Tokens.ts

https://issues.redhat.com/browse/HAC-5437

chore: update e2e tests for the new component details

---

integration-tests/support/constants/PageTitle.ts
src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/ImportForm.tsx
src/components/ImportForm/__tests__/GitImportForm.rendering.spec.tsx
src/components/ImportForm/__tests__/ImportForm.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-363
Update text for import page.
cc @misjohns
Go to import page.

fix: Update text for import page

---

src/components/PageAccess/NoAccessState.tsx
src/components/PageAccess/__tests__/NoAccessState.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-727
Update message for no access page.
Navigate to a page for which you do not have access to.

fix: Update message for no access page

---

integration-tests/support/pages/EnvironmentsPage.ts
integration-tests/utils/Applications.ts

secret creation shows the value in cypress recordings, make it unreadable

fix(e2e): obscure secrets in video recordings

---

src/components/SnapshotDetails/tabs/SnapshotOverview.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotOverview.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-931
Adds commit label to triggered by section

fix(snapshot): add commit label to triggered by

---

src/components/Secrets/__tests___/secret-utils.spec.ts
src/components/Secrets/utils/secret-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-916
Always add the `ui.appstudio.redhat.com/secret-for` label to remotesecret labels.
https://github.com/openshift/hac-dev/assets/20013884/5387d1d4-2841-4a35-b6da-39a42f7d23b1
Add a deployment secret using secrets form.

fix(secrets): Always add secretFor to remotesecret labels

---

integration-tests/support/pages/tabs/PipelinerunsTabPage.ts

https://issues.redhat.com/browse/RHTAPBUGS-977

fix(e2e): remove inspect-image from task list

---

src/components/ImportForm/utils/submit-utils.ts

https://issues.redhat.com/browse/RHTAPBUGS-921
Samples Build are not starting because visibility annotation is not set properly for Sample imports

fix(RHTAPBUGS-921): add visibility annotation for importing sample components

---

src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx
src/components/Components/ComponentsListRow.tsx
src/components/CustomizedPipeline/CustomizePipelines.tsx
src/components/CustomizedPipeline/__tests__/CustomizePipeline.spec.tsx
src/components/GitLink/GitRepoLink.tsx
src/components/GitLink/__tests__/GitRepoLink.spec.tsx
src/components/SnapshotDetails/tabs/SnapshotComponentsListRow.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsListRow.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-816
Avoid showing repo link if git url is not present in components, and instead show container image url if present.
Create a component with container image instead of git repo (cannot be done through UI currently)

fix(components): Show url for container image components

---

src/shared/components/pipeline-run-logs/logs/LogsTaskDuration.tsx
src/shared/components/pipeline-run-logs/logs/MultiStreamLogs.tsx
src/shared/components/pipeline-run-logs/logs/TektonTaskRunLog.tsx

https://issues.redhat.com/browse/HAC-5389
Waiting for input. Pushed to my fork for keeping the commit online

feat(pipelinelogs): add task duration

---

src/components/ImportForm/SourceSection/AuthOptions.tsx
src/components/ImportForm/SourceSection/__tests__/AuthOptions.spec.tsx
src/components/ImportForm/utils/auth-utils.ts

https://issues.redhat.com/browse/HAC-5453

feat(private-auth): add a form to initiate private auth flow

---

integration-tests/tests/create-application-from-sample.spec.ts

https://issues.redhat.com/browse/RHTAPBUGS-1010

fix(e2e): delete component after it refreshes

---

tmp/hac-proxy.yaml

https://issues.redhat.com/browse/RHTAPBUGS-1021
Adding separate proxy configuration for the registration service

test: update proxy to handle registration endpoints

---

src/components/UserAccess/UserAccessForm/UsernameSection.tsx
src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-999
Fix username validation regex
Use different username formats

fix(access): Fix username validation regex

---

integration-tests/cypress.config.ts
integration-tests/utils/APIHelper.ts
pr_check.sh

https://issues.redhat.com/browse/RHTAPBUGS-1053

fix(e2e): get access token from an existing source

---

src/components/ImportForm/SourceSection/SourceSection.tsx
src/components/ImportForm/SourceSection/__tests__/SourceSection.spec.tsx
src/types/service-provider-integration.ts

https://issues.redhat.com/browse/RHTAPBUGS-1032
Consider GitLab when performing access check for private repositories.
Use a private gitlab repository

fix(import): Handle authorization for private GitLab repository

---

src/components/ImportForm/utils/cdq-utils.ts
src/components/Overview/IntroBanner.tsx
src/components/Overview/__tests__/IntroBanner.spec.tsx
src/pages/ImportPage.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1003
- Avoid stopping creating of sample component if CDQ deletion fails.
- Check CDQ create access for import button
https://github.com/openshift/hac-dev/assets/20013884/b261f9d8-24ae-4e32-9efa-9b4aab44cad2
Create sample on a workspace with maintainer access.

fix(import): Avoid stopping sample creation if CDQ deletion fails

---

src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/ReviewSection/ReviewComponentCard.tsx
src/components/ImportForm/ReviewSection/ReviewSection.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewComponentCard.spec.tsx
src/components/ImportForm/ReviewSection/__tests__/ReviewSection.spec.tsx
src/components/ImportForm/__tests__/GitImportForm.actions.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-757
https://issues.redhat.com/browse/RHTAPBUGS-997
Avoid resetting the application name and component name fields if they'be been modified.
No design changes
https://github.com/openshift/hac-dev/assets/20013884/a1dbcea0-cfad-4fd6-97d1-06e62d57b1d7
Try to create an app that already exists, or change runtime after changing component name.

fix(import): Avoid resetting name input fields if modified

---

src/components/Overview/AboutSection.tsx
src/components/Overview/IntroBanner.tsx
src/components/Overview/__tests__/AboutSection.spec.tsx
src/components/Overview/__tests__/IntroBanner.spec.tsx

Fixes https://issues.redhat.com/browse/RHTAPBUGS-895
Update the slack links from the old devnation slack to current redhat-internal slack.
None
Click through the slack links

fix(slack): update slack links

---

src/components/ImportForm/GitImportForm.tsx
src/components/ImportForm/utils/submit-utils.ts

https://issues.redhat.com/browse/HAC-4812
**Get UX suggestion on the modal text**

fix(import-flow): optmize import flow api requests

---

src/components/Commits/tabs/__tests__/CommitsPipelineRunTab.spec.tsx
src/components/PipelineRunDetailsView/PipelineRunDetailsView.tsx
src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
src/components/PipelineRunListView/__tests__/PipelineRunListRow.spec.tsx
src/components/PipelineRunListView/__tests__/PipelineRunListView.spec.tsx
src/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx
src/components/PipelineRunListView/pipelinerun-actions.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsList.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotPipelineRunsTab.spec.tsx
src/utils/component-utils.ts

https://issues.redhat.com/browse/HAC-5490
Adding rerun option for Build pipelineruns

feat(pipelinerun): add rerun action for Build pipelineRun

---

src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx
src/components/Components/ComponentDetails/tabs/ComponentBuildSettings.tsx
src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.scss
src/components/Components/ComponentDetails/tabs/ComponentNudgesDependencies.tsx
src/components/Components/ComponentDetails/tabs/ComponentNudgesSVG.tsx
src/components/Components/ComponentDetails/tabs/__tests__/ComponentNudgesDependencies.spec.tsx
src/components/SnapshotDetails/tabs/__tests__/SnapshotComponentsList.spec.tsx
src/types/component.ts

https://issues.redhat.com/browse/HAC-5433

feat(components): add nudges dependencies

---

src/components/ReleaseService/ReleasePlan/ReleasePlanListRow.tsx
src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListRow.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1056

fix(release-plan): add undefined check on labels

---

src/components/ImportForm/GitImportForm.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1084

fix(import-flow): close submit progress model before customize pipeline

---

config/remotePlugin.js
src/components/Environment/environment-utils.ts
src/components/IntegrationTest/FormikParamsField.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/ReleasePlanForm.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/ReleasePlanFormPage.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/RunReleasePipelineSection.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/ReleasePlanForm.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/ReleasePlanFormPage.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/RunReleasePipelineSection.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/form-utils.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanListHeader.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanListRow.tsx
src/components/ReleaseService/ReleasePlan/releaseplan-actions.tsx
src/components/Secrets/SecretsForm/ApplicationDropdown.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/pages/CreateReleasePlanPage.tsx
src/pages/EditReleasePlanPage.tsx
src/pages/ReleaseServicesListPage.tsx
src/pages/__tests__/CreateReleasePlanPage.spec.tsx
src/pages/__tests__/EditReleasePlanPage.spec.tsx
src/shared/components/formik-fields/RadioGroupField.tsx
src/shared/components/formik-fields/ToggleableFieldBase.tsx
src/shared/components/formik-fields/field-types.ts
src/shared/components/formik-fields/key-value-input-field/KeyValueInputField.tsx
src/types/coreBuildService.ts

https://issues.redhat.com/browse/HAC-4700
Add release plan form.
Create release plan through release plan form.

feat(releases): Add release plan form

---

src/components/Components/ComponentsListRow.tsx
src/components/Components/__tests__/ComponentListView.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1092

fix(Component): remove sha hash from container image url

---

src/components/Releases/ReleaseOverviewTab.tsx
src/components/Releases/ReleasesListRow.tsx
src/components/Releases/__tests__/ReleaseDetailsView.spec.tsx
src/components/Releases/__tests__/ReleasesListRow.spec.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1026

fix(releases): add links for snapshot in release details and list view

---

src/components/TaskRunDetailsView/TaskRunDetailsView.tsx
src/components/TaskRunDetailsView/__tests__/TaskRunDetailsView.spec.tsx
src/components/TaskRunListView/__data__/mock-TaskRun-data.ts

https://issues.redhat.com/browse/RHTAPBUGS-1068
Navigayes to details page for succeeded Taskruns, else navigates to log pages.

feat(taskrun): update default tab

---

src/hooks/useApplicationPipelineGitHubApp.ts

https://issues.redhat.com/browse/RHTAPBUGS-1128
change github app URL and name

fix(github-app): change github app url and name

---

src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContractView/__tests__/utils.spec.ts
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx
src/components/EnterpriseContractView/utils.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1100
extract ec results from task run logs from tekton results

fix(EnterpriseContract): show ec results under security tab from tkn

---

src/components/ReleaseService/ReleaseServiceEmptyState.tsx
src/components/Releases/ReleasesEmptyState.tsx

https://issues.redhat.com/browse/RHTAPBUGS-1122
Update Release service & Release plan links to a working one

Fix(release): Update release service link

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ComponentRelation/ComponentRelationForm.tsx
src/components/ComponentRelation/ComponentRelationModal.tsx
src/components/ComponentRelation/ComponentRelationshipDropdowns.tsx
src/components/ComponentRelation/__tests__/ComponentRelationForm.spec.tsx
src/components/ComponentRelation/__tests__/ComponentRelationModal.spec.tsx
src/components/ComponentRelation/__tests__/ComponentRelationshipDropdowns.spec.tsx
src/components/ComponentRelation/__tests__/useNudgeData.spec.ts
src/components/ComponentRelation/__tests__/utils.spec.ts
src/components/ComponentRelation/cr-modals.tsx
src/components/ComponentRelation/type.ts
src/components/ComponentRelation/useComponentRelationAction.ts
src/components/ComponentRelation/useNudgeData.ts
src/components/ComponentRelation/utils.ts
src/components/Components/__data__/mock-data.ts

https://issues.redhat.com/browse/HAC-5432
add component relation modal for applications
TODO:

feat(Component-relationship): add modal to define component relationship

---

src/components/PipelineRunDetailsView/tabs/PipelineRunLogsTab.tsx
src/pages/GithubRedirectPage.tsx
src/pages/__tests__/GithubRedirectPage.spec.tsx
src/shared/components/pipeline-run-logs/PipelineRunLogs.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1124

fix(GithubRedirect): use task name instead of task run

---

src/components/ReleaseService/ReleasePlan/ReleasePlanForm/RunReleasePipelineSection.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/ReleasePlanForm.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/RunReleasePipelineSection.spec.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanForm/form-utils.ts
src/components/ReleaseService/ReleasePlan/ReleasePlanListHeader.tsx
src/components/ReleaseService/ReleasePlan/ReleasePlanListRow.tsx
src/types/coreBuildService.ts

https://issues.redhat.com/browse/KFLUXBUGS-572
update release plan form
=============#############################============
=============##############################===========

fix(release-plan): update release plan form, add status and release plan addmision column

---

src/components/Overview/IntroBanner.tsx
src/components/Overview/__tests__/IntroBanner.spec.tsx

- https://issues.redhat.com/browse/KFLUXBUGS-1120
- Update slack channel and fix typo for Red Hat.

fix(overview): change slack channel name and typo fix

---

src/components/Secrets/SecretsForm/AddSecretForm.tsx
src/components/Secrets/SecretsForm/SecretTypeSubForm.tsx
src/components/Secrets/SecretsListView/SecretsListHeader.tsx
src/components/Secrets/SecretsListView/SecretsListRow.tsx
src/components/Secrets/__tests___/AddSecretForm.spec.tsx
src/components/Secrets/__tests___/SecretTypeSubForm.spec.tsx
src/components/Secrets/__tests___/SecretsListView.spec.tsx
src/components/Secrets/__tests___/secret-utils.spec.ts
src/components/Secrets/__tests___/secret-validation.spec.ts
src/components/Secrets/utils/secret-utils.ts
src/components/Secrets/utils/secret-validation.ts
src/types/secret.ts
src/utils/__tests__/create-utils.spec.ts

https://issues.redhat.com/browse/HAC-5711
- Refactor Add secret form to remove the Deployment option from it.
- Remove mention of deployments from the Secret list page

feat(secrets): remove deployments from secrets

---

src/components/IntegrationTest/IntegrationTestForm/utils/__tests__/create-utils.spec.ts
src/components/IntegrationTest/IntegrationTestsListView/__data__/mock-integration-tests.ts

* update url of redhat-appstudio/integration-examples since it is migrated to konflux-ci
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
[STONEINTG-837](https://issues.redhat.com/browse/STONEINTG-837)
update url of redhat-appstudio/integration-examples since it is migrated to konflux-ci

feat(STONEINTG-837): update url of redhat-appstudio/integration-examples

---

src/components/Secrets/utils/secret-utils.ts

https://issues.redhat.com/browse/KFLUXBUGS-1275

fix(Secret): add namespace as target to Remote secret creation

---

config/remotePlugin.js
src/components/ReleaseService/ReleasePlan/TriggerRelease/ReleasePlanDropdown.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/SnapshotDropdown.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/TriggerReleaseForm.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/TriggerReleaseFormPage.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/ReleasePlanDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/SnapshotDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/TriggerReleaseForm.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/TriggerReleaseFormPage.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/TriggerRelease/form-utils.ts
src/components/ReleaseService/ReleasePlan/__tests__/releaseplan-actions.spec.tsx
src/components/ReleaseService/ReleasePlan/releaseplan-actions.tsx
src/pages/TriggerReleasePlanPage.tsx
src/pages/__tests__/TriggerReleasePlanPage.spec.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1176, 
https://issues.redhat.com/browse/KFLUXBUGS-1177, 
https://issues.redhat.com/browse/KFLUXBUGS-1178
1. Pre selects release plan
2. Only lists snapshots from same application
3. redirects to newly crated Release details page.

fix(release): fix trigger release

---

src/components/ApplicationDetails/ApplicationThumbnail.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1300

fix(Application): add application thumbnail check on resource metadata

---

src/components/ImportForm/PipelineSection/PipelineSection.tsx
src/components/ImportForm/PipelineSection/__tests__/usePipelineTemplate.spec.ts
src/components/ImportForm/PipelineSection/usePipelineTemplate.ts
src/components/ImportForm/__tests__/submit-utils.spec.ts
src/components/ImportForm/submit-utils.ts

https://issues.redhat.com/browse/HAC-5719
use ImageRepository CR instead of `'image.redhat.com/generate'` annotations.

fix(ImageRepository): use ImageRespository cr instead of component annotation

---

src/utils/__tests__/create-utils.spec.ts
src/utils/create-utils.ts

- Do not send generate image annotation since we are creating image repository CR now.

fix(import): do not send generate annotation in component

---

src/components/ImportForm/ComponentSection/ComponentSection.tsx
src/components/ImportForm/type.ts

https://issues.redhat.com/browse/KFLUXBUGS-1318
add input for docker file path

fix(ImportFlow): add input field for docker file path

---

src/utils/create-utils.ts

https://issues.redhat.com/browse/KFLUXBUGS-1322
add annotation `'image-controller.appstudio.redhat.com/update-component-image'` while create ImageRepository CR.

fix(ImageRepository): add iimage controller annontation while create IR cr

---

src/hooks/usePACState.ts
src/hooks/usePACStatesForComponents.ts

https://issues.redhat.com/browse/KFLUXBUGS-1307
fix the build pipeline status once the PR is merged on target repo

fix(BuildPipeline): filter pipeine run based on sender annotation

---

integration-tests/support/pageObjects/createApplication-po.ts
integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/SecretsPage.ts
integration-tests/support/pages/tabs/IntegrationTestsTabPage.ts
integration-tests/support/pages/tabs/LatestCommitsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts
integration-tests/utils/Applications.ts

Fix the advanced happy path flow as it is broken now due to large UI changes.

Fix advanced happy path

---

pr_check.sh

Add a `e2e-hac-` prefix for a generated user to ease the removal of repositories created by tests.

test: add prefix for username

---

src/components/GitLink/GitRepoLink.tsx
src/components/GitLink/__tests__/GitRepoLink.spec.tsx
src/utils/__tests__/git-utils.spec.tsx
src/utils/git-utils.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1347
fix URL parsing for gitlab.cee.redhat.com urls

fix(GitRepoLink): add support for gitlab.cee.redhat.com urls

---

src/components/ImportForm/__tests__/GitImportForm.spec.tsx
src/components/Secrets/__tests___/secret-actions.spec.ts
src/components/Secrets/secret-actions.ts
src/components/Secrets/utils/__tests__/service-account-utils.spec.ts
src/components/Secrets/utils/service-account-utils.ts
src/types/secret.ts

https://issues.redhat.com/browse/KFLUXBUGS-1353
Links & unlinks image pull secrets to Service account upon creation & deletion.

fix(secret): link serviceaccount

---

tmp/keycloak.py

Don't verify the certificate when creating a user in a keycloak. It is added due to test deployments in infra-deployments PR check jobs that don't have proper certifications setup.

fix(test): don't verify certificate

---

pr_check.sh

Test pr check

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/consts/pipelinerun.ts

https://issues.redhat.com/browse/HAC-5538
Adds a block in Details page to show snapshot creation status.

feat(pipelinerun): add snapshot creation message

---

src/components/PipelineRunDetailsView/tabs/PipelineRunDetailsTab.tsx
src/components/PipelineRunDetailsView/tabs/__tests__/PipelineRunDetailsTab.spec.tsx
src/utils/pipeline-utils.ts

fix view sbom link for deprecated pipeline run type

fix(PipelineRunDetailsTab): support deprecated pipeline run for view sbom

---

src/components/ImportForm/__tests__/GitImportForm.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueModal.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/AddIssueSection.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/CVEComponentDropDown.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/CVEFormContent.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/ComponentField.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/CVEFormContent.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/AddIssueSection/__tests__/ComponentField.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/form-utils.spec.ts
src/components/ReleaseService/ReleasePlan/TriggerRelease/form-utils.ts
src/types/coreBuildService.ts

https://issues.redhat.com/browse/KFLUXBUGS-1203
https://issues.redhat.com/browse/KFLUXBUGS-1198
- Updates Modal for CVE inout
- Changes structure for bugs and cves in Release data

Update CVE Modal fields and Issues output

---

integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/utils/UIhelper.ts

Stabilize test suites by skipping [SBOM](https://issues.redhat.com/browse/HAC-5807) check and check for [vulnerabilities](https://issues.redhat.com/browse/HAC-5808) as described in related issues.

test: stabilize tests by skipping failing ones

---

src/hooks/useScanResults.ts

https://issues.redhat.com/browse/HAC-5787
Adds a field to Tekton Vulnerability scan

feat(vulnerability): add new result type

---

src/components/IntegrationTest/IntegrationTestForm/utils/create-utils.ts

* Since users can manually modify the .spec.contexts field of their integrationTestScenario, the edit page should not overwrite it with the default data
* See more in [STONEINTG-974](https://issues.redhat.com/browse/STONEINTG-974)
Signed-off-by: dirgim <kpavic@redhat.com>

feat(STONEINTG-974): keep ITS contexts field when editing

---

src/components/UserAccess/UserAccessForm/UsernameSection.tsx
src/components/UserAccess/UserAccessForm/__tests__/UsernameSection.spec.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1492
Updates User access tooltip in GrantAccess Page

Update workspace tooltip

---

src/components/EnterpriseContractView/__data__/mockEnterpriseContractLogsJson.ts
src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContractView/useEnterpriseContractResultFromLogs.tsx

Reverts openshift/hac-dev#971
https://issues.redhat.com/browse/KFLUXBUGS-1577

Revert "fix(ec): use only results from `report-json` step"

---

src/components/Components/ComponentDetails/__tests__/ComponentDetails.spec.tsx
src/components/Components/ComponentDetails/tabs/ComponentDetails.tsx
src/hooks/__tests__/usePipelineRuns.spec.ts
src/hooks/usePipelineRuns.ts

https://issues.redhat.com/browse/KFLUXBUGS-1379
Updates component image to show IMAGE_URL from latest pipeline and fall back to containerImage if unavailable.

fix(components): update imageURL

---

src/components/IntegrationTest/EditParamsModal.tsx
src/components/IntegrationTest/__tests__/EditParamsModal.spec.tsx

https://issues.redhat.com/browse/KFLUXBUGS-1524
no visual changes

fix: format integration test param in the EditParamsModal

---

src/components/ApplicationDetails/__data__/mock-pipeline-run.ts
src/components/PipelineRunDetailsView/__tests__/PipelineRunDetailsView.spec.tsx
src/components/PipelineRunListView/__tests__/pipelinerun-actions.spec.tsx
src/components/PipelineRunListView/pipelinerun-actions.tsx
src/consts/pipelinerun.ts

https://issues.redhat.com/browse/KFLUXBUGS-1605

fix: enable rerun action only forpush builds

---

src/components/ComponentRelation/__tests__/useComponentRelationAction.spec.ts
src/components/ComponentRelation/useComponentRelationAction.ts
src/components/ComponentRelation/utils.ts

https://issues.redhat.com/browse/KFLUXBUGS-1453
add permission checks for component relationships action

fix: check permission for Component relationships

---

integration-tests/support/pages/ComponentsPage.ts
integration-tests/tests/advanced-happy-path.spec.ts

Stabilise private and advanced test.

Fix private and advanced tests

---

src/components/Components/ComponentDetails/ComponentDetailsView.tsx

[KFLUXBUGS-1502](https://issues.redhat.com//browse/KFLUXBUGS-1502)
The delete action is disable on component detail page if not permitted.

fix(KFLUXBUGS-1502): delete action on component detail

---

integration-tests/tests/advanced-happy-path.spec.ts

Fix the integration test name in the integration test's Pipeline rus tab.

fix(test): fix integration test name

---

src/components/ReleaseService/ReleasePlan/TriggerRelease/ReleasePlanDropdown.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/SnapshotDropdown.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/TriggerReleaseForm.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/TriggerReleaseFormPage.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/ReleasePlanDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/SnapshotDropdown.spec.tsx
src/components/ReleaseService/ReleasePlan/TriggerRelease/__tests__/TriggerReleaseForm.spec.tsx

[KFLUXBLUGS-1494](https://issues.redhat.com/browse/KFLUXBUGS-1494)
When the release plan is changed we should also change the snapshots.

fix(KFLUXBUGS-1494): get correct snapshots

---

OWNERS

chore: add reviewers

---

src/components/GithubRedirect.tsx
src/pages/GithubRedirectPage.tsx
src/pages/__tests__/GithubRedirectPage.spec.tsx
src/utils/__tests__/pipeline-utils.spec.ts
src/utils/pipeline-utils.ts
src/utils/tekton-results.ts

https://issues.redhat.com/browse/KFLUXBUGS-1636
https://issues.redhat.com/browse/KFLUXBUGS-1424

fix: use the correct workspace based on namespace for Github redirect

---

src/components/ReleaseService/ReleasePlanAdmission/ReleasePlanAdmissionListView.tsx

[KFLUXBUGS-1144](https://issues.redhat.com//browse/KFLUXBUGS-1144)
Contributors with list permissions can read the RPA list view

fix(KFLUXBUGS-1144): readable RPAs for contributors

---

src/components/ApplicationDetails/ApplicationDetails.tsx
src/components/ApplicationDetails/component-actions.tsx
src/components/ApplicationDetails/tabs/__tests__/__snapshots__/useWhatsNextItems.spec.ts.snap
src/components/ApplicationDetails/tabs/useWhatsNextItems.ts
src/components/Components/ComponentDetails/ComponentDetailsView.tsx
src/components/Components/ComponentListView.tsx

[KFLUXBUGS-902](https://issues.redhat.com//browse/KFLUXBUGS-902)
Disable pipeline actions for contributors

fix(KFLUXBUGS-902): disable pipeline actions for contributors

---

src/components/ApplicationListView/ApplicationListView.tsx
src/components/ApplicationListView/__tests__/ApplicationListView.spec.tsx

[KFLUXBUGS-1540](https://issues.redhat.com//browse/KFLUXBUGS-1540)
Application list can be filtered by name

feat(KFLUXBUGS-1540): filter on Applications

---

OWNERS
integration-tests/OWNERS

update owners file

---

src/utils/pipeline-utils.ts

[KFLUXBUGS-1485](https://issues.redhat.com//browse/KFLUXBUGS-1485)
When a pipeline run is stopped, it will display the status as cancelling while tasks are terminating and cancelled when done.

fix(KFLUXBUGS-1485): cancelled state on stopped runs

---

integration-tests/support/pages/ComponentsPage.ts
integration-tests/support/pages/tabs/PipelinerunsTabPage.ts
integration-tests/tests/advanced-happy-path.spec.ts
integration-tests/tests/basic-happy-path.spec.ts

Fix and stabilize tests. Debug the Advanced test behavior on a CI system.

fix(e2e): fix and stabilize e2e tests

---

src/components/EnterpriseContractView/__tests__/useEnterpriseContractResultFromLogs.spec.tsx
src/components/EnterpriseContractView/__tests__/utils.spec.ts
src/components/EnterpriseContractView/utils.tsx

https://issues.redhat.com/browse/KONFLUX-5697
with tekton results upgrade tkn logs format changed due to which logs parsing is failing on UI.

fix: ec regex to extract voilation reports from tkn logs

---

src/components/Components/ComponentListView.tsx
src/components/Components/ComponentsListRow.tsx
src/components/Components/__tests__/ComponentListView.spec.tsx

https://issues.redhat.com/browse/KONFLUX-5766

fix: unblock component list loading from pipeline runs

---

src/utils/tekton-results.ts

https://issues.redhat.com/browse/KONFLUX-6989

fix: records API return empty object

---

src/components/NamespacedPage/NamespacedPage.scss

fix: remove absolute position style from hac dev wrapper

---

src/components/ImportForm/PipelineSection/__tests__/usePipelineTemplate.spec.ts
src/components/ImportForm/PipelineSection/usePipelineTemplate.ts

Add the tekton-bundle-builder pipeline to the UI

chore(KFLUXVNGD-222): add tekton-bundle-builder pipeline to ui

---

src/components/AppBanner/AppBanner.tsx
src/components/AppBanner/__tests__/AppBanner.spec.tsx
src/components/NamespacedPage/NamespacedPage.tsx
src/components/NamespacedPage/__tests__/NamespacedPage.spec.tsx

https://issues.redhat.com/browse/ASC-817
Add app banner for the  konflux-ui announcement

fix: add app banner to redirect users to new UI
